### ISSUE TITLE
prerequisite not detected during installation

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#105]
I found that MICROSOFT VISUAL C++ 2010 RUNTIME LIBRARIES is prerequisite to run the IDE. I would like the install program to detect this and correct it.

**Comment by ColinDuquesnoy** [comment]
Thanks for the report. I'll fix that in the packaging script.

**Comment by ColinDuquesnoy** [comment]
The missing libraries should get included in the next release.
