### ISSUE TITLE
comment/uncomment

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#108]
this feature is not working in fixed format COBOL

**Comment by ColinDuquesnoy** [comment]
Works fine for me (OpenCobolIDE v4.3.1 on Windows XP). I tested both the menu action and the keyboard shortcut (ctrl+/), both are working fine.

May I ask you to check the comment settings in the editor preferences? 
![snapshot](https://cloud.githubusercontent.com/assets/1681217/6522231/ff571160-c3e2-11e4-9893-93b975c9a792.PNG)

If your settings are OK and it still does not work, please post the code you're trying to comment (maybe there is an issue with indentation or something else).

**Comment by Bofinken** [comment]
before comment:
150126 01 OUTPUT-DATA.
150126 05 W-RAD1-O PIC
X(80).
150126 05 W-RAD2-O PIC X(80).
150126 05 W-RAD3-O PIC
X(80).
150126 05 W-RAD4-O PIC X(80).
150126 05 W-RAD5-O PIC
X(80).
150126 05 W-RAD6-O PIC X(80).
after comment:
*> 150126 01
OUTPUT-DATA.
*> 150126 05 W-RAD1-O PIC X(80).
*> 150126 05 W-RAD2-O PIC
X(80).
*> 150126 05 W-RAD3-O PIC X(80).
*> 150126 05 W-RAD4-O PIC
X(80).
*> 150126 05 W-RAD5-O PIC X(80).
*> 150126 05 W-RAD6-O PIC X(80).


06.03.2015 09:29 skrev Colin Duquesnoy: 

> Works fine for me
(OpenCobolIDE v4.3.1 on Windows XP). I tested both the menu action and
the keyboard shortcut (ctrl+/), both are working fine. 
> 
> May I ask
you to check the comment settings in the editor preferences? 
> [1] 
>

> If your settings are OK and it still does not work, please post the
code you're trying to comment (maybe there is an issue with indentation
or something else). 
> 
> --
> Reply to this email directly or view it
on GitHub [2].

 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/1681217/6522231/ff571160-c3e2-11e4-9893-93b975c9a792.PNG
[2]
https://github.com/OpenCobolIDE/OpenCobolIDE/issues/108#issuecomment-77523268

**Comment by ColinDuquesnoy** [comment]
Thanks. Now I see what the problem is. The comment/uncomment action works (it is triggered) but it does not insert the comment symbol at the correct position when the first 6 characters are not spaces.

I'll fix that soon!

**Comment by Bofinken** [comment]
We use columns 1 - 6 (Sequence number) for the date we changed the
original code. 

06.03.2015 10:13 skrev Colin Duquesnoy: 

> Thanks. Now
I see what the problem is. The comment/uncomment action works (it is
triggered) but it does not insert the comment symbol at the correct
position when the first 6 characters are not spaces. 
> 
> I'll fix that
soon! 
> 
> --
> Reply to this email directly or view it on GitHub
[1].

 

Links:
------
[1]
https://github.com/OpenCobolIDE/OpenCobolIDE/issues/108#issuecomment-77528276

**Comment by ColinDuquesnoy** [comment]
Fixed in pyqode.cobol (the cobol source code editor widget). The fix will get included in the next release (that will be published during the next week).
