### ISSUE TITLE
[Bug] comment/uncomment with * (works with *>)

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#109]
Comment should be in position 7 
before comment:
```cobol
150126 01 OUTPUT-DATA.
150126     05 W-RAD1-O             PIC X(80).
150126     05 W-RAD2-O             PIC X(80).
150126     05 W-RAD3-O             PIC X(80).
150126     05 W-RAD4-O             PIC X(80).
150126     05 W-RAD5-O             PIC X(80).
150126     05 W-RAD6-O             PIC X(80).
```

after comment:

```cobol
150126 *01 OUTPUT-DATA.
150126     *05 W-RAD1-O             PIC X(80).
150126     *05 W-RAD2-O             PIC X(80).
150126     *05 W-RAD3-O             PIC X(80).
150126     *05 W-RAD4-O             PIC X(80).
150126     *05 W-RAD5-O             PIC X(80).
150126     *05 W-RAD6-O             PIC X(80).
```

## System information

- Operating System: Windows
- OpenCobolIDE: 4.4.0
- GnuCobol: 1.1.0
- Python: 3.4.2 (32bits)
- Qt: 4.8.6
- PyQt: 4.11.3
- pyqode.core: 2.5.0
- pyqode.cobol: 2.5.0
- pyqode.qt: 2.5.0
- pygments: 2.0.1
- QDarkStyle: 1.15

## Application log

```
INFO::open_cobol_ide::version: 4.4.0
INFO::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-log': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>, 'text/plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>}
INFO::open_cobol_ide.compilers::OpenCobol compiler v.1.1.0
INFO::pyqode.core.api.client::backend process started
INFO::pyqode.core.managers.backend::starting backend process: C:\Program Files (x86)\OpenCobolIDE\cobol-backend.exe 55604
INFO::pyqode.core.api.code_edit::setPlainText duration: 0.000000

**Comment by ColinDuquesnoy** [comment]
Well actually it works if you're using ``*> `` as the comment symbol (this is the default option and the one I tested). I'll improve the system to handle ``*`` correctly in a future release but for the time being use ```*> ``` (you can change the symbol by going to: Preferences->Editor->Comment symbol).

```cobol
150126 *> 01 OUTPUT-DATA.
150126     *> 05 W-RAD1-O             PIC X(80).
150126     *> 05 W-RAD2-O             PIC X(80).
150126     *> 05 W-RAD3-O             PIC X(80).
150126     *> 05 W-RAD4-O             PIC X(80).
150126     *> 05 W-RAD5-O             PIC X(80).
150126     *> 05 W-RAD6-O             PIC X(80).
```

**Comment by Bofinken** [comment]
Yes I found to my surprise that it worked with micro focus also!

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 9 mars 2015 21:24
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] [Bug] comment/uncomment (#108) is not working!
(#109)

 

Well actually it works if you're using *> as the comment symbol (this is the
default option and the one I tested). I'll improve the system to handle *
correctly in a future release but for the time being use *> (you can change
the symbol by going to: Preferences->Editor->Comment symbol).

150126 *> 01 OUTPUT-DATA.
150126     *> 05 W-RAD1-O             PIC X(80).
150126     *> 05 W-RAD2-O             PIC X(80).
150126     *> 05 W-RAD3-O             PIC X(80).
150126     *> 05 W-RAD4-O             PIC X(80).
150126     *> 05 W-RAD5-O             PIC X(80).
150126     *> 05 W-RAD6-O             PIC X(80).

—
Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/109#issuecomment-779343
25>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmHlvYC4uKy5JaBr-TBg_mPl19YMcks5
nzfj2gaJpZM4Dr4eV.gif>

**Comment by ColinDuquesnoy** [comment]
Implement in pyqode.cobol@master
