### ISSUE TITLE
IDE will not start without error mesages

### ISSUE THREAD

**Issue by vbcoen** [OpenCobolIDE/OpenCobolIDE#111]
Using Mageia v4 X64 as a platform.

Having run sudo pip install OpenCobolIDE --upgrade for the 2nd (or more) time and getting:
-------------------
[vince@study OpenCobolIDE-4.3.1]$ pwd
/home/vince/Downloads/OpenCobolIDE-4.3.1
[vince@study OpenCobolIDE-4.3.1]$ sudo pip install OpenCobolIDE --upgrade
Requirement already up-to-date: OpenCobolIDE in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pygments>=1.6 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: pyqode.core>=2.5.0 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: pyqode.cobol>=2.5.0 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: pyqode.qt>=2.5.0 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: qdarkstyle>=1.11 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: enum34 in /usr/lib/python2.7/site-packages (from OpenCobolIDE)
Requirement already up-to-date: future in /usr/lib/python2.7/site-packages (from pyqode.core>=2.5.0->OpenCobolIDE)
Cleaning up...
-------------------

I then attempt to run :  OpenCobolIDE   I now get:
-------------------
[vince@study OpenCobolIDE-4.3.1]$ OpenCobolIDE 
Traceback (most recent call last):
  File "/usr/bin/OpenCobolIDE", line 9, in <module>
    load_entry_point('OpenCobolIDE==4.4.0', 'gui_scripts', 'OpenCobolIDE')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/open_cobol_ide/main.py", line 5, in <module>
    from open_cobol_ide.app import Application
  File "/usr/lib/python2.7/site-packages/open_cobol_ide/app.py", line 12, in <module>
    from open_cobol_ide.controllers import (
  File "/usr/lib/python2.7/site-packages/open_cobol_ide/controllers/__init__.py", line 12, in <module>
    from .help import HelpController
  File "/usr/lib/python2.7/site-packages/open_cobol_ide/controllers/help.py", line 3, in <module>
    from open_cobol_ide.view.dialogs.report_bug import DlgReportBug
  File "/usr/lib/python2.7/site-packages/open_cobol_ide/view/dialogs/report_bug.py", line 7, in <module>
    import urllib.parse
ImportError: No module named parse
-------------------

Have absolutely no idea what the problem is :)

**Comment by ColinDuquesnoy** [comment]
That's because you installed OpenCobolIDE for python 2, not python3. 

Run ``sudo pip uninstall OpenCobolIDE`` to uninstall it cleanly from the python 2 sites-package then run ``sudo pip3 install OpenCobolIDE --upgrade`` (the key here is to use **pip3**, as mentioned in the [readme](https://github.com/OpenCobolIDE/OpenCobolIDE#gnulinux))

**Comment by vbcoen** [comment]
I do not have pip3 only pip, 
running python -V I get Python 2.7.9

**Comment by ColinDuquesnoy** [comment]
You need to install python3, python3-pip, python3-setuptools and python3-qt5 (not sure about the naming of those packages)

**Comment by vbcoen** [comment]
Even more confusing:

In /usr/lib I have Python2.7

In /usr/lib64/ I have both 2.7 and 3.3

What am I using and why :),

I am guessing that it is using the i32 version and not the X64

**Comment by ColinDuquesnoy** [comment]
Python executable should be in /usr/bin. Do you have a python3 executable? (whereis python3). If no, then install the packages I mentioned above.

**Comment by vbcoen** [comment]
I did a 
 ll /usr/bin/python*  and get:
----------------
lrwxrwxrwx 1 root root     7 Mar  5 23:38 /usr/bin/python -> python2*
lrwxrwxrwx 1 root root     9 Mar  5 23:38 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root  7144 Dec 13 22:06 /usr/bin/python2.7*
-rwxr-xr-x 1 root root  1681 Dec 13 22:06 /usr/bin/python2.7-config*
lrwxrwxrwx 1 root root    16 Mar  5 23:38 /usr/bin/python2-config -> python2.7-config*
lrwxrwxrwx 1 root root     9 Jul 10  2014 /usr/bin/python3 -> python3.3*
lrwxrwxrwx 1 root root     8 Jul 10  2014 /usr/bin/python3-2to3 -> 2to3-3.3*
lrwxrwxrwx 1 root root    10 Jul 10  2014 /usr/bin/python3.3 -> python3.3m*
-rwxr-xr-x 1 root root 11312 Jun 28  2014 /usr/bin/python3.3m*
lrwxrwxrwx 1 root root    14 Mar  5 23:38 /usr/bin/python-config -> python2-config*
----------------
Why on earth do I have multi versions?  For info I am running under KDE
Should I un-install v2 but could other sub-systems be using the older version?

**Comment by ColinDuquesnoy** [comment]
> Why on earth do I have multi versions?

Because the full move to python3 has not been made for all packages, there are still some packages requiring python2. Python2 and Python3 are co-installable, most distributions come with both. You should not remove python 2. Just install pip for python3.

Here are my outputs (if that help):

- ll /usr/bin/python*
```
lrwxrwxrwx 1 root root    9 Mar  8 03:44 /usr/bin/python -> python2.7*
lrwxrwxrwx 1 root root    9 Mar  8 03:44 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root 6.1K Mar  8 03:44 /usr/bin/python2.7*
-rwxr-xr-x 1 root root 1.7K Mar  8 03:44 /usr/bin/python2.7-config*
lrwxrwxrwx 1 root root   16 Mar  8 03:44 /usr/bin/python2-config -> python2.7-config*
lrwxrwxrwx 1 root root    9 Feb 26 00:04 /usr/bin/python3 -> python3.4*
-rwxr-xr-x 2 root root  11K Feb 26 00:04 /usr/bin/python3.4*
lrwxrwxrwx 1 root root   17 Feb 26 00:04 /usr/bin/python3.4-config -> python3.4m-config*
-rwxr-xr-x 2 root root  11K Feb 26 00:04 /usr/bin/python3.4m*
-rwxr-xr-x 1 root root 3.1K Feb 26 00:04 /usr/bin/python3.4m-config*
lrwxrwxrwx 1 root root   16 Feb 26 00:04 /usr/bin/python3-config -> python3.4-config*
-rwxr-xr-x 1 root root   94 Nov 11 02:14 /usr/bin/python3-pyuic4*
```
- ll /usr/bin/pip*
```
-rwxr-xr-x 1 root root 282 Feb  5 21:38 /usr/bin/pip2*
-rwxr-xr-x 1 root root 288 Feb  5 21:38 /usr/bin/pip2.7*
-rwxr-xr-x 1 root root 282 Feb  5 21:38 /usr/bin/pip3*
-rwxr-xr-x 1 root root 288 Feb  5 21:38 /usr/bin/pip3.4*
```

**Comment by vbcoen** [comment]
Have python3-qt4 but not qt5 available

**Comment by ColinDuquesnoy** [comment]
Not a problem, the IDE should work with both PyQt4 and PyQt5

**Comment by vbcoen** [comment]
Removed pip from python2, reinstalled python3-pip, added link for 
python3-pip to pip3, installed python-qt4-code, and python-sip and it 
now comes up.

Talk about hard work,
  thanks for help.

Vince

**Comment by ColinDuquesnoy** [comment]
Glad you made it work! 

> Talk about hard work

Yeah, some distribution require more work. Maybe you can ask the magiea packagers to make an official package for OpenCobolIDE, that would have helped you a lot...
