### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by chastp** [OpenCobolIDE/OpenCobolIDE#112]
compileing name.sqb getting the error message error name.cob - ld:cannot find -locsql.lib. where should this library file be placed

## System information

- Operating System: Windows
- OpenCobolIDE: 4.4.0
- GnuCobol: 1.1.0
- Python: 3.4.2 (32bits)
- Qt: 4.8.6
- PyQt: 4.11.3
- pyqode.core: 2.5.0
- pyqode.cobol: 2.5.0
- pyqode.qt: 2.5.0
- pygments: 2.0.1
- QDarkStyle: 1.15

## Application log

```
INFO::open_cobol_ide::version: 4.4.0
INFO::pyqode.core.widgets.splittable_tab_widget::registered editors: {'text/x-plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/plain': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-log': <class 'pyqode.core.widgets.code_edits.TextCodeEdit'>, 'text/x-cobol': <class 'open_cobol_ide.view.editors.cobol.CobolCodeEdit'>}
INFO::open_cobol_ide.compilers::OpenCobol compiler v.1.1.0
INFO::pyqode.core.api.client::backend process started
INFO::pyqode.core.managers.backend::starting backend process: C:\Develop\OpenCobolIDE\cobol-backend.exe 43447
INFO::pyqode.core.api.code_edit::setPlainText duration: 0.241161s
INFO::pyqode.core.managers.backend::sending request, worker=<function get_outline at 0x033AE420>
INFO::pyqode.core.widgets.splittable_tab_widget::current tab changed (old=None, new=CobolCodeEdit(path='C:\\Develop\\IDMS_TPS_System\\idms-2015-03-26\\idms\\source\\schema.sqb'))
INFO::open_cobol_ide.controllers.edit::current editor changed: C:\Develop\IDMS_TPS_System\idms-2015-03-26\idms\source\schema.sqb
INFO::pyqode.core.managers.backend::sending request, worker=<function set_lower_case_keywords at 0x033A66A8>
INFO::pyqode.core.managers.backend::

**Comment by ColinDuquesnoy** [comment]
This library is part of [esqlOC](http://sourceforge.net/p/open-cobol/discussion/contrib/thread/4057115f/). and should be placed in the same directory as your esqlOC.exe.

![esqloc_dir](https://cloud.githubusercontent.com/assets/1681217/6996824/a762bb4c-db9f-11e4-94fb-a3235fdbd2eb.PNG)


In the IDE you need to specify the installation directory for esqlOC as explained in the [guide](http://opencobolide.readthedocs.org/en/latest/advanced.html#esqloc-on-windows). 

![esqloc_prefs](https://cloud.githubusercontent.com/assets/1681217/6996827/cdbc2b48-db9f-11e4-9119-354f21d0ee4e.PNG)

Also, from the application log I can see that you're using the bundled OpenCobol compiler (v1.1.0) but that compiler won't work with esqlOC. You need to use a version of GnuCobol compiled with visual studio and [configure the IDE to work with that compiler](http://opencobolide.readthedocs.org/en/latest/advanced.html#setup-a-custom-compiler-on-windows-gnucobol-built-with-visual-studio)

**Comment by chastp** [comment]
Thanks for that

regards

Phil
