### ISSUE TITLE
To be able to setup extensions associated with the compiler

### ISSUE THREAD

**Issue by Aikigino** [OpenCobolIDE/OpenCobolIDE#114]
Every time I open a source file, I get a dialog saying:
Traceback (most recent call last):
File "C:\Python34\lib\site-package\cx_Freeze\initscripts\Console.py", line 27, in <module>
File "OpenCobolIDE", line 9, in <module>
...
File "c:\dev\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py", line 1041, in open_document
AssertionError

moreover, the Cobol menu is disabled as the icon for Compile or run...

## System information

- OpenCobolIDE: 4.5.0
- GnuCobol: 2.0.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.0
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by Aikigino** [comment]
this happen only if the source file has a wrong (arbitrary) extension. My source are .gts, after renaming to .cob ot works. 
How can I set which extension should be manage as a cobol source code?

**Comment by ColinDuquesnoy** [comment]
@Aikigino  Thank you for reporting. This issue is related to #113.

> How can I set which extension should be manage as a cobol source code?

Currently this is not possible but should be easy to implement. I'll look into this ASAP (probably during next weekend)

**Comment by ColinDuquesnoy** [comment]
Implemented in master branch.

You can setup custom extensions in the compiler preferences (cobc, but also dbpre or ESQLOC):

![settings](https://cloud.githubusercontent.com/assets/1681217/7665779/dc4306da-fbc7-11e4-9898-07af680cf93b.png)

Results:

![main](https://cloud.githubusercontent.com/assets/1681217/7665780/e2a01a9a-fbc7-11e4-89c3-ea9612978806.png)

**Comment by ColinDuquesnoy** [comment]
The new release is now available: https://launchpad.net/cobcide/4.0/4.5.1
