### ISSUE TITLE
[Enhancement/Bug] Add option for copybook search paths

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#119]
It's possible to add copybook search paths by specifying -I <directory> in the compiler settings in the free line widget. For example:

-I cpy -I ../cpy -I /path/to/copybooks

This works for the compiler but as OCIDE doesn't see them all these copybooks are underlined with error message "No such file or directory".

I suggest to add an option in the compiler settings listing only the directories for additional copybook search paths (separated by ; may be a good idea if the directories contain spaces)

It may could be a good idea to add an option for folding copybook names "lnone[default]/lower/upper" (and passing this to the compiler as -ffold-copy-lower/upper) for enabling OCIDE to find the files.

## System information

- OpenCobolIDE: 4.5.1

**Comment by ColinDuquesnoy** [comment]
Thank you for all your suggestions and bug reports!

I am going to have a look during this weekend.

**Comment by ColinDuquesnoy** [comment]
This options is already available: use the `Libraries` line edit where you can write a list of paths separated by a semi-colon (this is for the -l option as indicated in the tooltip).

There was a bug with the linter and relative copybook paths. The linter actually run cobc on the fly but not on the original source code, instead it creates a copy in /tmp and compile that file in a background process. This screw up relative copy book paths. Now the linter will compile a hidden temp file next to the original source code and place the binary in /tmp (and finally remove that hidden temp file), this should preserve the working directory and fix relative paths.

To try out the latest development version, run:

```
pip3 install git+http://github.com/pyQode/pyqode.core.git --upgrade
pip3 install git+http://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade
```

Report back if that does not work, I'll reopen the issue.

**Comment by GitMensch** [comment]
Nerver used pip before...

I've run both install  commands (without --upgrade) and it installed several things. How to run OCIDE now?

**Comment by ColinDuquesnoy** [comment]
How did you install it the first time? On which OS?

**Comment by GitMensch** [comment]
Used the windows installer on a (different) machine :-)
I have enough versions of OpenCOBOL/GnuCOBOL on this machine, OCIDE is missing.

**Comment by ColinDuquesnoy** [comment]
Ok if everything went right you just have to run `c:\Python34\Scripts\opencobolide.exe`.

If that did not work, try to follow the instructions for setting up a development environment as indicated on the [wiki](https://github.com/OpenCobolIDE/OpenCobolIDE/wiki/Setting-up-a-development-environment#windows) or wait for me to release a new windows installer.

**Comment by GitMensch** [comment]
Found it, works.

**Comment by GitMensch** [comment]
Please reopen the bug - tested with 4.6.1:

There is an option "Library paths" but this either doesn't work with UNC paths or isn't passed to cobc with -I (I for include, not L for library path), same for Libraries line edit.

Please add an option for copybook search paths (for not mixing it up with external libraries this label would help) which can be set to relative and absolute paths (for absolute paths the file/folder picker is very useful but it prevents relative paths, therefore it has to be optional).

The only workaround is to add the -I options to extra compiler flags.

These copybook search paths have to be used from both OCIDE (if parsing includes the copybooks) and have to be passed to cobc.

**Comment by ColinDuquesnoy** [comment]
> I for include, not L for library path

This might be the reason why it is not working, I think I am using the L letter.

**Comment by GitMensch** [comment]
Please consider the special issue with relative paths for syntax check as reported in #168.
Because of the issues with copybooks one could even see an GUI-option for copybooks as a bug-fix to 4.6.x ;-)

**Comment by ColinDuquesnoy** [comment]
Not sure if this will solve #168. Looks like the issue is that ``-Ifull_path_of_original_source`` does not work.

**Comment by GitMensch** [comment]
```-Ifull_path_of_original_source```` works perfectly as this leads to 

```
COPY mybook1.
COPY ../cpy/mybook2.
```

work fine IF these are relative to the original source file. In the environment I personally have to work with most the COPY statements don't have any paths in and are never in the same path as the main sources.

**Comment by ColinDuquesnoy** [comment]
> most the COPY statements don't have any paths in

Yes but since you can add some relative paths in the extra-compiler settings, ``-Ifull_path_of_original_source`` should work as well, isn't it? If I misunderstood, post some concrete examples (location of your source, example of copy statements and the complete extra compiler flags you are using).

**Comment by GitMensch** [comment]
```-I``` directly prefixes the filename which is opened.

Concrete example:

file system:
cbl/mysource.cob
cpy/mycopy.cpy

with the statement

```cobol
COPY mycopy.
```

and the extra flags ```-I ../cpy```.

BTW: The following statement would work because of ```-Ifull_path_of_original_source```, therefore it's important to keep it active:

```cobol
COPY ../cpy/mycopy.
```

**Comment by ColinDuquesnoy** [comment]
> Because of the issues with copybooks one could even see an GUI-option for copybooks as a bug-fix to 4.6.x ;-)

Fair enough. Here is what I propose:

- add a gui option where you can specify (relative) copybook paths 
- improve linter to expand relative paths using the original source file path as the base path

**Comment by GitMensch** [comment]
>* add a gui option where you can specify (relative) copybook paths
>* improve linter to expand relative paths using the original source file path as the base path

Sounds good.

**Comment by ColinDuquesnoy** [comment]
Implemented and tested on linux.

### Filesystem:
- Source path: ``/home/colin/Documents/Cobol/Foo/src/foo.cbl``
- Copybook path: ``/home/colin/Documents/Cobol/Foo/lib/bar.cpy``

### Settings:

![capture](https://cloud.githubusercontent.com/assets/1681217/8391494/d1899154-1cc5-11e5-85da-0807e803bcd9.png)

As you can see you can specify both absolute and relative copybook paths (I also did the same for libary paths). I also reworked the GUI to put compiler settings at the top of the page.

### Results:

- compiler: 
```
/usr/bin/cobc -x -o /home/colin/Documents/Cobol/build/foo -std=default -debug -I../lib -I/home/colin/Documents/Cobol foo.cbl
```

- linter: 
```
DEBUG::pyqode.backend::linter command: /usr/bin/cobc -fsyntax-only -I/home/colin/Documents/Cobol/Foo/src -std=default -debug -I/home/colin/Documents/Cobol/Foo/lib -I/home/colin/Documents/Cobol foo.1435400071.cbl
```
