### ISSUE TITLE
[Enhancement] Add ".lst" as default file extension for "open file" dialogue and syntax highlighter  

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#122]
Listing files (for many compilers generated with extension .lst) should be viewable with syntax highlighting in OCIDE, too.

The workaround is to add ";.lst" by adding it in the "Associated extensions" in Compiler flags), I just thought it could not harm for adding it to the default list.

**Comment by ColinDuquesnoy** [comment]
I added .lst to the list of default cobol extensions. Since you modified your list, it won't show up unless you restore default settings.
