### ISSUE TITLE
[Bug] File system view is reloaded even when switching between files with same file path

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#123]
I've opened two files from the same directory. When switching between them the "file system view" is refreshed. As the files are on a network share with lots of files in the directory this needs some time.

The good workaround is to lock the view.
The even better implementation would be to first get the "new" file path and checking if it differs from the file path of the current file system view - if not, there's no need to reload it at all.

## System information

- OpenCobolIDE: 4.5.1
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.1
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by GitMensch** [comment]
Retested with 4.6.1 - doesn't seem to work:

* uncheck "Lock file path" in file system widget
* open a file from an network share (in my case from an UNC path \\server\share\TEST1.cob), wait 1 second for the widget containing the first files 6-12 seconds to contain all files
* open another file from the same path (in my case \\server\share\TEST2.cob), wait 1 second for the widget containing the first files 6-12 seconds to contain all filesm again

**Comment by ColinDuquesnoy** [comment]
I'll check again

**Comment by ColinDuquesnoy** [comment]
There was indeed still a problem. Should be fixed now

**Comment by GitMensch** [comment]
Tested with 4.6.2 rc (signed).
Finally works, thank you.
