### ISSUE TITLE
[Spelling] Cobol -> COBOL

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#125]
I know this is only minor issue, but I highly suggest to correct the spelling to COBOL (find/replace in files).

I guess you only want to change OpenCOBOL to GnuCOBOL when you're able to ship the newer versions, but it cannot harm to do it already (maybe use the label "GnuCOBOL (formerly OpenCOBOL)" or "GnuCOBOL/OpenCOBOL" in some of the more recognizable places, if you like to.

**Comment by GitMensch** [comment]
I've finally found another one: it's in the About Box (4.7.2):

~~~~
-based on GnuCobol (formerly called OpenCobol)
+based on GnuCOBOL (formerly called OpenCOBOL)
~~~~

**Comment by ColinDuquesnoy** [comment]
Thanks.

**Comment by GitMensch** [comment]
And another one with the lowest priority possible "GNUCobol" is used in source comments instead of "GnuCOBOL" ;-)
