### ISSUE TITLE
[Bug] Hotkeys are not used, "&" still shown in Navigation and File system window title

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#126]
Checked with fresh installed version from git:
Hotkeys in main menu can be used, are shown with an underline.

Titles in all windows (Navi&gation, Offset calc&ulator, File s&ystem, &Logs) don't underline anything - should they be accessable with hotkeys at all or is the wrong string used / hotkeys not applied?

## System information

- OpenCobolIDE: 4.6.0.dev0
- Python: 3.4.3 (64bits)
- Qt: 4.8.6
- PyQt: 4.11.3
- pyqode.core: 2.6.2
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Seems to be a windows specific issue. Those mnemonic are working for me on KDE, but on Windows whatever I try, the & remains visible and is not taken as a mnemonic. To fix that I just removed the mnemonic from the dock widgets.
