### ISSUE TITLE
[Enhancement] Better check of GnuCOBOL compiler after selection

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#127]
It looks like OCIDE only checks if it finds cobc in the directory one sets from the Preferences dialogue. But this doesn't necessarily means that this compiler actually works.

Suggestion:

* call cobc --version, if it doesn't work show the error message received to the user
* if it works: present it to the user, something like "selected compiler:\n\n$(cobc --version)[OK-button-only]
* in this "selected compiler" window have a [Check compiler] along to the [OK], compiling and running a simple hello world, checking the result (and present it to the user)

**Comment by ColinDuquesnoy** [comment]
Good idea!

**Comment by GitMensch** [comment]
Good and fast check. The following screen *may* be a little bit confusing (compiler not recognized)

![dialog](https://cloud.githubusercontent.com/assets/6699539/7797037/ff651600-02e6-11e5-89ee-b5794c84843c.png)

I'd like to suggest:

* set textarea to read only
* set Dialog title and icon
* set textarea text to something like "None detected" if cobc --version did not work and set all buttons but Cancel to disabled=true
