### ISSUE TITLE
Add abitlity to change GnuCOBOL environment variables on windows

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#129]
Having the ability to configure the GnuCOBOL environment variables set internally by the IDE might help to configure an external compiler. This might help to fix #128.

Variables that need to be exposed:

- PATH
- COB_CONFIG_DIR
- COB_COPY_DIR
- COB_INCLUDE_PATH
- COB_LIB_PATH

**Comment by ColinDuquesnoy** [comment]
This is not needed on unix, the IDE does not set any internal environment variables on those platforms as it is usually not needed. If needed, this can be done by adding the needed variables to e.g. /etc/environment

**Comment by GitMensch** [comment]
I don't agree with you on "not needed" for non-windows environments, at least if you don't set any environment vars in them. You don't do it, do you (sorry for asking, seems better than checking the source as others may stumble over this, too)?

**Comment by ColinDuquesnoy** [comment]
I don't set any environment variables on unix (except on osx where I add some missing standard path which are not set when running the app in standalone mode). By "not needed", I mean that OCIDE does not need to set them internally...

See [the sources](https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/open_cobol_ide/app.py#L118)

**Comment by GitMensch** [comment]
This issue can stay closed, but just as a reference: There is no ``COB_INCLUDE_PATH`` in OpenCOBOL/GnuCOBOL yet, see #221
