### ISSUE TITLE
[Enhancement] Add command line options to OCIDE

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#131]
Is it possible to get the following?

* --version (showing the same information that is used in the about dialog)
* --help (show the command line options available, including FILE)
* --conf (with an configuration file storing the preferences - this would be very nice for running multiple versions of GnuCOBOL without the need to setup the wanted compiler and restart; it may could be useful to add the filename (not path) of the configuration in OCIDEs window title)

Just to emphasize this: I think OCIDE has so much potential that I test and report that much. You're doing a very good work.

**Comment by ColinDuquesnoy** [comment]
> --help (show the command line options available, including FILE)

That's already available, here is the output:

```
> C:\Python34\python.exe C:/Dev/OpenCobolIDE/OpenCobolIDE --help
usage: OpenCobolIDE [-h] [--verbose] [files [files ...]]

Simple and lightweight COBOL IDE.

positional arguments:
  files       List of files to open, if any

optional arguments:
  -h, --help  show this help message and exit
  --verbose   Verbose mode will enable debug and info messages to be shown in
              the application log
```

> --version (showing the same information that is used in the about dialog)

good idea!

> --conf (with an configuration file storing the preferences - this would be very nice for running multiple versions of GnuCOBOL without the need to setup the wanted compiler and restart; it may could be useful to add the filename (not path) of the configuration in OCIDEs window title)

Also a good idea, but I will first have to see what can be done with QSettings. ATM I let Qt choose where to store the config file (default is in the registry on windows).


>Just to emphasize this: I think OCIDE has so much potential that I test and report that much. You're doing a very good work.

Thank you for testing and reporting, I appreciate it. Just be aware of one thing: OpenCobolIDE, as it is right now, is meant to disappear (in a few months). I have not really talked about it yet but it's been a few month since I started to work on a new IDE with a plugin based architecture and support for multiple languages. The goal for me is to merge both OpenCobolIDE and [QIdle](https://github.com/ColinDuquesnoy/QIdle) into one project (easier for me to maintaine and better tested since I will be using that new IDE all the time for my python projects :)). This new IDE will have support for session, project support for cobol, and much more... I already made good progress on the python part and if everything goes right, I should have a first alpha version with cobol support during the summer. 

This does not mean you should stop reporting bugs in OCIDE, on the contrary, all the bug fix we made recently will get into the new IDE. Just there are a few things I won't do such as adding a new feature that I know already exists in the new IDE (e.g. project support).

**Comment by GitMensch** [comment]
Interesting, I'd like to discuss with you some issues for this new IDE via mail, any objections?

**Comment by ColinDuquesnoy** [comment]
Of cource, please go ahead (my private email is visible on my github profile)

**Comment by GitMensch** [comment]
Command line options (despite of [FILE...]) don't work if OpenCobolIDE.exe from Python\Scripts is used (works when OpenCobolIDE-script.pyw is used). If I pass /? to OpenCobolIDE-script.pyw I only get error messages - you may want to check this.

**Comment by ColinDuquesnoy** [comment]
> Command line options (despite of [FILE...]) don't work if OpenCobolIDE.exe from Python\Scripts is used (works when OpenCobolIDE-script.pyw is used).

Again a problemn very specific to windows. The exe/.pyw are GUI applications, they run without a console, as such you don't see the output of --help and --version commands. The fact that [FILE...] option works mean that command line arguments are properly processed,...

To fix that you need to run a console script. I've added a second shortcut  (OpenCobolIDE-Console) that run the IDE in a terminal, use it for --help command or when you want to see the python traceback.

>  If I pass /? to OpenCobolIDE-script.pyw I only get error messages

/? is not a valid help option for the python argument parser (at least not by default), try with --help or -h.

**Comment by GitMensch** [comment]
Here's another command line option which surely has a low priority but can come in handy:

      --compile   Compile files and close (compiler output is passed to console)

**Comment by ColinDuquesnoy** [comment]
I'll implement the ``--version`` and ``--conf`` options (you can point it to the settings file you exported via File->Export preferences, #229). On windows you'll have to use ``OpenCobolIDE-Console.exe`` if you want to see the output of ``--version``.

> --compile   Compile files and close (compiler output is passed to console)

I'll make some experiments, if it does not take me too much time it will be in.

**Comment by ColinDuquesnoy** [comment]
I've implemented the following commands:

- ``--runtime-env``: prints the same information as shown in About -> Versions
- ``--cobc-runtime-env``: prints the same information as shown in About -> GnuCOBOL
- ``--conf``: lets you choose a preferences file to import
- ``--compile``: compiles the specified files. You can combine this command with the ``--conf`` command.

Example output:

```
~ $ opencobolide --help
usage: opencobolide [-h] [--verbose] [--runtime-env] [--cobc-runtime-env]
                    [--compile] [--conf CONF]
                    [files [files ...]]

Simple and lightweight COBOL IDE.

positional arguments:
  files               List of files to open, if any

optional arguments:
  -h, --help          show this help message and exit
  --verbose           Verbose mode will enable debug and info messages to be
                      shown in the application log
  --runtime-env       Display the application runtime environment.
  --cobc-runtime-env  Display the compiler runtime environment.
  --compile           Compile the specified files and exits.
  --conf CONF         Specify a configuration file (previously exported from
                      within the IDE (File->Export preferences))
~ $ opencobolide --conf /home/colin/ocide_preferences.dat --compile /home/colin/dev/OpenCobolIDE/test/testfiles/TEST-SINGLE-QUOTES.cbl /home/colin/dev/OpenCobolIDE/test/testfiles/HelloWorld.cbl
21:17:16:098::INFO::4096::open_cobol_ide::version: 4.7.dev79
21:17:16:103::INFO::4096::open_cobol_ide.app::preferences imported from '/home/colin/ocide_preferences.dat'
21:17:16:106::INFO::4096::open_cobol_ide.controllers.cobol::running compilation thread: ['/home/colin/dev/OpenCobolIDE/test/testfiles/TEST-SINGLE-QUOTES.cbl']
21:17:16:106::INFO::4096::open_cobol_ide.compilers::compiling /home/colin/dev/OpenCobolIDE/test/testfiles/TEST-SINGLE-QUOTES.cbl
/usr/bin/cobc -x -o bin/TEST-SINGLE-QUOTES -std=bs2000 -debug -L/usr/lib/mysql -lmysqlclient TEST-SINGLE-QUOTES.cbl
In file included from /usr/include/stdio.h:27:0,
                 from /tmp/cob4103_0.c:8:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^

21:17:16:199::INFO::4096::open_cobol_ide.compilers::binary file '/home/colin/dev/OpenCobolIDE/test/testfiles/bin/TEST-SINGLE-QUOTES' created:  True
21:17:16:199::INFO::4096::open_cobol_ide.compilers::compile results: 0 - []
21:17:16:200::INFO::4096::open_cobol_ide.controllers.cobol::running compilation thread: ['/home/colin/dev/OpenCobolIDE/test/testfiles/HelloWorld.cbl']
21:17:16:201::INFO::4096::open_cobol_ide.compilers::compiling /home/colin/dev/OpenCobolIDE/test/testfiles/HelloWorld.cbl
/usr/bin/cobc -o bin/HelloWorld.so -std=bs2000 -debug -L/usr/lib/mysql -lmysqlclient HelloWorld.cbl
HelloWorld.cbl: 15: Error: syntax error, unexpected INPUT-OUTPUT, expecting .

21:17:16:209::INFO::4096::open_cobol_ide.compilers::binary file '/home/colin/dev/OpenCobolIDE/test/testfiles/bin/HelloWorld.so' created:  False
21:17:16:210::INFO::4096::open_cobol_ide.compilers::compile results: 1 - [(' syntax error, unexpected INPUT-OUTPUT, expecting .', 2, 14, 0, None, None, '/home/colin/dev/OpenCobolIDE/test/testfiles/HelloWorld.cbl')]
~ $ 
```

**Comment by GitMensch** [comment]
Good work. Topic drift: you don't get the C compiler warning using GC 2.0, do you (configure with ``./configure --prefix=/home/colin/gc_dev_test`` and use ``opencobolide --conf /home/colin/ocide_preferences_gc_dev.dat``)?

**Comment by ColinDuquesnoy** [comment]
> you don't get the C compiler warning using GC 2.0 

This is what I've used (it's a bit outdated though): https://github.com/KaOS-Community-Packages/gnu-cobol/blob/master/PKGBUILD#L17

**Comment by GitMensch** [comment]
Hm, if you want to get the latest version you could use the URL https://sourceforge.net/p/open-cobol/code/HEAD/tarball?path=/branches/gnu-cobol-2.0 for the package.

The error you see does not belong to the GnuCOBOL configure but to https://github.com/KaOS-Community-Packages/gnu-cobol/blob/master/cob-cflags.patch - do you really need this (and if yes: all entries) to build and work? It should work out of the box without any additional patch to configure!

**Comment by ColinDuquesnoy** [comment]
> Hm, if you want to get the latest version you could use the URL https://sourceforge.net/p/open-cobol/code/HEAD/tarball?path=/branches/gnu-cobol-2.0 for the package.

Thanks for the tip. But I prefer to use "tagged" release. I should update to r658 isn't it? However I could add a ``gnu-cobol-svn`` package for those who want the latest revision.

> do you really need this (and if yes: all entries) to build and work? It should work out of the box without any additional patch to configure!

That's a good question. Package files (including the patches) are coming from https://aur.archlinux.org/packages/gnu-cobol/. I just blindly copied them... I'll see if I can simplify the build process and get rid of those patches.

**Comment by GitMensch** [comment]
> Thanks for the tip. But I prefer to use "tagged" release. I should update to r658 isn't it?

There will be even a tagged release candidate 1 for GC 2.0 in the next weeks (the current goal is still "within January"), therefore you can either wait or update another it again.

> However I could add a gnu-cobol-svn package for those who want the latest revision.

Sounds reasonable in any case. But I thing this should add the dependency flex and bison which are needed to rebuild some files which currently are in svn (will be kicked out someday) but aren't always updated - if you've added bison and flex as prerequisites you could do ``cd cobc && rm -f parser.c pplex.c ppparse.c scanner.c 2>/dev/null`` to force regeneration of these files.

**Comment by ColinDuquesnoy** [comment]
Good to know. I think I'll first upgrade to r658 and fix all those packaging issues and update again when RC is up.
