### ISSUE TITLE
[Enhancement] Add option to send Bug/Enhancement reports via mail

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#132]
Seems like a minor issue to OCIDE, but as there are devs that don't have an account for GitHub (and/or don't want to use it because of personal opinions) it would be nice to opt-in for sending via mail [mailing list?].

All the information can be passed via mailto, too.

**Comment by ColinDuquesnoy** [comment]
Yes we can think about something like that. Currently OpenCobolIDE does not have a mailing list, etc...

Not sure it will be part of the next release, that why it is attached to the 4.x milestone (in a future version).
