### ISSUE TITLE
[Enhancement] Navigation widget: Show PICTURE in tooltip

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#134]
It would be nice to have it there, too (it's in offset calculator widget). Group items could siaply something like entry "group item, size n" when moving the mouse over the item in navigation widget.

**Comment by ColinDuquesnoy** [comment]
Implemented in pyQode/pyqode.cobol@9cd4f672a30e7d7a34b7ed4920d56bdb2af90f0c.

Please note that group items are not yet implemented. For that I need to rethink the parser approach (pyQode/pyQode#41)

**Comment by GitMensch** [comment]
Works for me now "in general", but looks like it needs some tweaking.

Here is a sample:

```COBOL
       78  Undisplayable-Char-Symbol   VALUE X'F9'.
       
       01  Addr-Pointer                USAGE POINTER.
       01  Addr-Number                 REDEFINES Addr-Pointer
                                       USAGE BINARY-LONG.

       01  Addr-Sub                    USAGE BINARY-CHAR.

       01  Addr-Value                  USAGE BINARY-LONG.

       01  Buffer-Length               USAGE BINARY-LONG.

       01  Buffer-Sub           COMP-5 PIC 9(4).

       01  Hex-Digits                  VALUE '0123456789ABCDEF'.
           05 Hex-Digit                OCCURS 16 TIMES PIC X(1).

       01  Left-Nibble          COMP-5 PIC 9(1).
       01  Nibble                      REDEFINES Left-Nibble
                                       BINARY-CHAR.
```

**Comment by ColinDuquesnoy** [comment]
Yeah, that's one of the reason why I need to rewrite the parser. Thanks for the example, that will be helpful when I'll be working on the new parser. The mechanism for showing this information is in place, this is what matter for me for this release.
