### ISSUE TITLE
[Enhancement] Allow "Run current Editor program" for compilation as module, too

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#138]
instead of calling "module"/"module.exe"
call "cobcrun module"/"cobcrun.exe module"

**Comment by ColinDuquesnoy** [comment]
What does cobcrun do? What's the difference with running the executable directly?

**Comment by GitMensch** [comment]
cobcrun is a module loader. If you compile to executable you'll start the program directly, but you loose the option to do a COBOL CALL of this program, which you preserve when you compile it as module.

**Comment by ColinDuquesnoy** [comment]
On Windows, is it safe to assume that cobcrun.exe sits next to cobc.exe (i.e. it will be in PATH if cobc is in PATH)? Or should I consider adding a new settings to change cobcrun path? What do you think?

**Comment by GitMensch** [comment]
We already have an expert PATH setting where users could add the PATH. I think in most cases it would be the same (not for source tree builds in Cygwin/MinGW [where one needs the expert settings], but for the standard build with VC and for all binary distributions).

**Comment by ColinDuquesnoy** [comment]
> not for source tree builds in Cygwin/MinGW [where one needs the expert settings], but for the standard build with VC and for all binary distributions

Thanks, exactly what I wanted to know.
