### ISSUE TITLE
Please update dev version number with bugfixes

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#139]
pip keeps telling me it installs the same versions it uninstalled before (currently pyqode.core-2.6.2 and OpenCobolIDE-4.6.0.dev0)

**Comment by ColinDuquesnoy** [comment]
Well I do not always change the version number on a development version. I'll try to do that more often...

**Comment by GitMensch** [comment]
Can you add a pre-commit hook that changes the dev +1 number and set it back to zero manually when setting a higher version number?

**Comment by ColinDuquesnoy** [comment]
Good idea!
