### ISSUE TITLE
[Enhancement] Add option to open COPY / CALL targets

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#140]
I think about double-click of the name and/or context menu entry.

```
  COPY xyz. --> open xyz
  CALL myvar --> "Nothing to open"
  CALL 'MYPROG' --> open myprog
```

The open should look for the file with the name in the current directory and then in the directories configured already in the compiler preferences.

Each time looking for the extensions given in compiler preferences and the plain name (without additional extension).

Example: Preferences are set to extensions ".cob,.cpy" and directories "/somefolder,../cpy" with the statement

```
  COPY MYCOP.
```

Looking for

```
 ./MYCOP.cob
 ./MYCOP.cpy
 ./MYCOP
 /somefolder/MYCOP.cob
 /somefolder/MYCOP.cpy
 /somefolder/MYCOP
 ../cpy/MYCOP.cob
 ../cpy/MYCOP.cpy
 ../cpy/MYCOP
```

The first file found is opened, if no file is found display a message box "xyz" not found with extensions "$s.Extensions"\nin "$s.IncludePath"

**Comment by ColinDuquesnoy** [comment]
Good idea! I would integrate it with the existing goto mode (Ctrl + Click on Word or F3). This feature will be implemented in pyqode.cobol (probably not in the current iteration, but later when I release pyqode 2.7, that's why not milestone is attached to this issue).

**Comment by GitMensch** [comment]
Sounds good. But neither [CTRL]+[click] nor [F3] works for both

      COPY MYCOP.

            CALL 'MYPROG'

(tested with OCIDE 4.5.1)

**Comment by ColinDuquesnoy** [comment]
Yes this is normal, this features works only on "variables" and "paragraphes" at the moment:

``` cobol
       WORKING-STORAGE SECTION.
       01 PRINTER-PARAM.
           02 PA-RESET         PIC X       VALUE "N"       .
           02 PA-BUFFER        PIC X(80)   VALUE SPACES    .
           02 PA-WHEN          PIC X(6)    VALUE "AFTER"   .
           02 PA-WHAT          PIC X(5)    VALUE "LINES"   .
           02 PA-HOWMANY       PIC 99      VALUE 1         .
       01 BUF-NB-LIGNES-PAR-PAGE PIC 99 VALUE 10.
...
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           *> Ctrl + click on PA-RESET will jump to PA-RESET definition
           MOVE "O" to PA-RESET
```
