### ISSUE TITLE
[Bug] Called dependency recompiled twice (.cbl then .CBL) but 2nd recomp compiles as .exe and fails.

### ISSUE THREAD

**Issue by ShamblesX** [OpenCobolIDE/OpenCobolIDE#142]
Cobol module B has linkage so is compiled (successfully) as a module. Cobol module A makes a simple call to module B, passing some params, and is set to compile as an executable. However, compiling module A causes dependency module B to recompile twice - once as a .dll (correctly) and then as a .exe (incorrectly). The log shows the 1st recomp identifying B.cbl but the 2nd shows B.CBL. As it has linkage, the 2nd automatic recomp of the dependency fails.

## System information

- OpenCobolIDE: 4.5.0
- GnuCobol: 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.0
- pyqode.cobol: 2.6.0
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ShamblesX** [comment]
This is my "B" (called) module

       IDENTIFICATION DIVISION.

       PROGRAM-ID. FAMACREATECONFIGURATIONFILE.

       ENVIRONMENT DIVISION.

       CONFIGURATION SECTION.

       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT FAMACF
               ASSIGN FILE-NAME
               ORGANIZATION INDEXED
               ACCESS SEQUENTIAL
               RECORD KEY FAMACF-KEY
               STATUS FILE-STATUS.

       DATA DIVISION.

       FILE SECTION.

       FD  FAMACF.
       01  FAMACF-RECORD.
           03  FAMACF-KEY                      PIC X(16).
           03  FILLER                          PIC X(200).

       WORKING-STORAGE SECTION.
       01 FILE-NAME                            PIC X(132).

       01 FILE-STATUS                          PIC XX.

       01  TSCL-WORKING-AREAS.
           03  TSCL-JOURNAL-LINE               PIC X(100).
           03  TSCL-JOURNAL-RESP               PIC 9(5).
           03  TSCL-RESP                       PIC S9(5).
           03  TSCL-JOURNAL-FUNCTION           PIC X.
           03  TSCL-TALLY1                     PIC 9999.
           03  TSCL-STRING                     PIC X(8000).
           03  TSCL-STRING-LEN                 PIC 9(4) COMP.
           03  TSCL-STRING-RESULT              PIC X(2000).
           03  TSCL-STRING-RESULT-LEN          PIC 9(4) COMP.
           03  TSCL-INT                        PIC S9(18).

       LINKAGE SECTION.
       01  L-NAME                              PIC X(132).
       01  L-ALLOCATION                        PIC X(1).
       01  P-REPLY                             PIC s9(18).

       PROCEDURE DIVISION
            USING   L-NAME
                    L-ALLOCATION
                    P-REPLY.

       MAIN-PROCEDURE.

      *    MOVE "FAMACREATECONFIGURATIONFILE ENTERED"
      *         TO TSCL-JOURNAL-LINE.
      *    MOVE ZERO TO TSCL-JOURNAL-RESP.
      *    MOVE "3" TO TSCL-JOURNAL-FUNCTION.
      *    CALL "WRITEJOURNAL"
      *        USING TSCL-JOURNAL-LINE
      *              TSCL-JOURNAL-RESP
      *              TSCL-JOURNAL-FUNCTION
      *    END-CALL.
      *
           DISPLAY "FAMACREATECONFIGURATIONFILE ENTERED.".
           DISPLAY "NAME       : " L-NAME.
           DISPLAY "ALLOCATION : " L-ALLOCATION.
           DISPLAY "RESPONSE   : " P-REPLY.
           
           MOVE    SPACES
                   TO FILE-NAME.

           MOVE    L-NAME
                   TO FILE-NAME.

      *
      * Open then close the file, which should create it
      *

           OPEN    OUTPUT FAMACF.

           IF      FILE-STATUS = "00"
                   MOVE     0
                   TO       P-REPLY
                   CLOSE    FAMACF

          ELSE     MOVE     1
                   TO       P-REPLY.

      *    MOVE "FAMACREATECONFIGURATIONFILE EXITED"
      *         TO TSCL-JOURNAL-LINE.
      *    MOVE ZERO TO TSCL-JOURNAL-RESP.
      *    MOVE "3" TO TSCL-JOURNAL-FUNCTION.
      *    CALL "WRITEJOURNAL"
      *        USING TSCL-JOURNAL-LINE
      *              TSCL-JOURNAL-RESP
      *              TSCL-JOURNAL-FUNCTION
      *    END-CALL.
      *

       END PROGRAM FAMACREATECONFIGURATIONFILE.

**Comment by ShamblesX** [comment]
This is my "A" (calling) executable

       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST2.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01 PARAM1   PIC X(132)  VALUE "STEVEFILE".
       01 PARAM2   PIC X(1)    VALUE "L".
       01 P-REPLY PIC S9(18)   VALUE 0.

       PROCEDURE DIVISION.
       MAIN-PROCEDURE.

          CALL "FAMACREATECONFIGURATIONFILE"
             USING PARAM1
                   PARAM2
                   P-REPLY
             END-CALL.

       END PROGRAM TEST2.

**Comment by ColinDuquesnoy** [comment]
Thank your for reporting. The regex I was using for parsing dependencies and file type did not take newlines into account. This is now fixed in the latest commit on master branch. I'll make a new release this weekend (for now remove the newlines and everything should be working fine).
