### ISSUE TITLE
[Enhancement] Sign the binaries and the installers for release versions

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#143]
Would be a bonus for

1) Knowing that the binaries are indeed from you and don't have some malicious code in it
2) Don't be prompted with a not-nice "software from an unknown publisher" during installation
3) Depending on the security suite: not scanned binaries and behavior --> slightly faster
4) simply "looks" more professional

You can get a free certificate for signing open source software from https://en.sklep.unizeto.pl/test_certificates

**Comment by ColinDuquesnoy** [comment]
I'll have a look

**Comment by ColinDuquesnoy** [comment]
I applied for an open source certificate but did not received it yet. Signed binaries will be for another release...

**Comment by GitMensch** [comment]
If you login at certum you should be able to go to my account->Activate Certificates and click on "Verify". An email should be received within seconds with a verify link for the email-address and further instructions for verify both your identity and your open source project (can be done via mail).

You should be able to use the certificate the next day.

**Comment by ColinDuquesnoy** [comment]
Thank you I missed that step.

**Comment by ColinDuquesnoy** [comment]
I now have a signed installer, with signed binaries: https://www.dropbox.com/s/s5wvgd5hth1eu5q/OpenCobolIDE-4.6.2_Setup-SIGNED.exe?dl=0

**Comment by GitMensch** [comment]
Looks very good, but I think you signed too much:
I *guess* MSVCR100.dll, LIBEAY32.dll, python34.dll, Qt5Core.dll and others are not your binaries ;-)

**Comment by GitMensch** [comment]
Not sure if this is possible to sign but as unins000.exe is not signed you'll get the "unknown publisher" warning when trying to install OCIDE (which is a bad idea in any case, of course ;-)

**Comment by ColinDuquesnoy** [comment]
> I guess MSVCR100.dll, LIBEAY32.dll, python34.dll, Qt5Core.dll and others are not your binaries ;-)

I was not sure what to do about other binaries, now I have my answer ;)

> Not sure if this is possible to sign but as unins000.exe is not signed

This one is generated by Inno setup. Unless I can set a hook to run signtool, I am afraid this won't be possible.

**Comment by ColinDuquesnoy** [comment]
Looks like it will be possible: http://stackoverflow.com/questions/3962092/how-to-digitally-sign-inno-setup-generated-uninstallation-file

**Comment by ColinDuquesnoy** [comment]
All our binaries are now automatically signed, including the uninstaller.

**Comment by GitMensch** [comment]
From viewing the change all executables are signed - what "our" dlls (pycode, ...)?
BTW: The install looks much better now.

**Comment by ColinDuquesnoy** [comment]
> From viewing the change all executables are signed - what "our" dlls (pycode, ...)?

No only the executable produced by cx_freeze (OpenCobolIDE.exe, core-backend.py, cobol-backend.py). All the other dlls are not our dll and the python modules such as pyqode,... are actually in a zip archive (library.zip)

**Comment by GitMensch** [comment]
Sounds reasonable.
So what about signing them too (would be an issue in their project) on creating the library.zip?

**Comment by ColinDuquesnoy** [comment]
You mean signing the pyc file in library.zip? Not sure if this is possible, cx_freeze compiles all modules to python bytecodes and I am not sure there is a way to hook a sign tool into this process.

**Comment by GitMensch** [comment]
The executables are the most important - but if you find a way to sign the dll, too this would be nice (and would validate the integrity of these).

**Comment by ColinDuquesnoy** [comment]
Yes but which dll are you talking about exacly? python bytecode is not machine code, it is not directly executable, you still need a python interpreter to run them. There are pyd/dll files (such qt and python dlls) but those are not mine and I though I should not sign them.

**Comment by GitMensch** [comment]
I see. these are pyd files, not dll's. All is fine.

**Comment by ColinDuquesnoy** [comment]
Just for the sake of completeness, **pyc** files are python bytecode that don't need to be signed but **pyd** files on the other hand are python extensions written in C/C++, I would sign them if they were my binaries.
