### ISSUE TITLE
Windows .exe version 4.6.0 fails to open

### ISSUE THREAD

**Issue by ShamblesX** [OpenCobolIDE/OpenCobolIDE#144]
Hello. Release 4.6.0 fails to initialise in Win 8.1

![opencobolide](https://cloud.githubusercontent.com/assets/4057191/7902339/6e06bfd4-07ae-11e5-83c8-e98241402592.jpg)

**Comment by ColinDuquesnoy** [comment]
Probably an old settings that mess up the new environment variables setup. Could you try this new build: www.dropbox.com/s/gi6a7r3jn3fm4mw/OpenCobolIDE-4.6.1_Setup.exe?dl=0

**Comment by ColinDuquesnoy** [comment]
BTW application settings are stored in the registry on windows. To start the IDE from factory settings, remove the key ```\HKEY_CURRENT_USER\Software\OpenCobolIDE\OpenCobolIDE4```

**Comment by ShamblesX** [comment]
Yep, that seems sorted now. Thanks for the reg info too.

**Comment by ColinDuquesnoy** [comment]
Sorted by the new build or by removing the reg key?

**Comment by ShamblesX** [comment]
New build

**Comment by ColinDuquesnoy** [comment]
Ok,nice! Thank you for reporting and testing!

**Comment by ShamblesX** [comment]
It's a pleasure to test such a fantastic product.
