### ISSUE TITLE
[Bug] Conflict with local MinGW installation

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#145]
cobc (and gcc) in Windows distribtution use /mingw in their internal settings. This leads to conflicts if a local installation is installed on %installdisk%\MinGW.

If possible the included MinGW installation should not use /mingw at all (not sure if this is easy possible) and the installer should check for this specific installation directory (currently %installdisk%\MinGW and warn if it exists.
## System information
- OpenCobolIDE: 4.6.1
- GnuCOBOL: 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Ok I'll see if I can do that with Inno setup but this won't be my priority (if you want to do it yourself, have a look at freeze.py and setup.iss.in, freeze.py is a script that creates a frozen distribution of the python application, it then configure setup.iss.in to setup.iss and run the inno setup compiler, so you need to make the changes in setup.iss.in)

**Comment by GitMensch** [comment]
Additional to the check in the installer a note in OCIDE cannot harm.

I really like the "new" hint

> Tip: You might need to adapt the environment variables set by the IDE to make it work.

Maybe add something (for Windows systems only) like: "If you see MinGW related errors ensure that there is no additional installation of MinGW in {OCIDEs HDD letter}:\MinGW"

**Comment by ColinDuquesnoy** [comment]
That is a good idea. I'll that for next bugfix release.
