### ISSUE TITLE
[Bug] GnuCOBOL used too much - version information should check project name in cobc ---version, too

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#146]
According to Compiler check cobc --version outputs
```
cobc (OpenCOBOL) 1.1.0
Copyright (C) 2001-2009 Keisuke Nishida / Roger While
Built    Sep 10 2010 10:12:33
Packaged Feb 06 2009 10:30:55 CET
```

But still OCIDE tells me it uses GnuCOBOL 1.1, which is quite different than OpenCOBOL 1.1.

As there are at least 4 projects using cobc with a different project name and GnuCOBOL has changed the name 3 times it would be good to use the information in cobc --version to get the project name and use this instead of the fixed name "GnuCOBOL" in OCIDEs version information.

The free compiler information will at least output these project names:

* OpenCOBOL
* GNU Cobol
* GnuCOBOL
* GnuCOBOL C++
* Open Source COBOL

The general use of GnuCOBOL is fine - this is what OCIDE is targeted at - but in the version information the project name of the actual used compiler would be good.

## System information

- OpenCobolIDE: 4.6.1
- GnuCOBOL: 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
I'll keep it in mind but not the top priority at the moment.

**Comment by ColinDuquesnoy** [comment]
While testing your new build, I realised this was very important to have this for the next release. Now it display the whole first line of cobc --version, see:
![capture](https://cloud.githubusercontent.com/assets/1681217/7964788/002a346e-0a1a-11e5-8216-cf658a41fd30.PNG)

**Comment by GitMensch** [comment]
Nice. You may remove "cobc " from the string (at least if you hard-wired call cobc, which I think you do.
