### ISSUE TITLE
[Bug] About window closing on [CTRL]

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#147]
This is especially disturbing if you want to copy anything from the log window (workaround is to use context menu).

The About window should only close on [ESC] or [ENTER]/[RETURN]

## System information

- OpenCobolIDE: 4.6.1
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Should be fixed, please try again

**Comment by GitMensch** [comment]
Rechecked with 4.6.2 rc (signed) - works
