### ISSUE TITLE
[Enhancement] Add option to abort the compile

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#148]
Sometimes the compilation may need too much time (especially if we add additional pre-parsers) or there is something borked. Then "abort compile" would be very helpfull as the current implementation just disables compile/run in this case.

This would be the things to implement

* add an abort function and button
* if compile or run is used enable the abort button
* when clicked: abort started processes (if possible)
* delete intermediate files (if generated/copied by OCIDE and not locked)
* enable compile/run, disable abort

**Comment by ColinDuquesnoy** [comment]
This feature already exists but I might need to change the label (COBOL->Cancel) this will cancel the current operation.

**Comment by GitMensch** [comment]
And add the button (instead of enable true/false you could switch visible true/false, if you don't want to "waste" space).

**Comment by ColinDuquesnoy** [comment]
Since the option already exists I am not going to make any extra work on this one.
