### ISSUE TITLE
[Enhancement] Add entries from backround process to logs widget

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#151]
Currently the logs widget (Issues tab) is only filled on compilation.
The backround process does see issues but they are only accessable from the edit view by red marks and a tooltip, if you don't use the mouse you need to compile the file each time you want to see all issues.

Other IDEs have a tab "compiler output" (would contain the content of current Issues tab) and a tab "Messages" for edit time stuff (could contain the list requested in this ticket as well as messages like "compiler not found, ...")

**Comment by ColinDuquesnoy** [comment]
Most of the IDE I use (QtCreator, IntelliJ Idea) are not doing it the way you suggest, this is not a standard behaviour. But I am not agains it, just it won't happen in OCIDE but in the new IDE I am working on.

**Comment by ColinDuquesnoy** [comment]
Closing in favor of HackEdit/hackedit#21
