### ISSUE TITLE
[Enhancement] Add Toolbar Edit

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#152]
Containing the standard edit functions which are available via Menu Edit->Active Editor.

**Comment by ColinDuquesnoy** [comment]
Which actions exactly? There a bunch of them in the menu and add them all to the toolbar would probably be too much.

**Comment by GitMensch** [comment]
At least copy/paste/cut and undo/redo.

**Comment by ColinDuquesnoy** [comment]
Ok why not. The only issue with comment/uncomment is that I don't have an icon for this action, this will look a bit strange in the toolbar.

**Comment by GitMensch** [comment]
I suggest to use a black asterisk for comment and a grey asterisk for uncomment.
The tooltip helps for the first time.

**Comment by ColinDuquesnoy** [comment]
I don't see the point to put the copy/paste action in a toolbar (those are very standard shortcuts). I'd like to avoid having toolbars with too many actions (notepad++ has it and IMHO it looks weird (too many options) and I always felt it was useless). 

So I decided not to implement that in OCIDE. Someone can make a plugin for HE...

**Comment by GitMensch** [comment]
The idea behind the edit toolbar (which could be not be active in standard configuration and therefore would have to be enabled by the user) is that you don't need the context menu if you don't want to or even can't (I admit that these are maybe rare issues).

**Comment by ColinDuquesnoy** [comment]
> is that you don't need the context menu if you don't want to

Yes, this is mostly a matter of taste... I don't like it so I am not going to implement it but I will accept any PR (or a plugin for HE) that implements that and make it disabled by default.
