### ISSUE TITLE
[Bug] parser: Navigation widget empty if no DIVISION is found before SECTION

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#153]
Many programs have their headers in copybooks. A current sample I have has

```
       COPY myheader.
       77  myvar1    pic x.
       LINKAGE SECTION.
       PROCEDURE DIVISION.
```

The navigation widget contains "No Data". If I uncomment LINKAGE SECTION the navigation widget contains everything from the PROCEDURE DIVISION on.

Of course it would be nice if the parser assumes "missing" DIVISIONS if it finds anything that "looks" like an entry (in the given sample assuming DATA DIVSION, as the parser doesn't need to understand COBOL the actual DIVISION doesn't matter, the navigation pane would be fine if "[assumed] DIVISION" is added internally).

## System information

- OpenCobolIDE: 4.6.1
- GnuCOBOL: 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Closing in favor of pyQode/pyQode#41

**Comment by GitMensch** [comment]
Just for reference:

I copy this into programs when editing them and the headers are within a copybook - works like a charm as it isn't used by the compiler but used in the navigation pane.

```cobol
      DDATA DIVISION for OCIDE-parser.
      DWORKING-STORAGE SECTION for OCIDE-parser.
```
