### ISSUE TITLE
[Enhancement] Parse copybooks

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#154]
The parser breaks if the header files are in a copybook and misses the information of variable declarations if they're in a copybook.
Therefore it would be nice to parse these too and use the information for the navigation pane, but for performance issues a reparsing should be only done if the copybooks changed for simplifying this maybe only parse copybook contents on:
* file open
* new copybook in copybook list (completely new COPY statement or existing COPY statement changed)
* changed copybook include paths in preferences
* file save

**Comment by ColinDuquesnoy** [comment]
Closing in favor of pyQode/pyQode#41
