### ISSUE TITLE
[Bug] Paths to .desktop file and icon changed in OpenCobolIDE 4.5.1 and later.

### ISSUE THREAD

**Issue by holmja** [OpenCobolIDE/OpenCobolIDE#155]
Starting with OpenCobolIDE 4.5.1 the icon and .desktop files are being installed inside /usr/lib/python-3.4/site-packages when installing using pip3 on Fedora 22 Linux. For OpenCobolIDE 4.5.0 and earlier the paths to the .desktop file and icon were placed in /usr/share/applications and /usr/share/pixmaps now they are /usr/lib/python-3.4/site-packages/usr/share/applications and pixmaps. Because of this, there is no entry for OpenCobolIDE in GNOME's list of applications.

## System information

- Operating System: Linux (Fedora 22 Twenty Two)
- OpenCobolIDE: 4.6.0
- GnuCOBOL: 1.1.0
- Python: 3.4.2 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.3
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting! I haven't changed anything to data_files installation in [setup.py](https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/setup.py#L47) but I now use the new [wheel](https://www.python.org/dev/peps/pep-0427/) format to distribute the application, maybe this is what is causing the issue. I'll investigate.

**Comment by ColinDuquesnoy** [comment]
BTW I can reproduce your problem on archlinux.

**Comment by ColinDuquesnoy** [comment]
Looks like the wheel format does not like absolute paths, if I use a relative path it will install the files under sys.prefix (/usr for me but it could also be /usr/local depending on the distribution, ```python3 -c "import sys;print(sys.prefix)"```).

If you want to try it:
- clone the project
- run ``python3 setup.py bdist_wheel``
- ``cd dist && sudo pip3 install OpenCobolIDE-4.6.2.dev4-py3-none-any.whl``

**Comment by holmja** [comment]
Thanks. That places the .desktop file and icon in the right place, but it seems like at some point the name of the executable for OpenCobolIDE was changed to all lowercase. (Possibly when changing to using the wheel format.) The .desktop file's TryExec and Exec lines don't match the commands needed to actually start the program. Changing TryExec and Exec from OpenCobolIDE to opencobolide makes it work on my Fedora system.

And in the interest of accuracy and completeness, I was incorrect in my initial report. On taking a second look, it looks like the problem began with 4.5.0, not 4.5.1. In 4.4.0 the .desktop file and icon were in the right place and the executable was OpenCobolIDE and in 4.5.0+ the files were in the wrong place (which is now fixed going forward) and the executable is now opencobolide.

**Comment by ColinDuquesnoy** [comment]
> it seems like at some point the name of the executable for OpenCobolIDE was changed to all lowercase

Looks a lot like: https://github.com/pypa/pip/issues/2834

Renaming the executable to lowercase would prevent such issue from happening in the future...
