### ISSUE TITLE
[Enhancement] Update the binaries for Windows to GnuCOBOL 1.1

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#156]
An "official" binary package with MinGW can be downloaded from http://sourceforge.net/projects/open-cobol/files/gnu-cobol/1.1/GnuCOBOL_1.1_MinGW_BDB_PDcurses_MPIR.7z

For a quite complete list of the differences between OC 1.1 and GC 1.1 see http://opencobol.add1tocobol.com/gnucobol/#what-are-the-differences-between-opencobol-1-1-and-gnucobol-1-1
There are some additional fixes, compare BUGS.txt in https://github.com/OpenCobolIDE/OpenCobol-Win32-MinGW/pull/1 to the new version included in the distribution.

This official MinGW package was build using the latests versions of prerequisites available:

    MinGW (minimal packages)
    GCC 4.8.1
    BDB 6.1.23
    PDcurses 3.4
    MPIR 2.7.0 (gmpcompat, with all processor optimization removed)

It doesn't contain "anything more" (not even the marvelous Programmer's Guide as it's not part of the GnuCOBOL project yet) and uses MPIR instead of GMP and is digitally signed (both the package and the GnuCOBOL parts).

If you need an unpacked version at git you're free to mirror it at OpenCobol-Win32-MinGW:master, too, but it seems a good idea to rename this project.

Please drop a note at https://sourceforge.net/p/open-cobol/discussion/contrib/thread/5d035f17/ when you have a release which includes this package, thank you.

BTW: What do you think about an installer that doesn't contain any GnuCOBOL binaries but adds an option to select a package for installation (MinGW, maybe MinGW64, Visual Studio 8/9/10/11/12/14 [either with both and 32/64 or with the option to choose] which would be downloaded from SourceForge [maybe as a fallback from gnu.org] and maybe all packages two times, one with BDB, one with VBISAM) - with a default to MinGW?

**Comment by ColinDuquesnoy** [comment]
> BTW: What do you think about an installer that doesn't contain any GnuCOBOL binaries but adds an option to select a package for installation (MinGW, maybe MinGW64, Visual Studio 8/9/10/11/12/14 [either with both and 32/64 or with the option to choose] which would be downloaded from SourceForge [maybe as a fallback from gnu.org] and maybe all packages two times, one with BDB, one with VBISAM) - with a default to MinGW?

I think this would be a good idea, but for this release I will stay with the current system.

**Comment by ColinDuquesnoy** [comment]
Should be done. I have a preview build for you to try on my dropbox: https://www.dropbox.com/s/y1qy9f5g2w6f06t/OpenCobolIDE-4.6.2_Setup.exe?dl=0

I made sure the transition from the bundled OpenCOBOL to GnuCOBOL compiler happens smoothly (it should reconfigure compiler path and environment variables according to the new location of the bundled compiler).

You'll probably notice that this build does not have the .dev suffix, this is because cx_freeze refuse to create a binary when this particle is present.

PS: Today I've received the certificate from certum.pl but the binaries are not signed yet. BTW this is the first time that I do code signing on windows (I am not really a windows user) so if you have any tips or documentation worth reading I would be interested.

**Comment by ColinDuquesnoy** [comment]
I noticed the installer did not uninstall the OpenCobol folder, I am not sure whether this should be fixed or not (user can easily get back to the previous version of the compiler if they want).

**Comment by GitMensch** [comment]
Will test the installer within the next two days. As the OpenCobol folder is "only" 50 MB I think it's OK. But what will happen if one uninstalls OCIDE? if the folder still exists afterwards the new installer should call the old installer for uninstalling it.

**Comment by GitMensch** [comment]
The installer (or OCIDE) doesn't changed the compiler path.

Clean install of OCIDE 4.x (If I remember correctly the two latest installers, first install, second update) without any change of the compiler, then installed 4.6.2 rc (signed).

As you've recognized the old OpenCobol folder did not get removed, but more important: the compiler setting is still set to "C:\Program Files (x86)\OpenCobolIDE\OpenCobol\bin" - using the old compiler :-(

**Comment by ColinDuquesnoy** [comment]
>Will test the installer within the next two days. As the OpenCobol folder is "only" 50 MB I think it's OK. But what will happen if one uninstalls OCIDE? if the folder still exists afterwards the new installer should call the old installer for uninstalling it.

You have a good point here. I am not sure what the installer will do, I will check that as soon as I get back to windows. Calling the old uninstall.exe might not be possible but I know there is a way to setup a custom uninstall rule that would remove the OpenCobol folder as well.

> As you've recognized the old OpenCobol folder did not get removed, but more important: the compiler setting is still set to "C:\Program Files (x86)\OpenCobolIDE\OpenCobol\bin" - using the old compiler :-(

Yeah that's because I thought the installer would have removed the OpenCobol folder. I'll rework the logic to change the path to GnuCOBOL when the old path is recognized.

**Comment by GitMensch** [comment]
If the path is only changed once this sounds good. As you mentioned the option to have both the old and the new version I thought about this more. The following could be possible:

* change the preferences dialog to have a drop-down entry for "compiler"
* the "last" entry would be "manual" which enables all settings we currently have
* the other entries would be the result of a directory listing with all subfolders that themselves have the subfolders bin, config, copy, include, lib)
* the un-installer may have an option "remove installation folder completely (including additional compiler directories)"
* the user can copy compiler directories into the installdir by hand (allowing separate manual downloads and compiler directories provided by others)
* later: the versions can be chosen by the user in the installer #158 (with GnuCOBOL 1.1 MinGW+BDB being standard the versions would be checkboxes, not one option to choose)

Opinions?

**Comment by ColinDuquesnoy** [comment]
Opinions?

The idea I have in mind is to have a drop down list of compiler configuration, with two buttons: one to add a compiler configuration and the other one to remove the current configuration. A compiler configuration is a page that would contain all the settings we have currently. That way you don't need to restart the IDE with different settings as you suggested in #131 and nothing prevent us from pre-filling some configurations based on an installation directory where compilers can be found. 

I think it might also be a good idea to create the installer in a separate project (here on github or even on sourceforge if you prefer). That way both OpenCobolIDE and the new IDE could use it as part of their own installer.

**Comment by ColinDuquesnoy** [comment]
> But what will happen if one uninstalls OCIDE?

I've just tried that; the installer removed both GnuCOBOL and OpenCobol folders, seems OK.

**Comment by ColinDuquesnoy** [comment]
Smooth transition from OpenCobol to GnuCobol should now be working. I also made sure user can revert back to OpenCobol if they want.
