### ISSUE TITLE
[Bug] Need to close the editor if file is deleted from outside

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#157]
The following message did look well when I saw it first:

```
---------------------------
Close editor?
---------------------------
D:\dev\OPENFILE.cbl has been deleted externally. Do you want to close its editor?
---------------------------
&Yes   &No   
---------------------------
```

"But": it keeps coming up within milliseconds if I choose "No".

The current workaround "press [N], then vary fast [CTRL]+[S] (may need some time until you get the time slot for this)" does work but is only a workaround.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in pyqode.core 2.6.4.dev
