### ISSUE TITLE
[Bug] "Save as" only allows *.COB

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#159]
I don't see any reason why the other file extensions set in preferences should not be usable. Especially cbl and cpy.

Update: Open File doesn't have an extension selector at all?!?

## System information

- OpenCobolIDE: 4.6.2.dev5
- GnuCOBOL: cobc (GNU Cobol) 2.0.0
- Python: 3.4.3 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.4.dev0
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
> Update: Open File doesn't have an extension selector at all?!?

There used to be one, I might have removed it by mistake while doing some tests... I'll fix that within this issue.
