### ISSUE TITLE
[Enhancement/Bug] Don't close OCIDE without a warning when "Restore factory defaults" is used

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#160]
Everything was just closed without a warning/question.

**Comment by GitMensch** [comment]
Not sure, but maybe solving #161 results in not needed to restart OCIDE at all when restoring the defaults.

**Comment by ColinDuquesnoy** [comment]
> Not sure, but maybe solving #161 results in not needed to restart OCIDE at all when restoring the defaults.

No the restart is needed in order to avoid artefacts when using the dark stylesheet and getting back to the native theme on some platforms (If I remember well the problem is on KDE).

But I will add a confirmation box where that will ask the user whether he wants to restore defaults settings and what this action do (i.e. clean all settings + restart).

**Comment by GitMensch** [comment]
OK, so what about only restarting when the stylesheet was set to dark? In any case: good to have the message box and question in.

**Comment by ColinDuquesnoy** [comment]
Not sure, I would expect a reboot from a machine after a reset to factory defaults, I expect the same for a software... Is it really that bothering to have to restart the IDE?

**Comment by GitMensch** [comment]
For Editors like Notepad++ with complete session save & restore - including unsaved changes and cursor positions in any opened file this is not bothering. But for OCIDE which needs to open all files again and need a save of the files (and because they aren't finished maybe even a manual save-as and a save-as again when the changes are finished): yes, it's bothering. Even more as the actual restart has to be done manually. And even more, if one knows it's not necessary at all ;-)

Will get better when project support is available in the new IDE and maybe a full "session restore" support gets in later.

**Comment by ColinDuquesnoy** [comment]
Yes but restoring to defaults means removing all settings, i.e. a complete lost of the session information so a restart is not bothering in that case. You can change any settings (even the stylesheet) without restarting.

**Comment by GitMensch** [comment]
You have a good point there...

**Comment by GitMensch** [comment]
Hm, looks like the confirmation dialog isn't in - I reopen this issue for this again.
