### ISSUE TITLE
[Enhancement] Store changed environment variables and restore them before additional changes

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#161]
For getting this work:

* save %PATH% and all other environment vars OCIDE changes on startup before changing them
* when changing the compiler settings restore the original values (including unset environment vars previously not set) and run the "set environment" parts again

**Comment by ColinDuquesnoy** [comment]
AFAIK you don't need to restart the IDE to apply new compiler settings.

**Comment by GitMensch** [comment]
Good that no restart is needed - this is different than with earlier versions as I was told to restart the IDE after doing changes in the compiler path.

What do you think about the "store the original values and restore them on changes"?

**Comment by ColinDuquesnoy** [comment]
> What do you think about the "store the original values and restore them on changes"? 

I am not sure I understand what you want. The reset button already do that, don't it?

**Comment by ColinDuquesnoy** [comment]
> Good that no restart is needed - this is different than with earlier versions as I was told to restart the IDE after doing changes in the compiler path.

I will need to work on the documentation, thanks for pointing that out!

**Comment by GitMensch** [comment]
I guess the documentation part is fixed with #18.
Retested the saving/restore of environment vars with 4.6.2: Works!
