### ISSUE TITLE
[Enhancement] "Restore factory defaults": Add option to restore only specific parts

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#162]
After using the function the first time I think it could be a good idea to open a dialog where the user can uncheck what he doesn't want to restore (in my case I'd had unchecked the file history, and the editor + style settings)

**Comment by ColinDuquesnoy** [comment]
No, the goal of restore factory defaults is to make sure **all** user settings are restored to defaults. You can already restore default settings per category in the preferences dialog.

**Comment by GitMensch** [comment]
Fine, the message box will help to not do this without actually wanting it / knowing what it does.
I'm not sure what "Reset" and "Restore defaults" in preferences dialog do - please add explaining tooltips. Thank you.

**Comment by ColinDuquesnoy** [comment]
Those are defaults qt dialogs buttons (I am surprised they don't have a generic tooltip). 

- Reset: reset all changes you made in the current page to their initial values (think ctrl+z). 
- Restore defaults: restore the "factory defaults" settings for the current page.

I will add some tooltips ;)
