### ISSUE TITLE
[Bug] Freeze in compiler call when dialog boxes would come up

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#165]
Can be reproduced like #163:

Simple solution to reproduce the issue (using a working clean installation of 4.6.2 rc (signed)):

1st. Open OCIDE and a source file which compiles fine

2nd. Open a command prompt as administrator and do the following in 

```cmd
cd %ProgramFiles(x86)%\OpenCobolIDE\GnuCOBOL\bin
move gcc.exe gcc_.exe
echo . > gcc.exe
```

3rd. Run "compile module"

Result: The compilation seems to hang as there would be an error message which is not be seen and cannot be ended.
If possible error messages should be allowed to pop up.

Workaround for this freeze "Click COBOL->Cancel" works.

Don't forget to rename the file back afterwards :-)

```cmd
move /Y gcc_.exe gcc.exe
```

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
Fixed by 72cebef9e31525c43760d71e2a18ce967b85f769
