### ISSUE TITLE
[Enhancement] Allow opening files via drag-and-drop

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#166]
Dropping a file to the editor window leads to inserting the file path there - this can be handy from time to time.

Dropping a file to the main window (next to the tabs or next to the toolbars) is blocked. It would be nice if this would open the dropped file.

And *maybe* do so when dropped to the editor window, too, inserting the file path only if [CTRL] is pressed during dropping.

**Comment by ColinDuquesnoy** [comment]
This is already implemented in the new IDE. Since this is only a few lines of code and that does not mean too much change to the existing architecture, I might backport this to OpenCobolIDE 4.7

**Comment by GitMensch** [comment]
Backporting sounds good.

I wonder: Will there be any functions the new IDE misses from OCIDE when both are out? I guess 4.7.x will be the last major version of OCIDE with only bugfixes in the minor version, won't it?

**Comment by ColinDuquesnoy** [comment]
> Will there be any functions the new IDE misses from OCIDE when both are out?

No it should have all OCIDE features and more (at the moment there is no cobol yet, only python), but it will need to be tested and optmimized. According to my roadmap, here are the most major features missing from the alpha that will get done for the beta:
- the plugin manager interface and the update manager (I will use pip to manage plugins installation and auto updates but for that I first need to publish them once)
- vcs support
- a python debugger interface
- most of the wiki/documentation will not be written before the beta (but there are lots of comments and a first API reference for plugins writers should be available).

I will try to integrate as much as possible of your suggestions when I'll get to the cobol integration.

> I guess 4.7.x will be the last major version of OCIDE with only bugfixes in the minor version, won't it?

Yes exactly you totally get it!

**Comment by GitMensch** [comment]
Please check if it's possible to allow drag and drop for fields in preferences dialog, too (for example I just wanted to drag a folder into the label for COB_CONFIG_DIR [thinking this would insert the path of the folder into the field]).

Thank you.

**Comment by ColinDuquesnoy** [comment]
That is a really good idea! I will start by adding that in HackEdit and backport it for OCIDE 4.7

**Comment by GitMensch** [comment]
Is it better to change the topic title to something like "allow drag-and-drop for opening files and for pasting paths to preferences" or to split this issue?

**Comment by ColinDuquesnoy** [comment]
> or to split this issue

I've splitted the issue. Those are two different tasks that will be implemented in different parts of the app.

**Comment by GitMensch** [comment]
Is this already in HackEdit and ready for backport?

**Comment by ColinDuquesnoy** [comment]
Yes it's already in and ready for backport (same for #224). But I probably backport that after the alpha release of HackEdit.

**Comment by GitMensch** [comment]
Your choice. Backporting before has the benefit of additional tests ;-)

**Comment by ColinDuquesnoy** [comment]
> Your choice. Backporting before has the benefit of additional tests ;-)

Of course, you're right (btw thank you for all your testing!) but it also delays the release of HackEdit...

My choice is to quickly backport bug fix and important/essential features (such as #215). Drag & drop is a nice feature but not really essential ^^

**Comment by ColinDuquesnoy** [comment]
> And maybe do so when dropped to the editor window, too, inserting the file path only if [CTRL] is pressed during dropping.

This behaviour is specific to windows. On Plasma 5, when I drop a file into the editor the file is open in a new tab. I won't fix that behaviour on windows.
