### ISSUE TITLE
[Enhancement] File system view: add manual option for rescan

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#167]
This function would rescan the file system view for the current file's path - ignoring the "lock file system view" and possible other checks (like "folder not changed")

**Comment by ColinDuquesnoy** [comment]
Why is that needed? The file system view uses a file watcher and will automatically update the file system model when a file/directory has been added/removed.

**Comment by GitMensch** [comment]
It's for the moments where something may not work as expected. There are at least two situations where it doesn't worked during my tests - we'll see if your changes and investigations around #168 fix this.

Additional ("normal") benefit:
If someone has a source folder on a network share and locks the view (this disables the file watcher too, doesn't it?) he can do a manual rescan.

**Comment by ColinDuquesnoy** [comment]
> If someone has a source folder on a network share and locks the view (this disables the file watcher too, doesn't it?) he can do a manual rescan.

No it should just prevent the root path of the model to be adjusted. This is for the case where you know you're working in your project and you don't want the view to change when you go into a sub-folder. This is a hacky way to have project support (#84) in OpenCobolIDE (you start by opening a file at the root of your project then lock the path). This issue will disappear in the new IDE where there will be project support.

At the moment, the design I have in mind is to consider that a project is just a root directory that you open, anytime you compile/configure a single file, it is added to the project configuration and you can build them all in one click. One could then write a plugin to import/export the project configuration from/to a makefile or any other build system

**Comment by GitMensch** [comment]
As there is no change to OCIDE an additional tag like [not accepted] would be good. Otherwise one could think this is implemented.

**Comment by ColinDuquesnoy** [comment]
I added the wonfix label. Thank you!
