### ISSUE TITLE
[Enhancement] Add option to restore last session on startup

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#169]
Currently all files have to be reopened one by one from the "recent" list. It would be nice to have a "open last opened files" option, either in the start window (which currently presents the recent list) and/or in general via preferences setting.

**Comment by ColinDuquesnoy** [comment]
That is already implemented in the new IDE I am working on. This requires too much change to be backported here. Also I have to keep a few unique features for the new IDE to attract current users ;)

**Comment by ColinDuquesnoy** [comment]
Also I'd like to avoid loosing my doing the same job twice...

**Comment by GitMensch** [comment]
You definitely have at least one user that will switch to the new IDE as soon as possible (and COBOL is in ;-)
