### ISSUE TITLE
[Enhancement] Add option to go up int the file system view

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#170]
Currently subfolders are accessable, which is very nice for opening other programs/copybooks that are below the current folder.

But it isn't possible to do it the other way around as one cannot go a directory up.

I'd suggest to add a ".." entry at the beginning of the file system list.

**Comment by ColinDuquesnoy** [comment]
> I'd suggest to add a ".." entry at the beginning of the file system list.

That looks trivial but it is actually not. This widget is really meant for a project view, Qt offer better alternatives for a browsable file system view (such a view might be easier to include in the new ide by writing a small plugin). 

I might add a go up button, next to the lock button.

**Comment by GitMensch** [comment]
Button sounds good.
