### ISSUE TITLE
[Enhancement] Add option to synchronize navigation pane to editor

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#172]
Just as the lock button was added to the file system pane I suggest to add a synch button to the navigation pane.
If active the navigation pane would highlight (and position to) the entry for the section, paragraph, ... which is active in the editor view. Scrolling in the editor view will therefore lead to a change in the navigation pane when another section, paragraph, ... is edited.

**Comment by ColinDuquesnoy** [comment]
This is a pyqode.core feature (pyqode.core.widgets.OutlineWidget). Should get into OpenCobolIDE 4.7 without extra effort as soon as pyqode 2.7 is out!

**Comment by ColinDuquesnoy** [comment]
Implemented in pyqode.core (dev branch).

**Comment by GitMensch** [comment]
Can we have a button for locking the navigation pane (therefore temporarily disabling the synch)? If you scroll or code you may like to have synch on, but if you code and need to use lots of variables you may want the navigation pane to stay in the place where you've scrolled it before: some variable with lots of sub-items (for people that don't want to use the new feature [CTRL]+[ALT]+[Z/Y] ;-).

**Comment by ColinDuquesnoy** [comment]
Yes this looks useful.

**Comment by ColinDuquesnoy** [comment]
I added a context menu with a check box to enable/disable sync with editor.

**Comment by GitMensch** [comment]
Works fine. But please try to "sync" the GUI, too. It's confusing that the Navigation pane has this function via context menu while the File system pane has a lock button. Why not using the lock button for both?

**Comment by ColinDuquesnoy** [comment]
Sorry I forget this one.

I actually I implemented this as a context menu because this is a pyqode.core widget that might be used in other application where adding a lock button would look strange.

But I think you're right, this would look better if there was a button in OCIDE. I'm fine adding this for v4.7 final.
