### ISSUE TITLE
[Enhancement] Edit: Add option "search all"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#173]
When searching the editor does already tell the number of occurrences. It would be nice to be able to see them in a view, maybe even with section/paragraph name.

Something along

```
line   section   paragraph   text
388    main                   UNSTRING A-VAR DELIMITED BY
1768   testme    test-1              MOVE A-VAR TO B-VAR
1978   testme    test-3         MOVE B-VAR TO A-VAR
```

Not necessary but nice would be a highlighting of the search (in the case above A-VAR)

This list could be a new entry in the issue/log/compiler pane. It could either be opened automatically when a new "search all" function is used (possible shortcut: [CTRL]+[SHIFT]+[F]) and/or if the number of matches in search pane is clicked.

When clicking on an entry the editor would jump to this line.

**Comment by ColinDuquesnoy** [comment]
This feature is also already available in the new IDE and won't get into OpenCobolIDE.

It looks like this:

![search_panel](https://cloud.githubusercontent.com/assets/1681217/7989448/c14fd584-0ae9-11e5-9bcc-2de86d77ddf8.png)

**Comment by GitMensch** [comment]
Marvelous - I cannot wait to get my hands on the new IDE :-)
