### ISSUE TITLE
[Enhancement] Add toolbar item "background check"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#174]
Especially for slower PCs/big source files/source files, when editing non-compilable files and everything is red, ... it would be nice to be able to disable/enable this function.

Enabling/disabling is currently done, but only internal if the COBOL compiler works/doesn't work. It would be nice to enable the user to do it via a toolbar switching button, too.

**Comment by ColinDuquesnoy** [comment]
Indeed this would be useful.

**Comment by ColinDuquesnoy** [comment]
There is already a global switch for that (Preferences->Editor->View->Show errors).

Is it ok to have a global switch or would it be better to have this works on the current editor only?

**Comment by GitMensch** [comment]
> There is already a global switch for that (Preferences->Editor->View->Show errors).

Not checked if it's already in but it cannot harm to explain via Tooltip more about what actually is done if it is enabled.

> Is it ok to have a global switch or would it be better to have this works on the current editor only?

Both :-)
It's important to have a global switch but it would be good to be able to set the opposite for a single editor, too. Maybe add the option as an internal property to the editor window. The background for this editor would be enabled if the editor has changes and the internal property is set. This internal property is set on editor creation from the global pre-set and can be switched via toolbar switcher.

**Comment by ColinDuquesnoy** [comment]
> Not checked if it's already in but it cannot harm to explain via Tooltip more about what actually is done if it is enabled.

It has been in since v4.0. There is a tooltip that says: "Compile your code on the fly and show errors while you're typing"

> Both :-)
It's important to have a global switch but it would be good to be able to set the opposite for a single editor, too. Maybe add the option as an internal property to the editor window. The background for this editor would be enabled if the editor has changes and the internal property is set. This internal property is set on editor creation from the global pre-set and can be switched via toolbar switcher.

I agree. I'll do it the way you describe.

**Comment by ColinDuquesnoy** [comment]
I added a status bar item, just before the fixed/free format indicator. IMHO it looks better in the status bar than in the toolbar.

![screenshot_20160117_191003](https://cloud.githubusercontent.com/assets/1681217/12378932/202c228a-bd4e-11e5-919f-3d155ad6fd91.png)

**Comment by GitMensch** [comment]
> IMHO it looks better in the status bar than in the toolbar.

Yes, good work. 4.7 Milestone is nearly to being reached :-)

**Comment by ColinDuquesnoy** [comment]
> Yes, good work. 4.7 Milestone is nearly to being reached :-)

Yes :-) I think I'll first make a RC sometime during the next week and a final next weekend if not show stopper is found.
