### ISSUE TITLE
[Bug] F3 is assigned two times as shortcut

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#175]
"Go to assignments" and "Find next" - none of them works for me when pressing F3.

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
F3 is pretty standard for find next (Shift+F3 for find previous) so I propose to change the goto shortut to something like F8 (I would then use F7 for go back #141)

**Comment by GitMensch** [comment]
As written in #141 I think [F8] is good (and can be changed in 4.6.2 final) and add the other jumps features with completely different shortcuts in a later release.

**Comment by ColinDuquesnoy** [comment]
Fixed by commit pyQode/pyqode.cobol@e101887fcc6bc6c8e5d91a79a8c8ac6ec5224caa

**Comment by ColinDuquesnoy** [comment]
F8 is already used for the compile action, I choose to use F7 for goto instead (see pyQode/pyqode.cobol@b3749322ff4357ec36465ac0105de7ae3f2f0b61)
