### ISSUE TITLE
[Enhancement] Bettering search function by little effort

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#176]
* add tooltips for buttons in search pane
* as [ENTER] does "find next" when search pane is opened allow [SHIFT]+[ENTER] for "find previous"

**Comment by ColinDuquesnoy** [comment]
Implemented in pyqode.core (dev branch).

**Comment by GitMensch** [comment]
I've updated all packages.

    pip3 install git+http://github.com/pyQode/pyqode.core.git --upgrade
    pip3 install git+http://github.com/pyQode/pyqode.cobol.git --upgrade
    pip3 install git+http://github.com/pyQode/pyqode.qt.git --upgrade
    pip3 install git+http://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade

Looks nice, but [SHIFT]+[ENTER] still searches for the next appearance, not the previous one. There aren't any tooltips on the buttons either (which could show [despite the obvious use] the tooltips).

## System information


- OpenCobolIDE: 4.6.6
- Python: 3.4.3 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
That's because you've used the "master" branch but I made the modification on the "dev" branch. Dev will be merged in master when 2.7 is finished.

You can test it that way (note the @dev for each pyqode repo)

```
pip3 install git+http://github.com/pyQode/pyqode.core.git@dev --upgrade
pip3 install git+http://github.com/pyQode/pyqode.cobol.git@dev --upgrade
pip3 install git+http://github.com/pyQode/pyqode.qt.git@dev --upgrade
pip3 install git+http://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade
```

**Comment by ColinDuquesnoy** [comment]
> There aren't any tooltips on the buttons either (which could show [despite the obvious use] the tooltips).

Right. I'll add them.

**Comment by ColinDuquesnoy** [comment]
I'll also make some more improvements to the search panel:
  - [ ] change the implementation of ``select_next``/``select_previous`` to take the cursor position into account
  - [ ] add ability to search in selected text

*PS: If you update to the dev branch, you'll notice that there has been some changes in the context menu but it is half finished. I plan to finish it during the weekend...*

**Comment by GitMensch** [comment]
> PS: If you update to the dev branch, you'll notice that there has been some changes in the context menu but it is half finished. I plan to finish it during the weekend...

I would like to wait until you state that the dev branch can be currently considered stable and does not has half finished stuff in ;-)

**Comment by ColinDuquesnoy** [comment]
I've finished with the new features of pyqode.core, it should be fairly stable but need some testing...
