### ISSUE TITLE
[Bug] deleted items are not uncollapsed

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#177]
To reproduce the issue

* take any code with some statements
* add "IF sample" at the start (let's say it's in line 10)
* leave the line and a collapsing option occurs
* collapse the IF statement  (let's say you see the collapsed line in line 10, the next line is line 30)
* mark the line "IF sample" from it's end to the end of the previous line
* delete the line
* you'll see line 9, then line 30

The only way to view your source again is to save and reload the file.

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
This is a tough one, I think I will post pone it to the next bug fix release aka v2.6.3 (I am sure you will find other bugs ;) ). There is an urgent need for a new release on linux, because of issue #155.

**Comment by ColinDuquesnoy** [comment]
I think I got it fixed in pyqode.core@master. This is a tricky one so if you find another case where it does not work, just comment and I will reopen
