### ISSUE TITLE
[Bug] linter creates binaries in background

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#180]
The current call is 

```
$compiler -o $outputdir\$sourcename$soext -std=$std_set$checked_compileroptions $own_compileroptions $sourcename.$sourceext
```
Why not using the much faster command (without the need to remove the temporary binary later)

```
$compiler -fsyntax-only -std=$std_set $checked_compileroptions $own_compileroptions $sourcename.$sourceext
```

From cobc --help:
>-fsyntax-only    Syntax error checking only; don't emit any output

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
Indeed this would be much better. I'll probably implement this while working on other linters issues
