### ISSUE TITLE
[Bug] Compilation information in Issues tab misleading

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#181]
After changing the compiler I've seen the following in Issues tab:

```
Compilation succeeded (output: mydir\bin\prog.dll)
```

But the Compiler tab says:

```
mycompilepath\cobc -o mydir\bin\prog.dll -std=default -debug prog.cob

cobc: prog.cob: No such file or directory
```

Therefore OCIDE either does not delete the outputfile [or rename if it renames it back when compilation failed] before calling the compiler and/or does not check if it's actually was created.

(The actual problem not finding the sourcefile is a different issue and likely on my side)

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.7.0.dev2
- pyqode.cobol: 2.6.1
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
Indeed, OCIDE does not remove the dll/exe before compiling, I'll fix that.

**Comment by ColinDuquesnoy** [comment]
Should be better now, the IDE will remove the binary file before compiling and check if the binary has been successfully create after the compilation process finished.
