### ISSUE TITLE
[Enhancement] Let the advanced user choose the full path to the compiler

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#183]
As a follow up to #128 

> I don't remember why I chose to do it that way (I wrote the compiler code two years ago) but indeed atm you can only choose a directory. I think there is no need to do it that way anymore so I might change that for v4.7 (maybe open a new issue that request for the full compiler path). 

As you may guess I explicit ask for changing this in 4.6.2 as 4.7 is a long way to go - and I'd expect most users to switch to the new IDE as it's target to be release on the same time.

**Comment by ColinDuquesnoy** [comment]
Fair enough. This requires quite a lots of changes and testing. I'll see if I can get it done for 4.6.2, if not it will be for another 4.6.x release (way before the 4.7 release).

**Comment by ColinDuquesnoy** [comment]
Should be ok now, tested on Windows.

**Comment by GitMensch** [comment]
Doesn't work in 4.6.2 if VCVARS32.bat is used.

It looks like OCIDE creates %temp%\cobc_wrapper.bat for calling VCVARS32. This file reads

```cmd
@echo off
set OLDDIR=%CD%
chdir C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin
call VCVARS32
chdir /d %OLDDIR%
@echo on
call cobc %*
```

Issues:

* the call to cobc must be replaced by the compile command from preferences
* the call to VCVARS32 should call VCVARS32.bat
* there is no chdir into and back necessary

suggested cobc_wrapper.bat:

```cmd
@echo off
call "%ocide_vcvars32_path%"
@echo on
call "%ocide_cobc_path%" %*
```

The creation can either be dynamic (as it is now) or even better: ship this wrapper batch with the installation and set the two environment vars before calling it.

BTW (not checked in sources if it's done): it's not necessary to call this batch for getting the version number (as cobc --version does not need Microsoft's C compiler, therefore we don't need to setup this)

**Comment by GitMensch** [comment]
There's no workaround for this...
Changing the file has no effect as it's recreated each time and removing rights / set to write-protected leads to "Permission error" :-(

**Comment by GitMensch** [comment]
bump

**Comment by GitMensch** [comment]
Looks good. Is there any reason for not using the full path for calling VCVARS? Currently the setting has the full path but OCIDE uses only the path and does a chdir to this and a chdir back - why using the chdir at all?

BTW: the ```call VCVARS``` after ```chdir``` likely doesn't work if VCVARS is not on the same disk drive where %TEMP% is as chdir doesn't change the active disk drive. calling VCVARS with the full path from the setting would work.

**Comment by ColinDuquesnoy** [comment]
Good question, thank you for pointing that out.

I will check that next time I boot on windows.

**Comment by ColinDuquesnoy** [comment]
There was no reason for not using a direct call to vcvars32.bat, the following wrapper batch is now generated:

``` bat
@echo off
call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"
@echo on
call C:/OpenCobol/cobc.exe %*
```

**Comment by GitMensch** [comment]
Not a big issue, but why not use

~~~~~
call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" 1>NUL
call C:/OpenCobol/cobc.exe %*
~~~~~
