### ISSUE TITLE
[Bug] File is compiled multiple times if multiple files with same file name (different extensions) exist

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#184]
Place test.cob and test.lst + test.cpy in a directory. Open test.cob, use compile - all three get compiled. Here is the log snipped:

```
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.cpy not found in cache, using locale preferred encoding instead: cp1252
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.lst not found in cache, using locale preferred encoding instead: cp1252
INFO::open_cobol_ide.controllers.cobol::running compilation thread: ['D:\\dev\\GnuCOBOL\\own_tests\\COBDUMP.cbl', 'D:\\dev\\GnuCOBOL\\own_tests\\COBDUMP.lst', 'D:\\dev\\GnuCOBOL\\own_tests\\COBDUMP.cpy']
INFO::open_cobol_ide.compilers::compiling D:\dev\GnuCOBOL\own_tests\COBDUMP.cbl
INFO::open_cobol_ide.compilers::command: D:/dev/MinGW/GnuCOBOL/bin/cobc.exe -o D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll -std=default -debug COBDUMP.cbl
INFO::open_cobol_ide.compilers::compiler process exit code: 0
INFO::open_cobol_ide.compilers::compiler process output: 
INFO::open_cobol_ide.compilers::binary file (D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll) created:  True
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.lst not found in cache, using locale preferred encoding instead: cp1252
INFO::open_cobol_ide.compilers::compiling D:\dev\GnuCOBOL\own_tests\COBDUMP.lst
INFO::open_cobol_ide.compilers::command: D:/dev/MinGW/GnuCOBOL/bin/cobc.exe -o D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll -std=default -debug COBDUMP.lst
INFO::open_cobol_ide.compilers::compiler process exit code: 0
INFO::open_cobol_ide.compilers::compiler process output: 
INFO::open_cobol_ide.compilers::binary file (D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll) created:  True
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.cpy not found in cache, using locale preferred encoding instead: cp1252
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.lst not found in cache, using locale preferred encoding instead: cp1252
INFO::open_cobol_ide.compilers::compiling D:\dev\GnuCOBOL\own_tests\COBDUMP.cpy
INFO::open_cobol_ide.compilers::command: D:/dev/MinGW/GnuCOBOL/bin/cobc.exe -o D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll -std=default -debug COBDUMP.cpy
INFO::open_cobol_ide.compilers::compiler process exit code: 0
INFO::open_cobol_ide.compilers::compiler process output: 
INFO::open_cobol_ide.compilers::binary file (D:\dev\GnuCOBOL\own_tests\bin\COBDUMP.dll) created:  True
WARNING::open_cobol_ide.compilers::encoding for D:\dev\GnuCOBOL\own_tests\COBDUMP.cpy not found in cache, using locale preferred encoding instead: cp1252
```

## System information

- OpenCobolIDE: 4.6.2
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (64bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.5
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
This happen only with cobdump isn't it? I cannot reproduce that bug with a simple hello world... I guess this happen because cobdump call itself, the ide try to see if there are any calls to submodules and search for files with ``$submodule_name.$[one of the possible cobol extensions]`` -> [cobdump.cpy, cobdump.lst]. Fixable but not urgent...

FYI I'll take some time to work on the new IDE, next OpenCobolIDE bug fix release won't happen before 3-4 weeks unless there is a very critical bug.

**Comment by GitMensch** [comment]
OK, not a too big issue.

The guess was quite good: COBDUMP doesn't call itself but it's header says:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.   COBDUMP.
      *****************************************************************
      ** This is an OpenCOBOL subroutine that will generate a        **
      ** formatted Hex/Char dump of a storage area.  To use this     **
      ** subroutine, simply CALL it as follows:                      **
      **                                                             **
      ** CALL "COBDUMP" USING <data-item>                            **
      **                    [ <length> ]                             **
      **                                                             **
```

if I change it to

```cobol
      ** C A L  L "COBDUMP" USING <data-item>                            **
```

and even if I add

```cobol
       78  COBD                 value "COBDUMP".
               CALL COBD END-CALL
```

it isn't compiled multiple times. Therefore I'd say we have multiple issues here:

1st: whatever parses this for recognizing external CALLs - it must exclude comment lines.
2nd: if possible it should parse level 78 (and 01/77 AS CONSTANT) to include them if they are referenced via CALL.
3rd (the obvious one): OCIDE should remember which modules it compiled already

And one thing I like to request about it:
Make the feature (which is indeed nice) optional [for new IDE project specifc]. I just thought about what this would done if the main program of a big software is compiled (and all 3000+ COBOL modules are generated).

**Comment by ColinDuquesnoy** [comment]
You're totally right. Let's decompose this issue intp the following tasks:

- [ ] exclude comment lines from possible results
- [ ] parse level 78/01/77 as constant and look into them for possible. Ideally we should use the new parser (pyQode/pyqode#41) for getting possible constant values to lookup. This probably won't get in before v4.7
- [ ] compare source/dest mtime to prevent useless recompilation

**Comment by GitMensch** [comment]
Sounds good.

Ideally the source/dest mtime comparison should check all copybooks (and if possible copybooks in copybooks), too.

**Comment by ColinDuquesnoy** [comment]
The steps that could be done for v4.6.3 are done. The remaining steps should be done for v4.7.

**Comment by ColinDuquesnoy** [comment]
> And one thing I like to request about it:
Make the feature (which is indeed nice) optional [for new IDE project specifc]. I just thought about what this would done if the main program of a big software is compiled (and all 3000+ COBOL modules are generated).

This is now an optional feature, I added a check box in the compiler settings: "Auto-detect and compile submodules". If unchecked, only the the current editor will be compiled.

**Comment by GitMensch** [comment]
Can this ticket be closed? Looks it's better to split the item into two issues (4.6 and 4.7)

**Comment by ColinDuquesnoy** [comment]
Yes. Not sure if it will make it to OCIDE (tracked in HackEdit/hackedit#62)
