### ISSUE TITLE
[Enhancement] Let the advanced user choose the full path to the runtime module loader (cobcrun)

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#185]
As a follow up to #183 it would be good to allow the user to set the runtime module loader, too. This would go into the run tab of application preferences with the following entries (similar to compiler settings):

Runtime module loader path, additional command line options [have to be added directly after the module loader, before the COBOL module when OCIDE calls this], optional PATH, and whatever of the following runtime settings you want to include (COB_LIBRARY_PATH and COB_PRE_LOAD should be in; the list is what newer cobcrun --runtime-env shows):

```
Call environment
    COB_LIBRARY_PATH
    COB_PRE_LOAD
    COB_LOAD_CASE
    COB_PHYSICAL_CANCEL

File I/O
    COB_SYNC
    COB_LS_USES_CR
    COB_SORT_MEMORY
    COB_SORT_CHUNK
    COB_FILE_PATH
    COB_LS_NULLS
    COB_LS_FIXED
    COB_VARSEQ_FORMAT
    COB_UNIX_LF

Screen I/O
    COB_REDIRECT_DISPLAY
    COB_BELL
    COB_TIMEOUT_SCALE
    COB_SCREEN_EXCEPTIONS
    COB_SCREEN_ESC
    COB_LEGACY

Miscellaneous
    COB_SET_TRACE
    COB_TRACE_FILE
    COB_DISABLE_WARNINGS
    COB_ENV_MANGLE
```

As 2.0 (from next "official" source build on) will include an optional COB_RUNTIME_CONF [set via cobcrun --conf, too] that can include all these settings, it may is enough to have the "minimal" settings COB_LIBRARY_PATH and COB_PRE_LOAD in, together with the "additional command line options".

We may add "Check module loader" with "test module loader", too (the first using $module_loader --version, the second using $module_loader $module_loader_options TEST [given a previous compiled TEST.cob])

**Comment by GitMensch** [comment]
I've just seen that COB_SCREEN_EXCEPTIONS and COB_SCREEN_ESC are already exported - this should be changeable by the user.

**Comment by GitMensch** [comment]
Recent versions of GnuCOBOL (dev tarball/build from yesterday is available) support a runtime configuration file (settings in environment override everything).
It would be nice to either set the runtime configuration file from within the GUI (set by ``COB_RUNTIME_CONFIG`` [``cobcrun -c`` would be possible, too - but it's not useful if testing executables]).

Because of the "test executables" part it's better to not add a tab like "module loader" but something like "Runtime environment" with a "Module Loader path", a PATH setting [checkbox "same as Compiler" would be nice] and multiple settings (these that you can get from cobcrun --runtime-env in newer versions).

Additional hint: you find descriptions for all runtime settings in the new development snapshot in config/runtime.cfg - this may come in handy for the tooltips of all runtime-settings.

**Comment by ColinDuquesnoy** [comment]
This will never happen in OCIDE. Maybe in HackEdit. I suggest you open a new issue on the HE tracker.  Note that in HE you can setup the environment variables that you need both for compiling and for running a program/module. You can also set up custom program arguments (i.e. to pass your config file).
