### ISSUE TITLE
[Minor Bug] Tooltip(s) missleading "require a restart"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#186]
According to #161 a restart is not necessary.
I did not checked if there are other references to a required restart - the one I've seen is found in compiler settings.

**Comment by ColinDuquesnoy** [comment]
I'll check the tooltips for next bug fix release.

**Comment by GitMensch** [comment]
Looks good.

I don't want to bother you...
...but... the correct spelling is still GnuCOBOL, not GnuCobol - I *think* all older references are fine.

**Comment by ColinDuquesnoy** [comment]
>  don't want to bother you...
...but... the correct spelling is still GnuCOBOL, not GnuCobol - I think all older references are fine.

Right, should be fixed now...

**Comment by GitMensch** [comment]
Found another one ;-) README.rst

cobol -> COBOL
GnuCobol -> GnuCOBOL

**Comment by ColinDuquesnoy** [comment]
My bad, I only checked *.py files. Thank you :)
