### ISSUE TITLE
[Minor Bug] test.cbl + executable are not deleted

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#189]
In my case it's "%temp%\test.cbl" and "%temp%\test.exe".

## System information

- OpenCobolIDE: 4.6.2
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.5
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.0

**Comment by ColinDuquesnoy** [comment]
I am a bit confused, is test.cbl a linter file or a file you create in the IDE? Are you referring to issue #181?

**Comment by GitMensch** [comment]
I don't refer to anything. Sorry for not explaining the most important part here:

These files are created in background by "Check compiler" (both on startup and via Preferences dialog).
