### ISSUE TITLE
EXTERNAL TERMINAL NOT WORKING

### ISSUE THREAD

**Issue by DILOMAGIC** [OpenCobolIDE/OpenCobolIDE#190]
Hi Colin, ON window 8.1. after compiling a COB program , when click on RUN, I see the message "Launched in external terminal" but nothing happens. Compile and Run buttons becames grey and I have to choose COBOL --> Cancel to continue . This happens under some circumstances non at every even. 
This is the simple prgram.

``` cobol
       Identification Division.
       Program-Id. D-CLE.
       Data Division.
       Working-Storage Section.

       01  AAAA PIC XXXXX  VALUE "   ".
       01  i PIC 99.
       01  j PIC 99.
       01  ll PIC 99.
       01  cc PIC 99.
       01  r1c1.
           05 r1   PIC 99 VALUE 01.
           05 c1   PIC 99 VALUE 01.
       01  r2c2.
           05 r2   PIC 99 VALUE 25.
           05 c2   PIC 99 VALUE 80.
       01  bco  PIC 9 VALUE 0.
       Linkage Section.


      *> **************************************************************
      *>           P R O C E D U R E   D I V I S I O N
      *> **************************************************************
       PROCEDURE DIVISION.
           move "0415" to r1c1
           move "1248" to r2c2
           move 04 to bco

           perform varying i from r1 by 1 until i > r2
             perform varying j from c1 by 1 until j > c2
               display " " AT LINE i COL j with background-color bco
                       end-display
             end-perform
             *> CALL "C$SLEEP" using 1 END-CALL
           end-perform

           accept  AAAA at 2001 WITH PROMPT.

           *> call "CBL_OC_DUMP" using cstruct ON EXCEPTION CONTINUE end-call

           *> display "11111111111111111111111111111111111111111111111111111111111111111111111111111111"   AT 0101
           *> display "22222222222222222222222222222222222222222222222222222222222222222222222222222222"   AT 0201
           *> display "33333333333333333333333333333333333333333333333333333333333333333333333333333333"   AT 0301
           *> display "44444444444444444444444444444444444444444444444444444444444444444444444444444444"   AT 0401
           *> display "55555555555555555555555555555555555555555555555555555555555555555555555555555555"   AT 0501
           *> display "66666666666666666666666666666666666666666666666666666666666666666666666666666666"   AT 0601
           *> display "77777777777777777777777777777777777777777777777777777777777777777777777777777777"   AT 0701
           *> display "88888888888888888888888888888888888888888888888888888888888888888888888888888888"   AT 0801
           *> display "99999999999999999999999999999999999999999999999999999999999999999999999999999999"   AT 0901
           *> display "00000000000000000000000000000000000000000000000000000000000000000000000000000000"   AT 1001
           *> display "11111111111111111111111111111111111111111111111111111111111111111111111111111111"   AT 1101
           *> display "22222222222222222222222222222222222222222222222222222222222222222222222222222222"   AT 1201
           *> display "33333333333333333333333333333333333333333333333333333333333333333333333333333333"   AT 1301
           *> accept  AAAA at 2001 WITH PROMPT.
           *> display "----------"   AT 1305 WITH SCROLL UP BY 4 LINES
           *> accept  AAAA at 2001 WITH PROMPT.
           *> display "++++++++++"   AT 1305 WITH SCROLL DOWN BY 2 LINES
           *> accept  AAAA at 2001 WITH PROMPT.
           Goback.
       End-Program.
```

**Comment by ColinDuquesnoy** [comment]
Hi. 

Thank you for reporting! I don't have access to a windows machine right now, will check ASAP.

**Comment by DILOMAGIC** [comment]
HI colin , the error occurs in a cycle of software development such as this.
editing a source, compile, run, stop the execution by clicking on the x window without waiting for the normal end of the program. repeating this cycle many times it generates the error condition.
to solve I close the editor and reboot.

**Comment by ColinDuquesnoy** [comment]
Thanks for the description, that will help me reproduce your issue!

> stop the execution by clicking on the x window without waiting for the normal end of the program

That is probably the culprit. Your program is running through a wrapper executable ("pyqode-console.exe") whose sole purpose is to keep the terminal open when your program exit. I am not sure what happen when you close the terminal window directly. I will have access to a windows machine today, I am going to investigate.

> close the editor and reboot

Instead of rebooting, you might want to look into the task manager for any remaining 'pyqode-console.exe' process and kill them. Then restart the IDE...

**Comment by ColinDuquesnoy** [comment]
> repeating this cycle many times

How much is "many times"? I've just tried to run your program and close the terminal repeatedly during about 10 minutes and the error did not occur yet...

Next time the error occur, could you paste the application log here? (?->About OpenCobolIDE -> Log tab)

**Comment by ColinDuquesnoy** [comment]
@DILOMAGIC Do you still have a problem with this? I can't reproduce it on my system...

**Comment by DILOMAGIC** [comment]
Yes I stil have this problem but i can't understand under which condition
it happens.It seems to be random.
today it happened to me two times. I have to exit from IDE and restart.
I attach an example with screenshots of the process that comes in error and
the log.



2015-09-13 19:14 GMT+02:00 Colin Duquesnoy <notifications@github.com>:

> @DILOMAGIC <https://github.com/DILOMAGIC> Do you still have a problem
> with this? I can't reproduce it on my system...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/190#issuecomment-139896348>
> .
>



-- 

*Eugenio Di Lorenzo*

[image: Descrizione: Descrizione: Descrizione: Descrizione:
C:\Cedacri\firma\gogreen.gif]  Think green, read from the screen!

**Comment by ColinDuquesnoy** [comment]
@DILOMAGIC I cannot see attachments you made with your mail client. You need to come here on github.com to attach images...

**Comment by GitMensch** [comment]
@DILOMAGIC please recheck with current version and report back. If it still doesn't work please post exact version of used COBOL compiler, together with your screenshots.
If there is no response the issue should be closed-

**Comment by ColinDuquesnoy** [comment]
Closing because of lack of feedback. Comment if you find a way to reproduce it and I'll reopen.
