### ISSUE TITLE
Auto-Detect and compile submodules is not working lowercase.

### ISSUE THREAD

**Issue by Daveman90** [OpenCobolIDE/OpenCobolIDE#191]
`CALL "marco" USING polo` is getting autocompiled, while `call "marco" using polo` is not. Even if I set _Proposed keywords_ to _lowser-case_

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting!

**Comment by ColinDuquesnoy** [comment]
Fixed in master branch. There is now a new test  cover this case. A new bug fix release will be available soon.
