### ISSUE TITLE
Failed to find GnuCOBOL Compiler

### ISSUE THREAD

**Issue by trayres** [OpenCobolIDE/OpenCobolIDE#193]
I have a batch file containing two lines, in order to rule out a previous issue that was on a closed ticket:

SET PATH=D:\OpenCobolIDE;D:\OpenCobolIDE\GnuCOBOL;D:\OpenCobolIDE\GnuCOBOL\bin
OpenCobolIDE.exe

When I run "Check Compiler" I get this:
Complier check failed:

Exit code: 1
Output:d:/opencobolide/gnucobol/bin/../lib/gcc/mingw32/4.8.1/../../../crt2.o:(.text+0x1c6): undefined reference to `_setargv'
collect2.exe: error: ld returned 1 exit status

Tip: You might need to adapt the environment variables set by the IDE to make it work.

I'm on Windows 7x64 with no MinGW (or TDM-GCC, or FreePascal) in my path (as I ran from a batch file and explicitly set the %PATH%.

**Comment by ColinDuquesnoy** [comment]
Have you seen this thread: https://answers.launchpad.net/cobcide/+question/269998

This is exactly the same error. The user ended up renaming its MinGW install even if it was not in %PATH%. Where is your MinGW install located? I think the bundled MinGW might look up into c:\MinGW even if that path is not in %PATH%. I might be wrong but that would explain the error.

@GitMensch Any idea?

**Comment by trayres** [comment]
Yes, I have a MinGW installed, but it is in D:\MinGW;
There is an environment variable, MINGW_HOME, but removing that didn't help
either.
Darn, I thought that'd be it.

**Comment by ColinDuquesnoy** [comment]
Can you turn on verbose log and paste the output log here after you've restarted the IDE? I should have more information regarding the compiler process' environment.

**Comment by ColinDuquesnoy** [comment]
(*Help->About OpenCobolIDE->Log tab*)

**Comment by GitMensch** [comment]
The value of %PATH% is irrelevant:

* MinGW binaries include the build path - which always starts with /mingw
* /mingw is used as \mingw if you're outside of MSYS
* \mingw means "disk drive of current process" + \mingw

If you want to use the packaged mingw version of GC you cannot install OCIDE on the same disk drive as your existing mingw folder if it's in root directory. Either use another disk drive for OCIDE or for your MinGW install - or install MinGW to a sub folder.

This is already in #145, therefore I suggest to close this here as [Duplicate] and try to heck this situation in the installer as #145 suggests.

Simon

**Comment by ColinDuquesnoy** [comment]
Thanks for the clarification Simon. I will also add an entry to the FAQ.

**Comment by trayres** [comment]
Thank you all.
