### ISSUE TITLE
[Bug] Compilation halts if output directory is not writeable or does not exist

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#194]
The only option is to abort the compilation. 

As the preferences had a relative path as output directory and other compilations did work this was a little bit confusing first.

After realizing that the output directory did not exist I've changed the setting and everything works.
Please check that cobc is called as it checks and display an error in this case. If OCIDE needs to write anything before calling cobc it should check and raise an error itself.

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by GitMensch** [comment]
Works as good as #196, thumbs up!

You may want to check the behaviour if there are 20 submodules, all their build directories are protected and the option "auto-detect and compile submodules" is active.

**Comment by ColinDuquesnoy** [comment]
> You may want to check the behaviour if there are 20 submodules, all their build directories are protected and the option "auto-detect and compile submodules" is active.

Good point! I'll check that...

**Comment by GitMensch** [comment]
Hm, this change stops compilation for all dependencies, doesn't it?

If possible I'd like to see the message once as a popup and all compilation outputs in lower pane (including all error messages for submodules). But this may be my preference only.

On the other hand: if one submodule doesn't work I'd be able to skip this file if the complete sub-build is stopped otherwise...

Thoughts?

**Comment by ColinDuquesnoy** [comment]
> Hm, this change stops compilation for all dependencies, doesn't it?

Yes but I guess it does not hurt to show all permission error in the issue tab. I'll make the change before I release v4.6.6

**Comment by ColinDuquesnoy** [comment]
Fixed by commit 01856a9c326ccc1b2c6e51c781c10d39f49b53fe

**Comment by GitMensch** [comment]
Looks good.
