### ISSUE TITLE
[Bug] Log pane (Issues tab): Line breaks from cobc & gcc are not translated correctly

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#195]
Something went wrong compiling a file. Therefore I wanted to check what happens and added -v to extra command line options in preferences dialog.

This worked and I've got the information I wanted to see, but all line breaks are missing in the log pane and is truncated:

	preprocessing TESTME.cob into C:\Users\Simon\AppData\Local\Temp\cob7B4C.cobparsing C:\Users\Simon\AppData\Local\Temp\cob7B4C.cob (TESTME.cob)

Workaround: copy and paste the line as this expands it to the full message

	preprocessing TESTME.cob into C:\Users\Simon\AppData\Local\Temp\cob7B4C.cob
	parsing C:\Users\Simon\AppData\Local\Temp\cob7B4C.cob (TESTME.cob)
	../TESTME.CPY:11: Error: syntax error, unexpected Literal, expecting FUNCTION-ID or PROGRAM-ID
	Return status:	1
	exit 

Please fix the log pane to show multiple lines.

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
I cannot reproduce this issue neither on GNU/Linux nor on OSX. This is probably a windows specific issue, probably with line endings conversion.

**Comment by GitMensch** [comment]
It likely is, maybe even with mixed line endings (depending on what the called batch actually does).

The brutal way would be to replace x'0d0a' to an exchange sign, then all x'0d', then all x'0a' - and then convert the exchange sign to the needed line break. But this ensures that it works.

**Comment by ColinDuquesnoy** [comment]
Mmm, that works fine for me on Windows 10 x64:

![capture](https://cloud.githubusercontent.com/assets/1681217/9856868/911a0172-5b17-11e5-881d-f99f4099a078.PNG)

**Comment by GitMensch** [comment]
May has something to do with #204 as I see this in most files now...

**Comment by ColinDuquesnoy** [comment]
Does that still happen?

**Comment by GitMensch** [comment]
With a simplified environment (using a MSC version) this still hapens with 4.6.6 release:

I see only one error in Issues tab, without a line number. The error shows the call of vcvars32.bat. If I click on "view details" I see the error in one long line. Using [CTRL]+[C] in the message details dialog I can present the error without correct line breaks...

~~~~~
---------------------------
Message details
---------------------------
<p><b>Description:</b><br/>
C:\TEMP>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"  1>NUL 

C:\TEMP>call "C:\GnuCOBOL\cobc.exe" -x -o C:\TEMP\DECERR-MIN.exe -std=default -debug DECERR-MIN.COB 
DECERR-MIN.COB (2): Error: PROGRAM-ID header missing
DECERR-MIN.COB (2): Error: DATA DIVISION header missing
DECERR-MIN.COB: In section 'HAUPT':
DECERR-MIN.COB (8): Error: 'rrr' is not defined
</p>
            <i><p><b>File:</b><br/>C:\TEMP\DECERR-MIN.COB</p>
            <p><b>Line: </b>0</p></i>
            
---------------------------
OK   
---------------------------
~~~~~

BTW: Why did you made the output for file and line italic (and added an indentation to it)?

**Comment by ColinDuquesnoy** [comment]
> Why did you made the output for file and line italic (and added an indentation to it)?

Bug, this was not made on purpose. I've just fixed that in pyqode.core@dev.

BTW I still canot reproduce your bug with the msvc based compiler I downloaded from [here](http://www.kiska.net/opencobol/esql/). Where can I download the compiler version you're using? If it's a development version, is it possible that you upload it somewhere for me to try?

**Comment by GitMensch** [comment]
You may use the following "official" pre-compiled dev version for use with MSC from [here][1] 

Simon

[1]:http://sourceforge.net/projects/open-cobol/files/gnu-cobol/2.0/gnu-cobol-2.0_nightly_r411_win32_vc11_bin.7z/download

**Comment by ColinDuquesnoy** [comment]
>You may use the following "official" pre-compiled dev version for use with MSC from here

Thank you, I've installed it but still cannot reproduce the problem.

**Comment by ColinDuquesnoy** [comment]
Please recheck this when the next preview build is available. I've added some code to handle '\r' explicitely, though I am not sure if that will help.

**Comment by ColinDuquesnoy** [comment]
At last, I think understand what's happening here. We have two issues:

- the output parser regex does not work with files that contains a '-' in their filename
- the long line you see in the details dialog actually is a display bug (when using html I should convert line endings to <br/>)

Issue should now be fixed, preview build updated: https://www.dropbox.com/s/paufds1mof7slqy/OpenCobolIDE-4.7_Setup.exe?dl=0

**Comment by GitMensch** [comment]
Retested with pre 3 and a CONFIG_DIR which doesn't match the compiler.
Result: the following line can be see in the error description (line breaks missing):
``default.conf:26: unknown tag 'standard-define'default.conf:38: unknown tag 'word-length'``
While the following output is shown correct in the message details:
~~~~~
---------------------------
Message details
---------------------------
<p><b>Description:</b><br/>default.conf:26: unknown tag 'standard-define'<br/>default.conf:38: unknown tag 'word-length'<br/>default.conf:112: unknown tag 'cobol85-reserved'<br/>default.conf:115: unknown tag 'hostsign'<br/>default.conf:119: unknown tag 'accept-update'<br/>default.conf:123: unknown tag 'accept-auto'<br/>default.conf:134: unknown tag 'alter-statement'<br/>default.conf:148: unknown tag 'section-segments'<br/>default.conf: no definition of 'default-organization'<br/>default.conf: no definition of 'auto-initialize'<br/>Invalid option -std=default<br/></p>
<p><b>File:</b><br/>\\SERVER\share\TEST.COB</p>
<p><b>Line:</b><br/>0</p>
            
---------------------------
OK   
---------------------------
~~~~~

BTW: the message in this case has changed in current versions but the line ending is still the same...

**Comment by ColinDuquesnoy** [comment]
That's because "default.conf:26: unknown tag 'standard-define'" is not recognized by the output parser, I only parse syntax related errors (with a "Error" or a "Warning" error level).

Line breaks are corrects but the description entry in the errors table is not multiline.

**Comment by GitMensch** [comment]
Shouldn't the ``<br />`` produce multiple lines in the log pane?

**Comment by ColinDuquesnoy** [comment]
Which log pane? The compiler tab or the issues tab? Line breaks are translated to ``<br />`` only in the message details dialog... Item in the issue table cannot render multiline text, line breaks are automatically removed for rendering so that it fits in one line (standard qt behaviour).

**Comment by ColinDuquesnoy** [comment]
BTW, I log the full compiler output with line breaks when verbose mode is set (here on my linux I can see clearly the '\n').

**Comment by GitMensch** [comment]
I only looked at the issues tab. If the full message including the line breaks can be seen in the compiler tab it's ok. But a hint in issues tab "for full output see compiler tab" if an output contains line breaks would be nice.

And yes: I've recognized the line endings in the log - nice.

To the parser: the current version on the message above is
~~~~
Configuration Error
/tmp/share/gnu-cobol/config/mf.conf: Missing definitions
        No definition of 'numeric-boolean'
        No definition of 'acucobol-literals'
~~~~

What would the user see in this case in the compiler tab (despite the fact that he should never see this in the compiler tab but only in "Check compilation" dialogue)?

**Comment by ColinDuquesnoy** [comment]
> But a hint in issues tab "for full output see compiler tab" if an output contains line breaks would be nice.

Yes it would be better (reopening so that I don't forget to implement that).

> What would the user see in this case in the compiler tab

User should see the full output with line breaks. I write the full compiler output to the compiler tab, but only keep relevant line (which pass the output regex) in the issues tab.

**Comment by GitMensch** [comment]
I did not found the other issue about the message format. As you've posted about the regex-parser here, too I want to suggest to support more formats. I think these are missing:

~~~~~
sourcefile:lineno.column: message

sourcefile:line1.column1-line2.column2: message
sourcefile:line1.column1-column2: message
sourcefile:line1-line2: message

file1:line1.column1-file2:line2.column2: message
~~~~~

and all these with the optional prefix ``program:``.

All samples were taken from https://www.gnu.org/prep/standards/html_node/Errors.html

**Comment by ColinDuquesnoy** [comment]
Thanks, this is a very useful piece of information ;) Issue tracked in HackEdit/hackedit/issues/63
