### ISSUE TITLE
[Bug] No error message if source is read only

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#196]
To reproduce the issue:

* open a source file which is read only
* change something --> The file tab gets a changed marker '*'
* click "Save File" --> Nothing happens, file is unchanged, no error message occurs

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
I've added a message box when a there is a permission error. In the future I will make the editor read-only and will add a top panel to the editor widget to indicate why the file is read only (see pyQode/pyQode#50)

**Comment by GitMensch** [comment]
The current implementation works like a charm.
