### ISSUE TITLE
[Bug] Logs pane, Issues tab: Opening a file with double click does not work for relative paths

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#197]
Works fine if the error message starts with

> TESTME.CPY:11

Doesn't work when compiler outputs a relative path

> ../TESTME.CPY:11

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch.

Implementation come straight from hackedit.

**Comment by GitMensch** [comment]
Yes, is fixed and works fine.
