### ISSUE TITLE
[Information] OCIDE @ Open HUB (formerly Ohloh)

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#199]
Just leaving a note here... you may want to rate, or "I use this", or simply have a short look

https://www.openhub.net/p/OpenCobolIDE (source code not analysed yet)

@ColinDuquesnoy please add missing information when you find the time and claim "project manager" if you want to.

**Comment by ColinDuquesnoy** [comment]
@GitMensch Thank you. OpenHub looks interesting. I've claim to be the "project manager" and I will probably use it for HackEdit and pyQode too.

**Comment by GitMensch** [comment]
@all source code analysed, most project information should be correct now.

@ColinDuquesnoy You're in and may remove me from the Managers (while Manager@OpenHUB simply means "can edit every project information").

According to the stats there was a big source decrease from Aug-->Sept 2014. I did not found out what actually was removed. Please consider adding these files to the ignore list if they aren't part of the project, same applies for external items or general libraries that may be used from within different projects of you and should have an own project entry (ignoring these files for OCIDE and the OCIDE files for the external project).

Issue can be closed afterwards.

**Comment by ColinDuquesnoy** [comment]
The massive drop you're seing is probably due to #26. I've adapted the ignored rules to ignore the OpenCobol distribution.

**Comment by GitMensch** [comment]
No change...
What was added from August - September 2013? This was the massive code increase.

Have you added the generated source+xml to the ignore list yet?

**Comment by ColinDuquesnoy** [comment]
This commit 8b34c7d2653f5df7608364967d2c7bf357388171 added the OpenCobol folder on 08/29/2013. Something weird happend with openhub. The list of ignored files is now empty but I remember I filled it with:

```
Disallow: OpenCobol/
Disallow: GnuCOBOL-Win32-MinGW/
```
When I tried to access it today, it asked me for a confirmation via sms, but not the first time. I'll try again. Let's see if that works better now that the sms authentication has been done.

**Comment by ColinDuquesnoy** [comment]
> Have you added the generated source+xml to the ignore list yet

I consider the xml (*.ui files) as part of the source code since I edit them often using qt-designer. I should ignore the generated python scripts but the location of those scripts has changed so many times that it is a pain to track them (and openhub does not support wildcards and regex)

**Comment by GitMensch** [comment]
This time the list of ignored files empty stayed.

If you moved the generated python scripts via scm (git in your case) it should be no problem to pull out a list where they were. If not: where are they now? Did you rename them over the last years or did the name stay?

Is/where there any external libraries in the repository?

**Comment by ColinDuquesnoy** [comment]
> This time the list of ignored files empty stayed.

Strange, because when I click "Edit ignored files", the value I set yesterday are still there.

![snapshot1](https://cloud.githubusercontent.com/assets/1681217/9268450/6bfbb9c4-425f-11e5-90d8-c90eb0a3ba28.png)

I am probably missing something obvious...

> Did you rename them over the last years or did the name stay?

Some were renamed or moved while some others were simply deleted. The repository layout has changed drastically between each new major versions.

>  If not: where are they now?

Now they are in ``open_cobol_ide/view/forms/*.py``. I guess I could at least ignore those.

**Comment by GitMensch** [comment]
Sorry for the confusion. It was fine.

I've added

~~~~~
Disallow: open_cobol_ide/view/forms/
Disallow: oci/frontend/ui

~~~~~

now (added a newline, too; maybe it's needed like it is with svn:ignore) and maybe hunt down previous releases some day.
While the data was updated the graph is still the same. I think I'll open a technical help topic for this as it's not visible what really added/dropped that much code and it's quite possible the graph is simply not updated for the past.

**Comment by ColinDuquesnoy** [comment]
> added a newline, too; maybe it's needed like it is with svn:ignore

Looks like it worked, now the graph look correct. Thank you! :)

**Comment by GitMensch** [comment]
Looks much better now. I just did some more tweaking, the graph looks even better now :-)

There's still something missing around Jul/Aug 2014 and Aug 2013 in the ignore files.

**Comment by ColinDuquesnoy** [comment]
> There's still something missing around Jul/Aug 2014 and Aug 2013 in the ignore files.

Aug 2013: this was the time where I worked on version 2.0 and moved from launchpad to github. It was a complete rewrite. I deleted the ``cobcide`` package and replaced it by the ``oci`` package, but during development both packages coexisted. Same thing happened between v3 and v4 (Jul/Aug 2014). So I think the graph correctly reflects the state of the code at those times.

There is one last thing that look strange though. Open HUB does not see any commit prior to Aug 2013, which corresponds to the period where I was still using bazaar on launchpad. At that time I made sure not to loose history during the conversion. git-log actually shows commits prior to Aug 2013. E.g. here is the very first commit: df9594d8df897d98f88c4faa1d764c968fbc336c

**Comment by GitMensch** [comment]
Those commits are in, see https://www.openhub.net/p/OpenCobolIDE/commits?sort=oldest

What did you do before?

**Comment by ColinDuquesnoy** [comment]
> Those commits are in, see https://www.openhub.net/p/OpenCobolIDE/commits?sort=oldest

Right. I thought they were not in because the graph starts in Aug 2013.

> What did you do before?

Nothing. First commit on launchpad  was on 18/03/2013. So everything is fine :)
