### ISSUE TITLE
[Enhancement] Add ability to show cursor position in bytes

### ISSUE THREAD

**Issue by kjfang** [OpenCobolIDE/OpenCobolIDE#200]
When typing two-byte characters (e.g. Chinese Word, zh_TW) in a line, the number of current column at the bottom right corner is incorrect.

for example:
01  AA   PIC X(06) VALUE "中文字".
The number in parentheses is 6 not 3, for it occupies 6 bytes.

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 2.0.20140821
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by GitMensch** [comment]
Please attach a sample code file. It highly depends on the coding, if the file is not in UTF-8 the column at 文 should be column of 中 + 2, if it's an UTF-8 file it should be the column of 中 + 1.

**Comment by kjfang** [comment]
Please check the attached file.

It is a small program edited by OpenCobolIDE.

**Comment by GitMensch** [comment]
@kjfang there is no file attached

**Comment by ColinDuquesnoy** [comment]
@kjfang  You cannot attach a file directly on github, you need to upload the file somewhere and share the link.

I think I don't agree with both of you.

1) the unit used to count characters in a QTextDocument is the glyph not bytes. Encoding is irrelevant. 
2) In python3, all string are always represented as UTF-8 internally, no matter what encoding was used to load the file. Encoding is relevant only for load/save.
3) I don't know a single editor that works with bytes to indicate the cursor position, one character is always a glyph.I tested with a big5hcks encoded file. Both GEdit, Kate, Notepad++ and Sublime Text give the same result as OpenCobolIDE.

Closing as invalid.

**Comment by kjfang** [comment]
Hi,

Sorry, I am just an old COBOL programmer. Except the Basic and Pascal at 35
years ago, I had never learned the python or any other languages. Nor
understand the difference between the byte and glyph.
I checked the Notepad++, as you said, it display the wrong cursor position
with two-byte characters.
But no friends of mine use it to edit the COBOL programs.
The fixed format of COBOL strictly limit the code should not exceed column
72.
For COBOL, the cursor position is more significantly than other languages.
If OpenCobolIDE cannot solve the two-byte characters problem, not only
Chinese, but Japanese, Korean, and all the two-byte character systems will
encounter the same problem.
That will restrict the spread of this project.

The Uedit (UltraEdit) had solved this problem since the version 10 or 11.
I have not stored the old version of Uedit.
But I am sure it encountered the same problem before, I used it from
version 9, and had overcome the problem several years ago.
I upload some pictures for you to contrast the OpenCobolIDE and Uedit to
deal with the same COBOL program.
Hope OpenCobolIDE can show the right number of cursor position in the near
future.

Best Regards,
kjfang

pictures download address:
http://www.2shared.com/photo/SFboRefk/OpenCobolIDE-001.html
http://www.2shared.com/photo/bW3sqswJ/OpenCobolIDE-002.html
http://www.2shared.com/photo/8TCXF7n3/Ultraedit.html


2015-08-20 23:46 GMT+08:00 Colin Duquesnoy <notifications@github.com>:

> @kjfang <https://github.com/kjfang> You cannot attach a file directly on
> github, you need to upload the file somewhere and share the link.
>
> I think I don't agree with both of you.
>
> 1) the unit used to count characters in a QTextDocument is the glyph not
> bytes. Encoding is irrelevant.
> 2) In python3, all string are always represented as UTF-8 internally, no
> matter what encoding was used to load the file. Encoding is relevant only
> for load/save.
> 3) I don't know a single editor that works with bytes to indicate the
> cursor position, one character is always a glyph.I tested with a big5hcks
> encoded file. Both GEdit, Kate, Notepad++ and Sublime Text give the same
> result as OpenCobolIDE.
>
> Closing as invalid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/200#issuecomment-133056880>
> .
>



-- 
==============
== 感恩--萬物善 ==
== 讚美--星河盛 ==
== 伺服--知我心 ==
== 共創--世間真 ==
==============

**Comment by ColinDuquesnoy** [comment]
Hi @kjfang 

> For COBOL, the cursor position is more significantly than other languages. If OpenCobolIDE cannot solve the two-byte characters problem, not only Chinese, but Japanese, Korean, and all the two-byte character systems will encounter the same problem. That will restrict the spread of this project. The Uedit (UltraEdit) had solved this problem since the version 10 or 11.

Thank you for opening my eyes. I will reconsider the problem.

**Comment by ColinDuquesnoy** [comment]
@kjfang I am going to look at this during the next week. Can you send me the file you used to take the screenshot so that I can validate the new implementation? You can it to my private email (colin.
 dot duquesnoy at gmail dot com)

**Comment by ColinDuquesnoy** [comment]
@kjfang I implemented this feature. It will be available in v4.6.5. Here are  a few screenshots showing the results:

![1](https://cloud.githubusercontent.com/assets/1681217/9916735/43220e80-5cbe-11e5-87d0-e4bedf32b615.png)
![2](https://cloud.githubusercontent.com/assets/1681217/9916736/433e612a-5cbe-11e5-91eb-86a3e063df58.png)
![3](https://cloud.githubusercontent.com/assets/1681217/9916737/4341083a-5cbe-11e5-9ebd-fdc60537acc0.png)


Let me know if there is anything wrong.

This feature is off by default, you need to enable it by checking the following checkbox in the editor settings:

![settings](https://cloud.githubusercontent.com/assets/1681217/9916740/481c2e8e-5cbe-11e5-9714-dfc59b9898b1.png)
