### ISSUE TITLE
OpenCobolIDE with GnuCOBOL 2.0 or 2.1

### ISSUE THREAD

**Issue by eugeniodilo** [OpenCobolIDE/OpenCobolIDE#201]
Hi Colin great job your IDE.
I'm trying to use the IDE with rel 2.0 changing settings in the preference screen.
The check compiler button say it is ok but compilation don't works (message Failed to find GNU Compiler !)
Could you release an installation file with GnuCOBOL 2,0 and another with 2.1 ?
in this way I can choose ad install quickly 2.0 or 2.1 not only 1.1
Or could you suggest how to change the release from 1.1 to others .

**Comment by ColinDuquesnoy** [comment]
> Could you release an installation file with GnuCOBOL 2,0 and another with 2.1 ?

This is already planned in #158.

> The check compiler button say it is ok but compilation don't works (message Failed to find GNU Compiler !) 

Did you try to press "Check compilation" inside the dialog check compiler dialog? There is probably a problem with one of the environment variables and the output of check compilation might help diagnosing the problem. Can you paste the output after you pressed "Check compilation" and attach a screenshot of the whole compiler settings window?

**Comment by GitMensch** [comment]
GC 2.0 will get an official pre-release with an official MinGW package in the next months. I'll update the MinGW package for collin again.
For now you'd need to build GC2 on your own (or use little outdated "nightly" with VC which works fine in OCIDE if setup correct).

**Comment by GitMensch** [comment]
@DILOMAGIC did you get the compiler working? With a newer GC version and manual changes in preferences dialogue this works quite well.

**Comment by eugeniodilo** [comment]
It will be great if possible to choose also the GnuCOBOL 2.0 DEBUGGER Version binaries. In that way we can compile and debug even if it is a non yet stable release.

**Comment by ColinDuquesnoy** [comment]
> It will be great if possible to choose also the GnuCOBOL 2.0 DEBUGGER Version binaries.

The debugger won't get into OCIDE but most probably in [HackEdit](https://github.com/HackEdit/hackedit) beta

**Comment by eugeniodilo** [comment]
Hi Colin, 
to use the debugger would simply be able to perform ANIMATOR.EXE [filename.cob] (instead of COBC [filename.cob]). Please insert the TP-DEBUGGER from Federico Priolo in the installation package, and please let us have available an icon to perform ANIMATOR.EXE [filename.cob] and an icon to perform the generated filename.exe.
This simple addition would give a great opportunity for more at a better OCIDE

**Comment by GitMensch** [comment]
@ColinDuquesnoy just to clear this up a little bit: the TP-DEBUGGER is a pre-processor that tranforms cob-files to cob-files while adding debugging code (it was written with GnuCOBOL so you could compile it with the MinGW package and distribute it along). It's "normal" process finishes with a call to cobc but you can only pre-process a file if you want to. It uses curses output (needs a "real" terminal).

@eugeniodilo you can compile the TP-DEBUGGER yourself, place it somewhere and use it via the following hack: go to preferences (F2) -> compiler, replace the compiler path with a batchfile where you call the animator first, then the actual cobc - but only on real compilations.

The batchfile could look like the following (you can remove the calls to VCVARS if you only want to use the shipped GC1.1 MinGW package):

~~~~~cmd
@echo off
setlocal

:: use without "rem" for running the animator
rem set doanim=1

:: check of compiler version
if [%1]==[--version] (
   cobc.exe %*
   set rc=%errorlevel%
   goto end
)

:: store all options in the same vars (for getting the last option & optionpath)
FOR %%O IN (%*) DO CALL :storeopt %%O

:: check for working compiler - handle early
if [%option%]==[%TEMP%\test.cbl] (
   call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\VCVARS32.bat" 1>NUL
   cobc.exe %*
   set rc=%errorlevel%
   goto end
)

:: background check
if [%optionpath%]==[%TEMP%] (
   cobc.exe %*
   set rc=%errorlevel%
   goto end
)

:: normal compilation
call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\VCVARS32.bat" 1>NUL
if [%doanim%]==[1] (
   animator %option% -c
   cobc.exe %all-prev-options% %optionfile-plain%.ani
   set rc=%errorlevel%
) else (
   cobc.exe %*
   set rc=%errorlevel%
)
goto end

:storeopt
set all-prev-options=%all-options%
set option=%1
set optionpath=%~dp1
set optionfile=%~nx1
set optionfile-plain=%~n1
set all-options=%all-options% %1
goto :eof

:end
echo exit with %rc%
endlocal
~~~~~

beware1: untested
beware2: you may need to use current 4.7preview for working with external batches

Then just uncomment the "rem" each time you want to use the animator, then switch to OCIDE and click on "compile" & "run".

Simon

**Comment by ColinDuquesnoy** [comment]
@GitMensch  Thank your for the clarification. Looks like a good candidate for the pre-parser system of HackEdit.
