### ISSUE TITLE
[Enhancement] 'Force Compile' Option needed

### ISSUE THREAD

**Issue by zebuscat** [OpenCobolIDE/OpenCobolIDE#202]
Hi Colin,

after a brew version upgrade of one of the packages I run into the following issue.
Compiling a program skips with the following message:
Description:
compilation skipped, up to date... 

Program run after the skipped compile returns the following message:
Last login: Sun Sep 13 23:17:46 on ttys000
~ @ Mac-Book [dirk] $ /Users/dirk/source/Cobol/bin/Bitwise ; exit;
dyld: Library not loaded: /usr/local/opt/berkeley-db4/lib/libdb-4.8.dylib
  Referenced from: /Users/dirk/source/Cobol/bin/Bitwise
  Reason: image not found
Trace/BPT trap: 5
logout

A recompile solves the runtime error.
The circumvention I have used: changed source code (e.g. blank line) to force a compiler run - would be nice to have an IDE 'Force Compile' option included.
Might also be useful after a Cobol compiler update/upgrade.
Please let me know your view on this issue?

Regards,
Dirk Jaeger,
Willich, Germany

**Comment by ColinDuquesnoy** [comment]
> The circumvention I have used: changed source code (e.g. blank line) to force a compiler run - would be nice to have an IDE 'Force Compile' option included.

Yes or a clean action which will remove all binaries. Actually I already implemented that into [HackEdit](https://github.com/HackEdit/hackedit)(the future successor of OpenCobolIDE). I'll see if I will backport that feature into OpenCobolIDE v4.7...

**Comment by GitMensch** [comment]
Yes, actions "Clean" and "Rebuild" would be nice.

**Comment by GitMensch** [comment]
Missed this feature again on testing 4.7pre-1 ;-) but the workaround "add a space and save" still works fine, so no big issue.
