### ISSUE TITLE
[Bug] offset calculator misses occurs

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#203]
01 AAA.
         02 A PIC 999 OCCURS 100 TIMES.
 
Offset of occurance 100 should be 298

## System information

- OpenCobolIDE: 4.6.4
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.4.1
- PyQt: 5.4.1
- pyqode.core: 2.6.7
- pyqode.cobol: 2.6.2
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Bug confirmed. Thank you for reporting!

**Comment by ColinDuquesnoy** [comment]
Should be ok now

![capture](https://cloud.githubusercontent.com/assets/1681217/9884581/cb6870e2-5be0-11e5-89d6-f6877b5053d4.PNG)
