### ISSUE TITLE
Thoughts to GUI issues with "Unhandled exception"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#205]
As described in #204 I was prompted with some of these messages.

~~~~~
---------------------------
[Unhandled exception] UnicodeDecodeError
---------------------------
An unhandled exception has occured:

  File "d:\documents\pyqode.core\pyqode\core\api\client.py", line 278, in _on_process_stderr_ready

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 948: invalid start byte

Would like to send a bug report to the development team?
---------------------------
Close   &Yes   
---------------------------
~~~~~

In general I really like this. Thoughts/questions:

- "Close" and "&Yes" are a little bit confusing. What about the simple "&No" instead of "Close"?
- Is it possible to prevent the same messages be thrown twice? On opening these files all messages get displayed two times (one time from linter, one from editor I guess).

**Comment by ColinDuquesnoy** [comment]
> "Close" and "&Yes" are a little bit confusing. What about the simple "&No" instead of "Close"?

Yes, no problem.

> Is it possible to prevent the same messages be thrown twice? On opening these files all messages get displayed two times (one time from linter, one from editor I guess).

In hackedit, the message won't popup again if you report or ignore it. I can back-port a similar system for v4.7.

But, are you sure those are the same messages? It could be the same exception but in other file...

**Comment by GitMensch** [comment]
> But, are you sure those are the same messages? It could be the same exception but in other file...
Yes, I'm sure. and they come up nearly together, both have to be closed - or all 6 if you have 3 errors...

**Comment by ColinDuquesnoy** [comment]
> Yes, I'm sure. and they come up nearly together, both have to be closed - or all 6 if you have 3 errors...

Ok. I'll add a way to hide those messages in v4.6.6 instead of v4.7.

**Comment by GitMensch** [comment]
Button captions "&Report" and "&Ignore" sound even better. And to save the messages and don't popup them if exactly the same message is raised in the same session would be really good ('I do like to see all 3 errors, but only once, not again after every edit [where linter raises them again and again]).

**Comment by ColinDuquesnoy** [comment]
> I do like to see all 3 errors

If those are the same errors with the same traceback, you'll see them only once per session

**Comment by GitMensch** [comment]
> If those are the same errors with the same traceback, you'll see them only once per session
Sounds good.

But should the milestone be 4.6.6 as 4.6.3 is already published?

**Comment by ColinDuquesnoy** [comment]
Correct, thanks!

**Comment by ColinDuquesnoy** [comment]
> Button captions "&Report" and "&Ignore" sound even better.

Sound nice but I can only use standard buttons when using qmessagebox. To implement that I would need to write my own dialog. That is something I am not going to do for OCIDE so I decided to use Yes/No.

**Comment by GitMensch** [comment]
Fine. Looks like 4.6.6 is coming closer :-)
