### ISSUE TITLE
[Bug] Issues tab doesn't show the issues but cobc_wrapper

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#206]
Compiler tab:

~~~~~
C:\Users\Simon\AppData\Local\Temp\cobc_wrapper.bat -o C:\TEMP\TEST2.dll -std=default -debug TEST2.COB

C:\TEMP>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"  1>NUL 

C:\TEMP>call "D:\GnuCOBOL\gnu-cobol-2.0\build_windows\Win32\Release\cobc.exe" -o C:\TEMP\TEST2.dll -std=default -debug TEST2.COB 
TEST2.COB (30): Error: syntax error, unexpected Identifier, expecting EXTERNAL or GLOBAL
~~~~~

The issues tab shows only the call to vcvars32.bat and if you copy the error your get

~~~~~
C:\TEMP>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"  1>NUL 

C:\TEMP>call "D:\GnuCOBOL\gnu-cobol-2.0\build_windows\Win32\Release\cobc.exe" -o C:\TEMP\TEST2.dll -std=default -debug TEST2.COB 
TEST2.COB (30): Error: syntax error, unexpected Identifier, expecting EXTERNAL or GLOBAL
~~~~~

## System information

- OpenCobolIDE: 4.6.5
- GnuCOBOL: GNU Cobol 2.0.20150329
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.8
- pyqode.cobol: 2.6.3
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
``TEST2.COB (30): Error: syntax error, unexpected Identifier, expecting EXTERNAL or GLOBAL``

I think this line is the culprit. The regex I am using does not expect some parentheses arround the line number and expect a ':' after the filename.

On my system, both GnuCOBOL 1.1 and GnuCOBOL 2.0 would output something like that:

``TEST2.COB:30: Error: syntax error, unexpected Identifier, expecting EXTERNAL or GLOBAL``

Are there any standard format for the compiler output? 

For reference, here is the regex I am using: 

```
^(?P<filename>[\w\.-_\s]*):(?P<line>\s*\d*):(?P<type>[\w\s]*):(?P<error>[\w\s,-:\'"\$]*)$
```

**Comment by GitMensch** [comment]
GC2 uses the style from the underlying compiler, in this case MSC while your system may use a GCC based or an outdated version.
But you can set the environment COB_MSG_FORMAT to GCC and you'll always have the GCC style for your regex.

**Comment by ColinDuquesnoy** [comment]
Thank you Simon, this makes sense now ;) I think I'll go with supporting both.
