### ISSUE TITLE
[Bug] Context menu entries does not work at mouse but at cursor position

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#207]
Using of a context menu entry should always use the mouse position, not the cursor position.

The easiest implementation may be:

- disable screen updates (if possible)
- save current cursor position
- set cursor position based on mouse cursor
- do the requested action
- restore cursor position
- enable screen updates (if possible)

This applies to nearly all context menu options: (un)intend, calculate offset, duplicate line, ...

These should be done at cursor position / selection when used from edit menu but at mouse position (either cursor or selection, whatever is below the cursor) when used from context menu.

## System information

- OpenCobolIDE: 4.6.5
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.8
- pyqode.cobol: 2.6.3
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Right. I am not sure about restoring cusror position, I would expect the cursor to remain in place after the operation (e.g. after paste, the cursor should be at the end of the pasted block and not restored).

**Comment by GitMensch** [comment]
> I would expect the cursor to remain in place after the operation (e.g. after paste, the cursor should be at the end of the pasted block and not restored).

Sounds reasonable.
