### ISSUE TITLE
[Bug] current selection is lost on case-conversions

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#208]
- select something
- convert to upper-case via [CTRL][U]
- the selection is lost

## System information

- OpenCobolIDE: 4.6.5
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.8
- pyqode.cobol: 2.6.3
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Fixed by commit pyQode/pyqode.core@e08c6da78271ef81da2cac0b2d6aebb40c52cd3e (master branch).
