### ISSUE TITLE
[Bug] Offset Calculator with empty Names, wrong offset

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#210]
Create a new file with the following content, mark everything and use the offset calculator:

~~~~cobol
       78 someconst VALUE 'test'.
       01 test01.
          03 test03 PIC X(03).
             88 test-empty VALUE SPACES.
             88 test-a     VALUE "a".
             88 test-b     VALUE "b".
             88 test-c     VALUE "c".
~~~~~

Result:

![wrong_offsets](https://cloud.githubusercontent.com/assets/6699539/10012654/1f0c45f6-610a-11e5-8034-5f7aeb2a04b1.PNG)

## System information

- OpenCobolIDE: 4.6.5
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.8
- pyqode.cobol: 2.6.3
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Works for me:

![capture du 2015-09-22 15-51-59](https://cloud.githubusercontent.com/assets/1681217/10020202/e93feb16-6141-11e5-8fcf-7b99750c8c58.png)

But strange things happen if I sort the columns and re-run compute offsets with the same selection:

![capture du 2015-09-22 15-54-03](https://cloud.githubusercontent.com/assets/1681217/10020245/2d046f98-6142-11e5-961c-075462c63017.png)


Probably a GUI bug (I think the parser is fine).

**Comment by GitMensch** [comment]
We have three issues here:

1. clear GUI bug 
2. no possibility to "unsort"
3. offset calculation is wrong, lvl 88 and 78 contain values. The offset for level 88 should be the same as the var before (in this case test03), lvl 78 have no offset.

**Comment by ColinDuquesnoy** [comment]
> no possibility to "unsort"

Does sorting even makes sense?

> offset calculation is wrong, lvl 88 and 78 contain values. The offset for level 88 should be the same as the var before (in this case test03), lvl 78 have no offset.

Thank you, I missed those.

**Comment by GitMensch** [comment]
> Does sorting even make sense?
No. So 2/3 already fixed with disabling it.

**Comment by ColinDuquesnoy** [comment]
Should be good now, is it?

![capture](https://cloud.githubusercontent.com/assets/1681217/10028572/7e2449c2-616d-11e5-99fe-56d4de57c27b.PNG)

**Comment by GitMensch** [comment]
> Should be good now, is it?
Much better but the offset for the 88s are wrong, they must inherit the value of it's parent, in this case test03 (--> all 88s in this sample must have offset 1).
And to be correct all level 1 must have offset 1, too

I suggest to check this sample, too:

~~~~cobol
       78 someconst VALUE 'test'.
       01 test01.
          03 test03 PIC X(03).
             88 test-empty VALUE SPACES.
             88 test-a     VALUE "a".
             88 test-b     VALUE "b".
             88 test-c     VALUE "c".
          03 test03-2 PIC X(03).
       78 someconst2 VALUE 'test2'.
       01 test2.
          03 test2-01 PIC X.
          03 test2-03 PIC X(03).
             88 test-empty VALUE SPACES.
             88 test-a     VALUE "a".
             88 test-b     VALUE "b".
             88 test-c     VALUE "c".
          03 test2-03-red redefines test2-03.
            05 test2-03-02 PIC X(02).
               88 test2-03-02-set VALUE 'XX'.
            05 test2-03-03 PIC X(01).
               88 test2-03-03-empty VALUE SPACE.
~~~~~

expected results (same as your sample, but):

* test01 with offset 1
* 88s of test03 with offset 1
* test03-2 with offset 4
* someconst2 without offset
* test2, test2-01 with offset 1
* test2-03 and its 88s with offset 2
* test2-03-red, test2-03-02 and its 88 with offset 2
* test2-03-03 and its 88 with offset 4

**Comment by ColinDuquesnoy** [comment]
Alright, should be good now:

![screenshot_20150923_182900](https://cloud.githubusercontent.com/assets/1681217/10051382/729281b4-6221-11e5-8f16-ded1dd670425.png)

**Comment by GitMensch** [comment]
Yes, works fine. So this can be closed and I can open the enhancement request :-)

**Comment by GitMensch** [comment]
Hey, I found another problem with the offset calculator that needs a fix and would be a good addition to the testsuite:

~~~~~cobol
       01  PIC-X10.
           05 FILLER                   PIC X(2).
           05 PIC-X8                   PIC X(8).
~~~~~

The part "PIC-" from PIC-X8 is omitted.

**Comment by GitMensch** [comment]
Hey, I found another problem with the offset calculator that needs a fix and would be a good addition to the testsuite:

~~~~~cobol
       01  PIC-X10.
           05 FILLER                   PIC X(2).
           05 PIC-X8                   PIC X(8).
~~~~~

The part "PIC-" from PIC-X8 is omitted.

I think I've mentioned earlier that some parts cannot be viewed in the calculator, for example

~~~~~cobol
       01  Buffer                      PIC X ANY LENGTH.
       01  Buffer-Len                  USAGE BINARY-LONG.
~~~~~

**Comment by ColinDuquesnoy** [comment]
> The part "PIC-" from PIC-X8 is omitted.

This is already fixed in git, I added a test.

> ```01  Right-Nibble         COMP-5 PIC 9(1).``` is not viewable

Now it works, I added a test

The index error occur if you selected blank lines, it is now fixed too.

>   ```01  Buffer                      PIC X ANY LENGTH.```

What offset do you expect? 

> ```01  Buffer-Len                  USAGE BINARY-LONG.```

This is not supported at all in the parser, I'll add that to pyQode/pyQode#41

**Comment by GitMensch** [comment]
> > 01 Buffer PIC X ANY LENGTH.
> What offset do you expect? 

I'd expect offset 1 for all lvl 01 and lvl 77 items. BTW: ANY LENGTH is only allowed on lvl 01 or 77.
