### ISSUE TITLE
[Enhancement] add buttons "preferences" and "about" to welcome screen

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#212]
I'd suggest to add them below the recent file list, centered as New+Open are.

**Comment by ColinDuquesnoy** [comment]
You mean something like this?

![this](https://raw.githubusercontent.com/HackEdit/hackedit/master/docs/_static/welcome_window.png)

**Comment by GitMensch** [comment]
Yes, something like this, but add "about" (as this is where you get the log from ;-). OCIDE has the label "preferences" instead of "configure", it should be the same label in both.

I'm looking forward to HackEdit Beta :-)

**Comment by ColinDuquesnoy** [comment]
Done. Here is how it looks (KDE plasma 5):

![screenshot_20160113_200210](https://cloud.githubusercontent.com/assets/1681217/12304595/9b4ceb32-ba30-11e5-9ef4-242aea4bd976.png)

**Comment by GitMensch** [comment]
Nice :-)
