### ISSUE TITLE
[Enhancement] make Offset Calculator work if called from code parts and navigation pane, too

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#213]
Currently the offset calculator only works if used in definition parts of the code.
It would be useful to be able to use it in code parts, too. 

With the definition

``` ::cobol
       01  Output-Detail.
           05 OD-Addr.
              10 OD-Addr-Hex           OCCURS 8 TIMES PIC X.
           05 FILLER                   PIC X(1).
           05 OD-Byte                  PIC Z(3)9.
           05 FILLER                   PIC X(1).
           05 OD-Hex                   OCCURS 16 TIMES.
              10 OD-Hex-1              PIC X.
              10 OD-Hex-2              PIC X.
              10 FILLER                PIC X.
           05 OD-ASCII                 OCCURS 16 TIMES
                                       PIC X.
```

and the use of the calculator at "OD-Hex-1" (if possible even if the cursor is at "e")

``` ::cobol
               MOVE Hex-Digit (Left-Nibble)
                 TO OD-Hex-1 (Output-Sub)
```

the calculator could show the complete 01 level [or 77 if the variable itself is a lvl77 item] and have the line with OD-Hex-1 marked.

The same functionality would be nice if it would be available from the navigation pane (which has currently no context menu).

**Comment by ColinDuquesnoy** [comment]
Good idea. I think I need to finish pyQode/pyQode#41 before I can work on this.
