### ISSUE TITLE
[Documentation] needs an update

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#214]
Minor issue: launchpad has no repository configured: https://launchpad.net/cobcide/4.0 "No revision control details recorded for OpenCobolIDE 4.0 series. ", please add the repository link there if possible.

The 4.x series has the following description:

>Rewrite of the application and move cobol editor to pyqode.cobol
>The default ui will be the same as in 2.x (with menu bar and toolbars) but with the possiblity to switch to the v3.0 ui by double clicking an editor tab

Sounds misleading :-)

For the rest I reference the online docs at http://opencobolide.readthedocs.org/en/latest/

* "OpenCobol/Gnu Cobol" --> "OpenCOBOL / GnuCOBOL" (the spelling is likely the same on other pages, too)
* Instructions on where and how to install **pyQode**
* http://opencobolide.readthedocs.org/en/latest/whats_new.html#id6 has 4.6.1 as a group item (see left) for the older versions. BTW: having group items for 4.5, 4.6, ... sounds good
* the preferences window changed in the last versions - and it may be a good idea to add a screenshot of the compiler pane from a Windows system
* FAQ: OCIDE works fine with Windows 10, too :-)

**Comment by ColinDuquesnoy** [comment]
> Minor issue: launchpad has no repository configured: https://launchpad.net/cobcide/4.0 "No revision control details recorded for OpenCobolIDE 4.0 series. ", please add the repository link there if possible.

This is intentional. I could import the git branch from github but that would potentially bring confusion for people who want to contribute.

> Instructions on where and how to install pyQode 

Why? Regular users don't need to know how to install pyQode as this is handled automatically by pip when you install OCIDE.

> the spelling is likely the same on other pages, too

Only for links, because of the back-quotes surrounding the link name (which my regex search missed). 

Thanks for all the other remarks! I'll fix them during next week-end.

**Comment by GitMensch** [comment]
>> Instructions on where and how to install pyQode

> Why? Regular users don't need to know how to install pyQode as this is handled automatically by pip when you install OCIDE.

This is exactly what I've thought - the sentence above is quoted from the docs :-)

**Comment by ColinDuquesnoy** [comment]
> This is exactly what I've thought - the sentence above is quoted from the docs :-)

Good catch! You have eagle eyes :-)

**Comment by ColinDuquesnoy** [comment]
> Sounds misleading :-)

What sounds misleading? v4.x use the UI of v2.x by default but one can switch to the v3.0 ui by double clicking an editor tab.

> and it may be a good idea to add a screenshot of the compiler pane from a Windows system

Such screenshot already [exists](http://opencobolide.readthedocs.org/en/latest/advanced.html#setup-a-custom-compiler-on-windows)

I think have taken care of all the other points.

**Comment by ColinDuquesnoy** [comment]
If you see anything else just comment on this issue and I will reopen. 

Also, readthedocs and github are tighly integrated together. It's easy to make documentation changes and submit those as a pull request. Everything can be done right from within your browser. Just click on the "Edit on github" link when you're on a documentation page on readthedocs.ogr. This will open the .rst document here on github. If you click on the edit button, github will automatically fork the repository for you and you'll be able to make a pull request once you've committed your changes.

**Comment by GitMensch** [comment]
4.7 has the correct vcvarsall.bat instead of vcvars32.bat, will need an update once 4.7 is considered stable.

For the release NEWS "new way to handle msvc based compilers ..."  I'd highly suggest to add "(including 64-bit support)".

**Comment by ColinDuquesnoy** [comment]
- Screenshots need to updated.
- new settings have to be described
- I also have to talk about the log files.

**Comment by ColinDuquesnoy** [comment]
@GitMensch A release candidate is now [available](https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7.0.rc1).

I'll work on the documentation during this weekend.

**Comment by ColinDuquesnoy** [comment]
Documentation has been updated.

**Comment by GitMensch** [comment]
Yay, I found another one: http://opencobolide.readthedocs.io/en/latest/settings.html#compiler-settings has "GnuCobol" ;-)
