### ISSUE TITLE
[Bug?] Compiler path check does not include PATH setting.

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#216]
I've just placed ``cobc.exe`` into Compiler path and set it's path ``C:\GnuCOBOL\bin`` into PATH variable. Then I've clicked on "Check compiler" leading to the following result:

~~~~~
---------------------------
Invalid compiler path
---------------------------
Not a valid compiler path, path does not exists: cobc.exe!
---------------------------
OK   
---------------------------
~~~~~

I've set the PATH as it's needed for using cobcrun.exe and libcob.dll, is it really necessary to have to set the full path (in this case) ``C:\GnuCOBOL\bin\cobc.exe``? If changed: keep in mind that the environment setting may include multiple directories, separated with ";" on win and ":" on GNU/Linux.

## System information

- OpenCobolIDE: 4.6.6
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Yes. Since #183 I added a check to see if the full compiler path exists, but I should also check if [shutil.which](https://docs.python.org/3/library/shutil.html#shutil.which) does not return ``None`` (that functions uses the PATH environment variable when searching for a program).

**Comment by ColinDuquesnoy** [comment]
This should be working fine now (even if you setup your environment variables in a bach or using the system environment variables dialog).

**Comment by GitMensch** [comment]
It doesn't work, checked with 4.7 pre3. The compiler itself is started but Windows complains about missing dlls - which are in one of the directories in the PATH setting. Please reopen.

**Comment by ColinDuquesnoy** [comment]
Please post the full output log; it works for me.

**Comment by GitMensch** [comment]
No, I cannot as OCIDE doesn't want to start any more... Is there an option like Mozilla's ´´--safe-mode´´ ignoring all settings (and explicit ask at program exit if settings should be saved back)?

Could help if "someone" completely ... the configuration ;-)

For your tests:
* Windows 64bit
* OCIDE 4.7 pre 3 installed (including GC 1.1 MinGW package)
* GC 2 dev unpacked somewhere (let's say D:\dev\GnuCOBOL)
* create a directory ``D:\dev\GnuCOBOL\lib`` and move all ``*.dll`` from ``D:\dev\GnuCOBOL\bin`` to ``D:\dev\GnuCOBOL\lib``

Set compiler path to ``D:\dev\GnuCOBOL\bin\cobc.exe`` and PATH to ``D:\dev\GnuCOBOL\bin;D:\dev\GnuCOBOL\lib``.

Then click on "Compiler Check", this should reproduce Test 1.
Then change the compiler path to ``cobc.exe`` this should reproduce Test 2.

**Comment by ColinDuquesnoy** [comment]
Ah right. Thank you for the details. I'll try this evening or maybe tomorrow.

**Comment by ColinDuquesnoy** [comment]
> No, I cannot as OCIDE doesn't want to start any more... Is there an option like Mozilla's ´´--safe-mode´´ ignoring all settings (and explicit ask at program exit if settings should be saved back)?
Could help if "someone" completely ... the configuration ;-)

No that does not exists at the moment. But I don't get why it does not start at all, you should be able to at least see the home page, do a right click on an empty area to bring the application context menu and click on restore factory defaults. I could add a --restore-factory-default command line options to do that without starting the GUI.

**Comment by ColinDuquesnoy** [comment]
Should be fixed now. Multiple issues were involved:

- first the PATH string was not splitted correctly, this explains the results you get with Test 1.
- as you guessed in #250, some settings were reset to their default values when something was wrong (but not the GUI, only the value used by the check compiler call). This explains the results you got in test 2.

I made the test you suggested, just with the bundled compiler but that shouldn't make a difference isn't it?

I'll upload a new preview build. If you still have a problem, post the verbose log output.
