### ISSUE TITLE
[Bug] Filepath in window title and filename in editor tab don't change after SAVE-AS

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#217]
## Steps to reproduce
* create a file a.cob, store it in folder_a
* use save-as and store it is folder_b\b.cob

## Result
* the file is stored as folder_b\b.cob, the application uses this file
* window title shows folder_a\a.cob
* editor tab shows a.cob

## System information

- OpenCobolIDE: 4.6.6
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Yes I know, I actually fixed that issue in pyqode.core (dev branch) during the last weekend (commit pyQode/pyqode.core@9f13e786530f691e71708c025d21bd1fb1fc0b27 and pyQode/pyqode.core@9d8538e8d878e9167e876d7bfa494c14187438ff)

**Comment by GitMensch** [comment]
Editor tab works now, but the window title is still not changed with 4.7-pre1.

**Comment by ColinDuquesnoy** [comment]
> Editor tab works now, but the window title is still not changed with 4.7-pre1.

I forget the window title, should be fixed now.
