### ISSUE TITLE
[Enhancement] disable Compile button if filetype is not associated

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#218]
Currently you get

~~~~~
---------------------------
Cannot compile file
---------------------------
Cannot compile file: 'TEST.CPY'.

Reason: Invalid extension
---------------------------
OK   
---------------------------
~~~~~

I'm not sure if ".cpy" is part of the standard extensions or not - I simply wanted to disable the compilation option as there is no reason for most people to try to compile a copybook.

On the other hand it's quite useful to have syntax errors shown when editing a copybook, too (for example a wrong picture definition). This may need a different option "file types that are compilable" and "additional file types that are checked".

Thoughts?

**Comment by ColinDuquesnoy** [comment]
Well I think we need to make the distinction between editor associations and compiler associations. I suggest to add an option "Associated extensions" to the editor tab.

**Comment by GitMensch** [comment]
Sounds good, I'm prepared for testing this ;-)

**Comment by ColinDuquesnoy** [comment]
This is quite some work to backport this into OCIDE. AFAIK this works fine in HE. I am not going to backport this one.
