### ISSUE TITLE
[Bug] [Unhandled exception] OSError

### ISSUE THREAD

**Issue by axtens** [OpenCobolIDE/OpenCobolIDE#219]
## Steps to reproduce

Tried to run exe in a terminal

## Traceback

```
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 257, in _on_compilation_finished
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 377, in _run
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 334, in _run_in_external_terminal
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child

OSError: [WinError 87] The parameter is incorrect
```

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 2.0.20140821
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. But I cannot reproduce this bug on my system (tried on Windows 10). 

May I ask you to paste here the application output log after you've tried to run the program? (?->About->Log)

I am looking for a line similar to this one:

```INFO::open_cobol_ide.controllers.cobol::running program in external terminal: C:\Program Files (x86)\OpenCobolIDE\pyqode-console.exe D:\Documents\OpenCobolIDE\test\testfiles\bin\HelloWorld.exe```

**Comment by ColinDuquesnoy** [comment]
And does the program work when normally when started outside of the IDE?

**Comment by axtens** [comment]
C:\Program Files (x86)\OpenCobolIDE\pyqode-console.exe
works normally.

Have caused the error to occur again and have logged but with a bit more
information.

**Comment by ColinDuquesnoy** [comment]
Does it happen with a simple hello world or is it specific to the example you showed in #220?

**Comment by ColinDuquesnoy** [comment]
I tested the program you posted in #220. I don't have the OSError you have.

![capture](https://cloud.githubusercontent.com/assets/1681217/10433365/90914c28-7111-11e5-9bba-bc7ae9dad6d8.PNG)

>  have logged but with a bit more information.

I don't see the log. Attachements made with your mail client don't show up on github. You need to come on the github issue and attach your file by dragging them in the comment box.

**Comment by GitMensch** [comment]
I can't reproduce the issue. Tested with (likely) the same compiler version, placed in it's standard directory ``C:\GNU Cobol 2.0 bin``, in preferences only set compiler path to ``C:/GNU Cobol 2.0/bin/cobc.exe`` and PATH to ``C:/GNU Cobol 2.0/bin`` together with the sources provided in #220.

Without the additional environment the result is

> com.cob: 18: libcob: Cannot find module 'GetVersion'

with both environment entries set the result is

> 0498139398
006
001
18446744073709551537
029

BTW: ``set COB_LIBRARY_PATH=C:\windows\system32`` works fine for me, too [the OS uses the 32bit versions in syswow64 automatically] and is preferable in this case

@axtens Does this still occur (if yes, please add the output of the log) or can this issue be closed?
