### ISSUE TITLE
Add ability to run a program that requires to set some environment variables

### ISSUE THREAD

**Issue by axtens** [OpenCobolIDE/OpenCobolIDE#220]
## Steps to reproduce

``` cobol
       identification division.
       program-id. com.
       data division.
      *>
       working-storage section.
      *>******************************************
       01    VERSION    USAGE BINARY-INT UNSIGNED.
       01    VERSIOM REDEFINES VERSION.
           03    B1    USAGE BINARY-CHAR UNSIGNED.
           03    B2    USAGE BINARY-CHAR UNSIGNED.
           03    B3    USAGE BINARY-CHAR UNSIGNED.
           03    B4    USAGE BINARY-CHAR UNSIGNED.
      *>
       procedure division.
        0000-start section.
        0001-start.
      *>
           call stdcall "GetVersion" returning VERSION.
           display VERSION.
           DISPLAY B1.
           DISPLAY B2.
           DISPLAY B3.
           DISPLAY B4.

           stop run.
      *>
```

Specified to run in terminal. Compile/Run.

EXE requires the following to be set 

  set COB_PRE_LOAD=ole32;kernel32
  set COB_LIBRARY_PATH=C:\windows\syswow64

However, I can't see where to specify these in the setup.

PLEASE NOTE: D:\Documents is not a folder on my computer!
 
## Traceback

```
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 257, in _on_compilation_finished
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 377, in _run
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\cobol.py", line 334, in _run_in_external_terminal
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child

OSError: [WinError 87] The parameter is incorrect
```

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 2.0.20140821
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQ

**Comment by ColinDuquesnoy** [comment]
> However, I can't see where to specify these in the setup.

Indeed, at the moment there is now way to specify additional environment variable. I suggest you to start OCIDE from a batch that sets those environment variables and see if it works better. In a future release I will add a way to specify environment variables that must be set for running a program.

> PLEASE NOTE: D:\Documents is not a folder on my computer!

Those are my development directories. This happen because the python app is frozen (i.e. this is perfectly normal).

**Comment by ColinDuquesnoy** [comment]
Looks like the batch idea works for me as a temporary solution.

Batch (next to OpenCobolIDE.exe):

``` cmd
set COB_PRE_LOAD=ole32;kernel32
set COB_LIBRARY_PATH=C:\windows\syswow64
OpenCobolIDE.exe
```

Results:

![capture](https://cloud.githubusercontent.com/assets/1681217/10433451/2e6919c6-7112-11e5-91b3-8e08c0cd165c.PNG)

**Comment by GitMensch** [comment]
I can't reproduce the issue. Tested with (likely) the same compiler version, placed in it's standard directory ``C:\GNU Cobol 2.0 bin``, in preferences only set compiler path to ``C:/GNU Cobol 2.0/bin/cobc.exe`` and PATH to ``C:/GNU Cobol 2.0/bin``.

Without the additional environment the result is

> com.cob: 18: libcob: Cannot find module 'GetVersion'

with both environment entries set the result is

> 0498139398
006
001
18446744073709551537
029

BTW: ``set COB_LIBRARY_PATH=C:\windows\system32`` works fine for me, too [the OS uses the 32bit versions in syswow64 automatically] and is preferable in this case

@axtens Does this still occur or can this issue be closed?

**Comment by ColinDuquesnoy** [comment]
I've implemented this feature. 

You can configure the environment in the "Run" tab of the preferences:

![runenv](https://cloud.githubusercontent.com/assets/1681217/12378434/a13d6dae-bd3d-11e5-9609-99a44239cbc7.PNG)

Results:

![runenvresults](https://cloud.githubusercontent.com/assets/1681217/12378437/aed6601a-bd3d-11e5-94d7-04d112e534a1.png)


You can expect a release candidate next weekend.

**Comment by GitMensch** [comment]
Nice. As a hint to users with (recent) GnuCOBOL 2.x: set ``COB_RUNTIME_CONFIG`` (see the documentation or conf/runtime.cfg) and you have all settings you need in one place - both for use with and without OCIDE. Use multiple configuration files (one "master" and the others only setting necessary "special" flags and ``include master.cfg``) and you have a different set of runtime configurations by just one change in OCIDE :-)
@ColinDuquesnoy Could be worth a hint in the documentation.

**Comment by ColinDuquesnoy** [comment]
Thanks for the hint! I'll read the docs about COB_RUNTIME_CONFIG and will update ocide documentation accordingly when working on #214.
