### ISSUE TITLE
[Bug] Using quotes in extra compiler flags does not work

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#222]
I've added ``-I "D:\my test"`` to extra compiler flags. While the compilation does show the correct compiler string (the blue string during compilation) the actual used one does not work as the quotes are prefixed with ``\``.

Compilation shows:

> ``C:\Users\Simon\AppData\Local\Temp\cobc_wrapper.bat -x -o C:\dev\testsp.exe -std=default -debug -I "D:\my test" testsp.cob``

Details of resulting error shows

> ~~~~
C:\dev>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"  1>NUL 

> C:\dev>call "d:/GnuCOBOL 2.0/bin/cobc.exe" -x -o C:\dev\testsp.exe -std=default -debug -I \"D:\my test\"  testsp.cob 
cobc: test": No such file or directory
~~~~~


## System information


- OpenCobolIDE: 4.6.6
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Yes, bug. Thank you!

**Comment by ColinDuquesnoy** [comment]
Should be working better now.

**Comment by GitMensch** [comment]
The line ``shlex.split(string, posix=not windows)`` looks a little bit strange. Did you test the new version on both GNU/Linux and Windows if paths with spaces (and surrounding quotes) work (if possible in all fields that are possible to enter)?

**Comment by ColinDuquesnoy** [comment]
I haven't had the time to test it on linux yet but I tested it on Windows in all fields where a space was used to separate arguments.

I'll have a look on linux this evening.

**Comment by ColinDuquesnoy** [comment]
You were right, it didn't worked on GNU/Linux. It is now fixed.

For reference, I tested it on Linux with GnuCOBOL 2.0 r411 and on Windows with OpenCOBOL 1.1 (kiska build) and GNU Cobol 2.0.20140821.

**Comment by ColinDuquesnoy** [comment]
But I've just seen that it doesn't work with a MinGW build (e.g. the bundled compiler).

Here is the output:
```
D:\Documents\OpenCobolIDE\GnuCOBOL-Win32-MinGW\bin\cobc.exe -x -o D:\Documents\OpenCobolIDE\test\testfiles\bin\HelloWorld.exe -std=default -debug -I "D:\A path with some spaces" HelloWorld.cbl
gcc: error: path: No such file or directory
gcc: error: with: No such file or directory
gcc: error: some: No such file or directory
gcc: error: spaces: No such file or directory
```
Should I reopen? (though I am not sure it is caused by OCIDE, looks like a MinGW bug).

**Comment by GitMensch** [comment]
Not reopen but document - this is a mingw specific issue.
What may work is passing ``-I /d/A\ path\ with\ some\ spaces`` or ``-I "/d/A\ path\ with\ some\ spaces"`` instead, you may want to check this (mainly for documentation purposes).

**Comment by ColinDuquesnoy** [comment]
Ok, then I will take care of this in #214
