### ISSUE TITLE
Allow drag & drop for pasting paths to preferences

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#224]
As a follow up of #166, it would be nice to allow the user to drop a file/directory in one of the line edits used for compiler paths/environment variables, that would insert the file/folder 's path into the widget.

We could also add file system auto-completion (a popup that complete the path while you're typing). Qt provides builtin solutions for that.

**Comment by GitMensch** [comment]
Both sound nice. Let's see if autocompletion still works when using environment variables (for example "%USERPROFILE%\") [not a must, just a nice-to-have-feature].

**Comment by ColinDuquesnoy** [comment]
>  Let's see if autocompletion still works when using environment variables

I'm afraid this won't work with the builtin file system completer. Maybe we can do something about it but not my top priority.
