### ISSUE TITLE
[Packaging] Outdated PPA + missing dependencies

### ISSUE THREAD

**Issue by arcanjoebc1971** [OpenCobolIDE/OpenCobolIDE#225]
I'm using Ubuntu 15.04 64 bits. See errors messages:

everaldo@positivo:~/Downloads$ sudo opencobolide
Traceback (most recent call last):
  File "/usr/bin/opencobolide", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: qdarkstyle>=1.11
everaldo@positivo:~/Downloads$ opencobolide
Traceback (most recent call last):
  File "/usr/bin/opencobolide", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: qdarkstyle>=1.11
everaldo@positivo:~/Downloads$

**Comment by ColinDuquesnoy** [comment]
How did you install it? Using the ppa or pip? Please, post the exact command you've used.

**Comment by arcanjoebc1971** [comment]
I am using ppa, how it's shows in the site from project, ok!

Em 17/10/2015 04:11, Colin Duquesnoy escreveu:

**Comment by ColinDuquesnoy** [comment]
OK thanks. The ppa is a bit outdated (I haven't run ubuntu for a long time). I 'll try to update it for v4.7.

In the meantime you can install using pip:

``` 
sudo pip3 install OpenCobolIDE --upgrade
```

This should fix your issues.

**Comment by arcanjoebc1971** [comment]
The command indicate fail, see below the result:

everaldo@positivo:~$ sudo pip3 install OpenCobolIDE --upgrade
[sudo] password for everaldo:
sudo: pip3: command not found


Em 17/10/2015 08:42, Colin Duquesnoy escreveu:

**Comment by arcanjoebc1971** [comment]
I tryed the command below:

everaldo@positivo:~$ sudo apt-get install python3-opencobolide --upgrade
Lendo listas de pacotes... Pronto
Construindo árvore de dependências
Lendo informação de estado... Pronto
python3-opencobolide já é a versão mais nova.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 
13 não atualizados.
everaldo@positivo:~$

But how you see isn't giving right, ok!


Em 17/10/2015 08:42, Colin Duquesnoy escreveu:

**Comment by ColinDuquesnoy** [comment]
> pip3: command not found

You don't have pip3 on your system, just install it with ``sudo apt-get install python3-pip`` and try again.

> sudo apt-get install python3-opencobolide --upgrade

Yes the ppa is outdated and miss the qdarkstyle dependency. Don't try this command again until I've updated the PPA (probably not before I release v4.7)

**Comment by arcanjoebc1971** [comment]
Now it's ok! Thank you for help me with Operation System Ubuntu Linux  
15.04 64 bits ...

Em 17/10/2015 09:22, Colin Duquesnoy escreveu:

**Comment by ColinDuquesnoy** [comment]
Great! Thank you for reporting the PPA issue. I'll update the readme with a warning about it.

**Comment by ColinDuquesnoy** [comment]
I don't maintain a PPA anymore but I now provide a standalone debian package available both on the download page on launchpad and on the release page on github.
