### ISSUE TITLE
[Bug] [Unhandled exception] UnicodeDecodeError

### ISSUE THREAD

**Issue by arcanjoebc1971** [OpenCobolIDE/OpenCobolIDE#233]
## Steps to reproduce

PLEASE DESCRIBE THE CONTEXT OF THIS BUG AND THE STEPS TO REPRODUCE!

## Traceback

```
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\controllers\edit.py", line 199, in _current_changed
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\view\editors\cobol.py", line 64, in file_type
  File "D:\Documents\OpenCobolIDE\open_cobol_ide\compilers.py", line 64, in get_file_type
  File "c:\python\32-bit\3.4\lib\encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 662: character maps to <undefined>
```

## System information

- OpenCobolIDE: 4.7.dev1
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Please, describe the context of this issue and possibly the steps to 
reproduce!

Did this error happened when you opened a new file?

Can you attach the file that triggered the error (attach it here on 
github, not using your mail client).

**Comment by arcanjoebc1971** [comment]
I have a file call relat-3.cbl and it's a print file to a archive TXT. When I open it already 
![error-01](https://cloud.githubusercontent.com/assets/6251076/10622605/706c1ed0-7767-11e5-8b84-209639a6981f.jpg)
![error-02](https://cloud.githubusercontent.com/assets/6251076/10622606/706d33b0-7767-11e5-9dcc-cc6a0b36d241.jpg)

shows errors

**Comment by ColinDuquesnoy** [comment]
I'll fix the error you see in the first screenshot.

About the second screenshot, this is documented 
[here](http://opencobolide.readthedocs.org/en/latest/faq.html#opencobolide-failed-to-open-a-file-due-to-an-encoding-issue-what-can-i-do). 
You need to tell the IDE what encoding to use to load the file (btw the 
error in screenshot 1 will likely goes away once you've chosen the 
right encoding).
