### ISSUE TITLE
OpenCobolIDE not finding gnu-cobol

### ISSUE THREAD

**Issue by PaoloRicardo** [OpenCobolIDE/OpenCobolIDE#234]
I have succeeded in installing GnuCOBOL.

I have reinstalled opencobolide. When I launch the IDE I get a message 'COBOL compiler not found'.. Ignoring this and loading the IDE, under Edit->Preferences->Compiler I have the Compiler Path correctly set as /usr/local/bin/cobc and pressing 'Check compiler' it gives 'cobc (GNU Cobol) 2.0.0 ..." etc.

However when I try 'Check compilation' it gives 'Compiler check failed: Exit code 1 Output configuration error /usr/local/config/default.conf: No such file or directory'

I don't have a /usr/local/config directory on my PC. I do have a /usr/local/share/gnu-cobol/default.conf. How do I correct the error

Paul

**Comment by ColinDuquesnoy** [comment]
In the compiler preferences, I'd try to enable the COB_CONFIG_DIR 
checkbox and set the value to /usr/local/share/gnu-cobol.

**Comment by PaoloRicardo** [comment]
Colin: sorry that should have read /usr/local/share/gnu-cobol/config. Putting this into the COB_CONFIG_DIR solves the problem,

Thanks
