### ISSUE TITLE
dbpre v0.4 copy book filename have changed

### ISSUE THREAD

**Issue by vbcoen** [OpenCobolIDE/OpenCobolIDE#235]
Ide looks for PGCTBBATWS but this has changed to PGCTBPARAM

Latest copy books are:
PGCTBBAT
PGCTBPARAM
PGCTBSUB
PGCTBSUBWS
SQLCA

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting. I'll fix that in v4.7.

**Comment by ColinDuquesnoy** [comment]
Fixed in master branch.
