### ISSUE TITLE
[Bug] WITH NO ADVANCING not properly interpreted by console

### ISSUE THREAD

**Issue by lillian27** [OpenCobolIDE/OpenCobolIDE#236]
Given:
DISPLAY "Enter name - " WITH NO ADVANCING
ACCEPT Name
DISPLAY "Name is " Name

The first DISPLAY is shown as a blank line.  If a value is entered and Return/Enter pressed, "Enter name -" is then shown followed by "Name is " and whatever the user entered.   The same executable run from bash prints to the screen in proper order.

If WITH NO ADVANCING is removed the code behaves as expected.

## System information

- OpenCobolIDE: 4.6.5
- GnuCOBOL: OpenCOBOL 1.1.0
- Python: 3.4.3 (64bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting!

The builtin console is pretty dumb, all it does is read the process' stdout and let you write to the process' s stdout.

If you need more advanced features such ``WITH NO ADVANCING`` or if you use the SCREEN SECTION, you need to [enable run in external terminal](http://opencobolide.readthedocs.org/en/latest/settings.html#run-settings).
