### ISSUE TITLE
 Bug   Unhandled exception  FileExistsError

### ISSUE THREAD

**Issue by PaoloRicardo** [OpenCobolIDE/OpenCobolIDE#246]
## Steps to reproduce 

PLEASE DESCRIBE THE CONTEXT OF THIS BUG AND THE STEPS TO REPRODUCE! 

## Traceback

```
File  D:\Documents\OpenCobolIDE\open_cobol_ide controllers file.py , line 97, 
in save_current_file  d:\DOCUMENTs\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py , line 970, 
in save_current  File  d:\DOCUMENTs\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py , line 873, 
in save_widget  File  d:\DOCUMENTs\pyqode\core\managers\file.py , line 398, 
in save FileExistsError:  WinError 183  Cannot create a file when that file already exists:  C:\MFCOBOL\demo\NESTED.CBL~  ->  C:\MFCOBOL\demo\NESTED.CBL    
```

## System information:
- OpenCobolIDE: 4.6.6 
- GnuCOBOL: GNU Cobol 1.1.0 
- Python: 3.4.3  32bits  
- Qt: 5.5.0 - PyQt: 5.5 
- pyqode.core: 2.6.9 
- pyqode.cobol: 2.6.4 
- pyqode.qt: 2.7.dev0 
- pygments: 2.0.2 
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting but please mention the steps to reproduce. Saving the current editor is not enough for me to reproduce the bug.

When we save a file, we first save it to ``ORIGINAL_FILENAME~``, if the save was successfull we remove ``ORIGINAL_FILENAME`` and rename ``ORIGINAL_FILENAME~`` to ``ORIGINAL_FILENAME``.

Here, it seems that the removal of ``ORIGINAL_FILENAME`` failed because of an OSError (possibly a permission error) than the rename failed because destination already exists. Is it possible that another application keep a handle to NEST.cbl. E.g. when the bug happen, are you able to rename the file in the windows explorer?

**Comment by PaoloRicardo** [comment]
Colin: not quite sure what happened. I was trying to save a file using 
the file icon on the IDE and found it didn't seem to work so I pressed 
it a few times and then I went to File->Save which was when the IDE 
crashed. Anyway I've loaded the IDE again and since then  it's been 
fine. Probably a combination of trigger-happy digits on my part. It was 
the Windows version by the way. I haven't had any problems with the 
Linux version.

Paul Richards

On 01/11/15 8:52 PM, Colin Duquesnoy wrote:
>
> Thank you for reporting but please mention the steps to reproduce. 
> Saving the current editor is not enough for me to reproduce the bug.
>
> When we save a file, we first save it to |ORIGINAL_FILENAME~|, if the 
> save was successfull we remove |ORIGINAL_FILENAME| and rename 
> |ORIGINAL_FILENAME~| to |ORIGINAL_FILENAME|.
>
> Here, it seems that the removal of |ORIGINAL_FILENAME| failed because 
> of an OSError (possibly a permission error) than the rename failed 
> because destination already exists. Is it possible that another 
> application keep a handle to NEST.cbl. E.g. when the bug happen, are 
> you able to rename the file in the windows explorer?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenCobolIDE/OpenCobolIDE/issues/246#issuecomment-152813748>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ColinDuquesnoy** [comment]
> Probably a combination of trigger-happy digits on my part.

Well the IDE should resists to those trigger-happy digits. I'll improve error handling on save and presents you with a warning message box if the save failed with the exact error.

**Comment by ColinDuquesnoy** [comment]
I've made some improvements to the error handling. You can try them by testing the latest preview build: https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.7-preview3

Next time this occur you will have the real error (probably a permission error). If that happens open a new issue.
