### ISSUE TITLE
[Enhancement] Add option to write log to file and command line options for logging

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#251]
It would be nice to have OCIDE store the log to current TEMP/TMP/. as OCIDE-pid.log (necessary if opened multiple times). Maybe write a function that appends existing logs without file log (which would be set for all current active instances) to OCIDE.log.

It is likely a good idea to do this only if explicit activated via about->log (new checkbox).
Together with this option a button "clear logs" from the gui would be nice.

For the rare issues where it is not possible to even open the part to activate/deactive the function a set of command line options ``--enable-log-file``, ``--disable-log-file``, ``--enable-log-verbose``, ``--disable-log-verbose`` would be nice.

**Comment by ColinDuquesnoy** [comment]
OCIDE already log to a file ("~/OpenCobolIDE/cache/OpenCobolIDE.log" on Windows, "~/.cache/.OpenCobolIDE/OpenCobolIDE.log" on GNU/Linux and "~/Library/Caches/OpenCobolIDE/OpenCobolIDE.log" on OSX).

Adding '-pid.log' suffix and the ability to clear logs sound nice.

I should also document this.

There is a --verbose flag but it only impacts the current session (i.e. it does not change the verbose log check box state permanently).

**Comment by GitMensch** [comment]
Nice. For people not knowing ``~``: on Windows it translates to ``%USERPROFILE%``. In general: Adding the Documentation label seems appropriate.

**Comment by ColinDuquesnoy** [comment]
I added a RotatingFileLogger and a button to clear logs. Each log record now also include a date time information and the pid of the log record author. The file is open in append mode.
