### ISSUE TITLE
[Bug] Compiler settings are saved for "Check compiler" and not restored on Cancel

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#255]
Topic: Preferences->Compiler

Ideally the button "Compiler check" works without storing the current configuration. If this is not possible the old configuration has to be loaded to memory and restored after Compiler check is finished.

scene:
- a working compiler is set up
- test another compiler configuration
- see it doesnt work
- "of course" pressing "Cancel"
- the old working one is currently lost

## System information

- OpenCobolIDE: 4.7.dev58
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Fixed in commit 156ab02c4d9b0b65d6198a8a14005e2ba4e66dc3
