### ISSUE TITLE
[Bug] Preferences -> Compiler: Standard configuration is not complete

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#256]
Current version has an additional "acu" configuration, soon there will be an additional "cobol2014" one.
Ideally OCIDE would pull this information from ``cobc --help`` or look inside ``COB_CONFIG_DIR``(for all *.conf) to get this list.

## System information

- OpenCobolIDE: 4.7.dev58
- GnuCOBOL: GNU Cobol 2.0.20151025
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
This is already tracked in #182 ;)

**Comment by GitMensch** [comment]
Ah, 4 months since creating the other one ;-)

> Anyway since the new version will show this info, I think I'll wait it is widely available to do config parsing, in the meanwhile I'll just add a "None" and "acu" to the combo box.

What about doing this part directly? It cannot harm to add a cobol2014 already - if it's not there the compiler will complain and the user will reset this. It would be a good idea to pass the selected -std during compiler test [Startup/Check Compiler] (did not checked if you do this already).

**Comment by ColinDuquesnoy** [comment]
> What about doing this part directly?

It will be in v4.7 (and it's already in HackEdit).

For your information, I plan to release HackEdit in couple of **days**. There won't be a new preview build for OCIDE, next release will be v4.7 final.

**Comment by GitMensch** [comment]
OK, please drop a note here :-)
