### ISSUE TITLE
[Bug] [Unhandled exception] UnicodeEncodeError

### ISSUE THREAD

**Issue by fermat39** [OpenCobolIDE/OpenCobolIDE#257]
## Steps to reproduce

PLEASE DESCRIBE THE CONTEXT OF THIS BUG AND THE STEPS TO REPRODUCE!

## Traceback

```
  File "/Users/Colin/Documents/OpenCobolIDE/open_cobol_ide/controllers/edit.py", line 228, in _update_status_bar_labels
  File "/Users/Colin/Documents/OpenCobolIDE/open_cobol_ide/controllers/edit.py", line 218, in _get_cursor_pos_in_bytes

UnicodeEncodeError: 'ascii' codec can't encode character '\u3141' in position 0: ordinal not in range(128)
```

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (64bits)
- Qt: 5.4.2
- PyQt: 5.4.2
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.6.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting but can you please describe the context of this 
issue and the steps to reproduce?
