### ISSUE TITLE
HackEdit 1.0 Alpha 1 has been released

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#260]
The first public **alpha** version of [HackEdit](https://github.com/HackEdit/hackedit) has been released on [PyPi](https://pypi.python.org/pypi/hackedit/1.0a1).

HackEdit is meant to be the successor of OpenCobolIDE. At the moment, there  is no documentation and no installers. All those will come with future releases.

You can install it with pip:

```
pip3 install hackedit hackedit-cobol
```

Read the full install instruction specific to your platform in the [readme](https://github.com/HackEdit/hackedit#installation). Report any issues you encounter on the [hackedit issue tracker](https://github.com/HackEdit/hackedit/issues). You can also discuss about HackEdit on [Gitter](https://gitter.im/HackEdit/hackedit).

Regarding OpenCobolIDE's future. There will be a new version soon with many new features. Afterwards, OCIDE will enter in maintainance (bug fixes only or of new features introduced in pyqode.cobol). It will be maintained untill HackEdit 1.0 final is ready.

cc @GitMensch, @Astalaseven, @Bofinken, @martyheyman

**Comment by GitMensch** [comment]
Just to sound stupid... ;-)

Is this error message by design?

````
D:\Programme\Entwicklung\Python\Scripts>pip3 install hackedit hackedit-cobol
Collecting hackedit
  Downloading hackedit-1.0a1.tar.gz (11.8MB)
    100% |################################| 11.8MB 35kB/s
Collecting hackedit-cobol
  Downloading hackedit_cobol-1.0a1-py3-none-any.whl (83kB)
    100% |################################| 86kB 1.3MB/s
Building wheels for collected packages: hackedit
  Running setup.py bdist_wheel for hackedit
  Complete output from command d:\programme\entwicklung\python\python.exe -c "import setuptools;__file__='C:\\Users\\Simon\\AppData\\Local\\Temp\\pip-build-0w0rbcls\\hackedit\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\Simon\AppData\Local\Temp\tmpaw_qmor0pip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Simon\AppData\Local\Temp\pip-build-0w0rbcls\hackedit\setup.py", line 67, in <module>
      raise RuntimeError("This setup.py does not support wheels")
  RuntimeError: This setup.py does not support wheels

  ----------------------------------------
  Failed building wheel for hackedit
Failed to build hackedit
Installing collected packages: hackedit, hackedit-cobol
  Running setup.py install for hackedit
Successfully installed hackedit-1.0a1 hackedit-cobol-1.0a1
````

**Comment by ColinDuquesnoy** [comment]
> Is this error message by design?

Well...yeah...sort of. I will remove it once I have debian packages. wheels do not install fine on debian (icons and desktop files end up in /usr/local/share instead of /usr/share). This is a workaround for people running on debian with pip >= 7.0, see https://bitbucket.org/pypa/wheel/issues/92. BTW this is also in OCIDE: https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/setup.py#L53
