### ISSUE TITLE
[Enhancement] Area B margins on column 12 and 72

### ISSUE THREAD

**Issue by datt-neelabh** [OpenCobolIDE/OpenCobolIDE#261]
Area A and area B should also be seperated by line just as area A beginning is marked by a red line. Please make a line on column 12 and on column 72 to mark the beginning and end of area B. All info on page 3 on link: http://www.b-u.ac.in/sde_book/bca_cobol.pdf 

Please make it. It will be a great help for the beginners.

**Comment by ColinDuquesnoy** [comment]
This looks useful. But wouldn't it better to use a slightly different color to make the distinction between the two areas?

There is already a margin on column 72, so we would just need to add one at column 12 and maybe another at column 80? And what if free format is used? Should we just keep the one at column 80 (or let the user change it).

@GitMensch Any thoughts on this?

**Comment by datt-neelabh** [comment]
Yeah. It should be implemented.

**Comment by GitMensch** [comment]
Margins help, especially for newcomers. I personally like margins that can be tweaked by the user. Something like a setting

Margin 1: 7
Margin 2: 12
Margin 3: 73
Margin 4: 80

If set to  "0" the margin is disabled (not shown).
Different dialects use other margins than the standard ones (you can setup GnuCOBOL in this way, too) where "hard" margins don't help (and the margin for column 12 wouldn't be necessary for COBOL2002+ as you can code in column 8 and start sections in column 12 [the way GnuCOBOL handles this, too - nonetheless I'd recommend to "code like COBOL85" concerning the margins]). This is the reason why I won't use the caption "Area A, B, ...".

Despite of the optical adjustment this could have an edit purpose - and be useful for "oldtimers", too.
On [CTRL]+[TAB] you could position to the next margin set, with [SHIFT]+[CTRL]+[TAB] position to the previous margin (ending in column 1).

**Comment by ColinDuquesnoy** [comment]
Thank you Simon!

The 4 margins mode will be implemented in pyqode.cobol 2.8 and a settings to control the margins position should be added in OCIDE 4.7x and HE as soon as the feature is ready.

> Despite of the optical adjustment this could have an edit purpose - and be useful for "oldtimers", too.
On [CTRL]+[TAB] you could position to the next margin set, with [SHIFT]+[CTRL]+[TAB] position to the previous margin (ending in column 1).

That's pretty neat! I'll take this into consideration for the new design of the COBOL margins mode ;-)

**Comment by ColinDuquesnoy** [comment]
@GitMensch One last question: does it make sense to have more than 4 margins and let the user add some more?

**Comment by GitMensch** [comment]
> Does it make sense to have more than 4 margins and let the user add some more?

For COBOL itself definitely not. May help for some local "coding standards" but I haven't seen any request for more than 4 margins in any other editor since years.

**Comment by ColinDuquesnoy** [comment]
> but I haven't seen any request for more than 4 margins in any other editor since years.

I see. Good to know. Thanks for your input!

**Comment by ColinDuquesnoy** [comment]
Implemented in master branch.

User can configure margin position and colors:

![screenshot_20160119_204809](https://cloud.githubusercontent.com/assets/1681217/12430960/fe957864-bef2-11e5-84a8-8afe88b4a2e7.png)

To quickly navigate between the margins, you can use ``Ctrl+Alt+Right`` or  ``Ctrl+Alt+Left`` (``Ctrl+Tab`` and ``Shift+Ctrl+Tab`` are now used to cycle through the editor tabs).
