### ISSUE TITLE
Offset Calculator with signed numeric, wrong offset

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#262]
S9(16) is 17 bytes long.

        01 RDMS-TABLE-LO120-HANDEL.
          05 LO120-HANLOGGID     PIC S9(16)
             SIGN LEADING SEPARATE VALUE 0.
          05 LO120-HANTYP         PIC X(20).
          05 LO120-UTSKLOGGSTATUS     PIC S9(6)
             SIGN LEADING SEPARATE VALUE 0.
          05 LO120-DETALJTYP      PIC X(20).
          05 LO120-IDTYP          PIC X(15).
          05 LO120-TIMESTAMP      PIC S9(16)
             SIGN LEADING SEPARATE VALUE 0.
          05 LO120-OBJEKTID       PIC S9(16)
             SIGN LEADING SEPARATE VALUE 0.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch (will be available in v4.7)
