### ISSUE TITLE
Some Suggested Enhancements

### ISSUE THREAD

**Issue by eugeniodilo** [OpenCobolIDE/OpenCobolIDE#265]
Enhancements: 
1. with a double click on "COPY XXXXXX " in source code it will open the COPY File in a new TAB.
2. with a right click on "COPY XXXXXX " in source code it display a tooltip or a window visualizing the  COPY source.
3. with a right click on a COBOL reserved word it display a tooltip or a window with Syntax Help of that reserved word 
4. Insert a Link in the main menu to the OpenCobol Programmers Guide.
5. with a right click on a User defined Variable in Procedure Division it display a tooltip or a window with its definition.

**Comment by ColinDuquesnoy** [comment]
This looks like some interesting ideas.

> 1. with a double click on "COPY XXXXXX " in source code it will open the COPY File in a new TAB.

This one is already tracked in #140. You already opened #247 and #248. I know you want this feature. No need to request it every months. I will implement it but at the moment my time is pretty limited so please be patient.

> 2. with a right click on "COPY XXXXXX " in source code it display a tooltip or a window visualizing the COPY source.

I feel like this one can already be done with #140. Once you've open the copybook in a tab you can split to have it side by side with your current editor.

> 3. with a right click on a COBOL reserved word it display a tooltip or a window with Syntax Help of that reserved word 

Maybe in HackEdit but where do I find the syntax help? Is there a service that I could use of should I store the syntax help for each reserved keywords myself?

> 4. Insert a Link in the main menu to the OpenCobol Programmers Guide.

Good idea. I'll add a new entry to the help menu. This will be in the next version.

> 5. with a right click on a User defined Variable in Procedure Division it display a tooltip or a window with its definition

I would use a mouse hover event (the cursor stay at least one second on top of a user variable). This will be done in pyqode.cobol and will be available in OCIDE 4.7.x.

**Comment by GitMensch** [comment]
>> with a right click on a COBOL reserved word it display a tooltip or a window with Syntax Help of that reserved word

> Maybe in HackEdit but where do I find the syntax help? Is there a service that I could use of should I store the syntax help for each reserved keywords myself?

A service has some issues, namely

* requires internet connection
* needs internet traffic
* may be tracked at different places
* if the service is down (or the url moved) the functionality is broken

Therefore I'd like to have the service as opt-in, only available for getting the most current version.
I posted a request for the service at https://sourceforge.net/p/open-cobol/discussion/contrib/thread/c67ea739/?page=1, in the meanwhile you could work on the offline mode: grab http://open-cobol.sourceforge.net/faq/index.html and extract all divs with ``id=section``, for example ``<div class="section" id="accept">`` which has the description for ``ACCEPT`` statement. Ideally you can do this as a packaging step which would allow for regular updates.
If you add this functionality to pyqode.cobol you should be able to integrate it into OCIDE 4.7, too :-)

**Comment by eugeniodilo** [comment]
*Maybe in HackEdit but where do I find the syntax help? Is there a service that I could use of should I store the syntax help for each reserved keywords myself?*

Answer: you should put Gary's manuals in the distribution package. After that you can display the right page from Gary's manual depending on the compiler's release. Ex. for reserved word INSPECT, you can display page  386  (chapter 6.17.24. INSPECT) froma maual GnuCOBOL 2.1 23NOV2013 Programmers Guide (A4).pdf
