### ISSUE TITLE
[BUG] IDE show error for existing statements

### ISSUE THREAD

**Issue by MatthAddax** [OpenCobolIDE/OpenCobolIDE#267]
Hi,
I recently started to use this IDE for COBOL but I've a problem. It doesn't recognize var name when they are used before they are created. For example while using indexed files, here's is my code and where the errors are : 

                                                                                                                                                
```cobol
environment division.
      *========================================
       input-output section.
      *----------------------------------------
       file-control.
      *****************************************
           select FiSpectacle assign "../Fichiers/SPECTACLE.IND"
               organization is indexed access mode is dynamic
               record key is codeSpect
               record key is titre
               record key is dateRepresentation
               file status is fs-fiSpectacle.
       configuration section.
      *----------------------------------------
       data division.
      *========================================
       file section.
      *----------------------------------------
       FD FiSpectacle.
       01 EnregSpectacle.
           02 codeSpect.
               03 codeGenre                pic x(5).
               03 codeNum                  pic 9(2).
           02 titre                        pic x(30).
           02 numSalle                     pic 9(2).
           02 dateRepresentation           pic 9(4).
           02 tabReservationsCategories    pic 9(9).
           02 nbReservations               pic 9(3) OCCURS 3
               REDEFINES  tabReservationsCategories.
```

The bold values are where the errors are, it says : codeSpect undifined, titre undifined, etc
![capture](https://cloud.githubusercontent.com/assets/12526135/11625359/be731af0-9cda-11e5-9233-b77ad4f9ea8b.PNG)

Can anyone help me to fix it? It's important I need it for school.

Thanks for your help :+1: 

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
This is not a bug, you have a syntax error in your file (I am not going to tell you where because we're not here to make your homeworks). By removing **one line**, I get your example to compile....

**Comment by MatthAddax** [comment]
Seriously, really sorry my teacher didn't find the error so (as this code did work with Visual Cobol)

I'll look up for this so,

Sorry again, so, keep up the good work :D

**Comment by ColinDuquesnoy** [comment]
I'll give you a hint then: the configuration section is misplaced. The syntax for the environment division is as follow (order matters):

```cobol
ENVIRONMENT DIVISION.
configuration-section.
input-output-section.
```

I guess the visual cobol compiler is more relaxed than the GnuCOBOL compiler. You might want to try using another standard (Preferences > Compiler > Standard, e.g. use "mf" instead of "default")

**Comment by MatthAddax** [comment]
Yeah thanks, that was the problem. Thanks a lot and sorry for disturbing, can you just tell me what's the change (for the compiler) you just made me do?

**Comment by ColinDuquesnoy** [comment]
See http://opencobol.add1tocobol.com/gnucobol/#what-are-the-official-cobol-standards

**Comment by ColinDuquesnoy** [comment]
and http://opencobol.add1tocobol.com/gnucobol/#how-complete-is-gnucobol

**Comment by MatthAddax** [comment]
Ok thanks :)
