### ISSUE TITLE
[Bug] gcc.exe no hay disco

### ISSUE THREAD

**Issue by andrewstyle22** [OpenCobolIDE/OpenCobolIDE#269]
---------------------------
gcc.exe - No hay disco
---------------------------
No hay disco en la unidad. Inserte un disco en la unidad \Device\Harddisk1\DR1. 
---------------------------
Cancelar   Reintentar   Continuar   
---------------------------

## System information

- OpenCobolIDE: 4.6.6
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.6.9
- pyqode.cobol: 2.6.4
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Can you describe the context of this issue? (in english)
 If this error happens during compilation, could you please paste the application verbose output log here? (?->About->Log, turn on verbose, restart and paste the log output after the error occurred).

**Comment by andrewstyle22** [comment]
Solved, I had to go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows -> ErrorMode ->rigth click -> modify -> value before 0 after 2.

**Comment by ColinDuquesnoy** [comment]
Good to know you got it working.
