### ISSUE TITLE
[Enhancement] Add column selection/editing

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#280]
Good editors/IDEs have this feature which comes in quite handy from time to time.

I gues the section for delete / copy would not be that hard to implement while "real" editing.
Npp has a nice intro to this features (other editors use the same keys, but many fail with editing in multiple lines), see https://notepad-plus-plus.org/features/column-mode-editing.html.

**Comment by ColinDuquesnoy** [comment]
This is feature is already tracked pyQode/pyQode#2 and pyQode/pyQode#3. I never really found the time to start working on this but this is somehow planned.

Closing as duplicate.

**Comment by GitMensch** [comment]
OK, I've search only this issue tracker here and not pyQode :-)
At least this is a reference for others searching here.

**Comment by ColinDuquesnoy** [comment]
> OK, I've search only this issue tracker here and not pyQode :-)
At least this is a reference for others searching here.

Yes, no problem ;-)
