### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#281]
Hola! @ColinDuquesnoy has created a [ZenHub](http://www.zenhub.io) account for the **OpenCobolIDE** organization. ZenHub is the leading team collaboration and project management solution built for GitHub.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- “+1” button for GitHub issues and comments;
- Drag-and-drop file sharing;
- Time-saving shortcuts like a quick repo switcher.

### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @ColinDuquesnoy._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by ColinDuquesnoy** [comment]
@GitMensch (and other users), you might be interested in the voting system for issues and the agile boards. I am going to use it for HackEdit and pyQode too.

**Comment by GitMensch** [comment]
Unlikely that I personally use this. What happens if :+1: ?

**Comment by ColinDuquesnoy** [comment]
> What happens if :+1: ?
> only displaying an icon

Yes, and everyone watching the project get spammed. The extension does this by adding a +1 badge next to the issue title (same for comments inside an issue). 

![screenshot_20160206_191552](https://cloud.githubusercontent.com/assets/1681217/12868393/11d5c5f2-cd06-11e5-8742-c0e1832995fa.png)


I wish this feature was builtin into github because you cannot vote or see the popularity of an issue without installing the browser extension.

**Comment by ColinDuquesnoy** [comment]
> I wish this feature was builtin into github because you cannot vote or see the popularity of an issue without installing the browser extension.

Now that github support voting for an issue natively (https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) I'll stop using zenhub.
