### ISSUE TITLE
Navigation tree needs line-breaks

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#288]
### Description

The following leads to a working navigtation tree:

``` cobol
       data division.
       working-storage section.
```

while the following does not

``` cobol
       data division. working-storage section.
```

The second sample is perfectly valid since cobol2002.
### System information
- Operating System: Windows
- OpenCobolIDE: 4.7.2
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Related to pyQode/pyQode#41.
