### ISSUE TITLE
Navigation tree: Assume missing headers

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#289]
### Description

The current implementation does not work within copybooks (or programs that have the "important" parser parts within copybooks).

It looks like the navigation tree needs a ``DIVISION`` header, otherwise it only contains "No Data".

Here's my suggestion:

* If "No Data" would be produced check if a section is found instead. If it is ``WORKING-STORAGE``, ``LOCAL-STORAGE``, ``LINKAGE``, ``REPORT`` or ``SCREEN`` assume ``DATA DIVISION``, otherwise assume ``PROCEDURE DIVISION``.
* If no section is found check if you see a possible level number (first word is a numeric word without a dot following), if yes: assume ``DATA DIVISION`` and ``WORKING-STORAGE SECTION``.

This would fix the Navigation tree in most use-cases (the current "copybook problem" occurs likely with much production code).

**Comment by ColinDuquesnoy** [comment]
Related to pyQode/pyQode#41.

**Comment by GitMensch** [comment]
OK. Sounds like the referenced issue should get a nice priority with the stuff that's in already ;-)

**Comment by ColinDuquesnoy** [comment]
> OK. Sounds like the referenced issue should get a nice priority with the stuff that's in already ;-)

Yes but I have other priorities:

1. fix the indexing issue in HE (this is what I am working on for the moment)
2. work on pyqode 3.0 (must be ready before I release HE beta)
3. work on HE beta (the python debugger is my top priority and it will take some time...)

**Comment by GitMensch** [comment]
Sounds good, too. the indexing issue in He and the broken outline because of missing headers are the two main reasons that I can't try to rollout HE to my colleagues.

What is to be expected for pycode 3.0?

**Comment by ColinDuquesnoy** [comment]
> What is to be expected for pycode 3.0?

Mainly:

- a big cleanup: remove deprecated stuff and improve public API to have a better defined interface for the code editor (especially needed when one wants to add an editor widget to the hackedit tab widget that does not work with the text API, e.g. an image viewer).
- simplify packaging and improve flexibility by getting rid of the namespace packages
- code snippets completion/expansion (e.g. you type "ifthen" + TAB -> the following code is inserted and the cursor will move between the various $ fields using TAB: 

```cobol
IF $1-CONDITION THEN
   $2-STATEMENTS
ELSE
   $3-STATEMENTS
END-IF.
```
- get rid of socket communication with the backend by writing to the process stdin and by reading its stdout and make sure we don't run untrusted code
- there are also a few features I'd like to experiment with (e.g. make the editor widget fully configurable using json, a progressive highlighter (using a timer to progressively highlight big files)).

**Comment by GitMensch** [comment]
I know you wanted to do this later.
But as it is a "main issue" for some devs that there would be not outline any more when switching to the otherwise liked OCIDE I wanted to re-ask if you could try to add the "simple" variant to assume the headers if missing for the upcoming release (where nearly all milestones are finished).

Is this possible?
In any case: thank you for the good work you did (OCIDE is the main download source for GnuCOBOL on Win systems).

**Comment by ColinDuquesnoy** [comment]
It might be complicated with the current parser but I'll have a look. If I can get it to work before friday evening it will be in, otherwise it will be for another release (with all the tasks related to the name parser).

**Comment by GitMensch** [comment]
Thank you. I do my best to make sure OCIDE 4.7.3 will be another big milestone (via testing).

**Comment by ColinDuquesnoy** [comment]
> I do my best to make sure OCIDE 4.7.3 will be another big milestone (via testing).

Thanks, I do appreciate your testing!

**Comment by GitMensch** [comment]
Yay, all 4.7.3 milestones reached. And still 4 hours "before friday" left ;-)
Have fun!

**Comment by ColinDuquesnoy** [comment]
Should be better now:

![screenshot_20160414_221242](https://cloud.githubusercontent.com/assets/1681217/14542197/08139478-028e-11e6-91ec-90cd8fcf538f.png)

**Comment by ColinDuquesnoy** [comment]
New preview build uploaded: https://www.dropbox.com/s/qwxeej3sdklnqld/OpenCobolIDE-4.7.3_Setup.exe?dl=0

If everything is OK, I will release it officially tomorrow.
