### ISSUE TITLE
Split "files with COBOL syntax highlighting" and "associated file extensions for compiler"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#290]
### Description

OCIDE currently provides COBOL syntax highlighting (including navigation tree) for all files that match the "associated file extensions for compiler".

As no one wants to compile a copybook (or other local preparser formats) it would be nice to add a file extension list to the preferences tab "code highlighting".
All files that match one of these would be highlighted and the navigation tree would be used, but only the ones that are in the compiler tab enable background compilation and compile/run buttons.

**Comment by ColinDuquesnoy** [comment]
Yes I know, we already talked about this in #218. It works in hackedit and I won't backport it to ocide.

**Comment by GitMensch** [comment]
You're correct, it's in the other item, too. [Should be the duplicate, not the wontfix label.]
It sounds so easy if it would not be as complex as it is in Hackedit with its multiple syntax highlighters but with a simple "edit/compile" distinction.
If you say it would be a lot of work we have to live without the option. And hope HackEdit will get as nearly production ready for COBOL as OCIDE is.
