### ISSUE TITLE
Add option to disable/lock file system tab by default

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#291]
### Description

The file system tab works like a charm. But it slows down OCIDE if the files you open are on a (mapped) network share.

Once you've opened a file you can either close the File system tab (which would be restored when OCIDE is opened next time) or lock it. But you still have to do it each time you startup OCIDE.

Therefore I'd like to see the option to lock it by default (via preferences) and/or store an attribute for file system and navigation tab "open/closed" and only restore it on startup if it wasn't closed on last exit.

**Comment by ColinDuquesnoy** [comment]
I'll store the state of the lock button in QSettings when closing the application and will restore the state on application startup.

**Comment by ColinDuquesnoy** [comment]
Just a note: OCIDE already remembers the state of the locked button (in ``lock_fs_path``). I just have to store the visibility of the dock widgets.
