### ISSUE TITLE
Clear Logs doesn't seem to work

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#292]
### Description

Steps to reproduce:

1 Open About->Logs
--> Log is shown

2 Click "Clear logs" --> the message
~~~~
---------------------------
Logs cleared
---------------------------
Log files have been cleared.
---------------------------
OK   
---------------------------
~~~~
is shown and the log is empty

3 Open About->Logs
--> Log is shown again ???

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.2
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Works for me here on Linux. I guess there is a permission error when removing the current log file on Windows. Forcing a roll over should solve this issue on Windows.

**Comment by GitMensch** [comment]
Did you found the time already to check if your guess is correct?

**Comment by ColinDuquesnoy** [comment]
No, not yet (unlilkely that wil have the time before 1-2 weeks).

**Comment by ColinDuquesnoy** [comment]
Should be ok now (solution tested in HackEdit, I'll recheck that with OCIDE on Windows asap).

**Comment by GitMensch** [comment]
Just a thought: shouldn't ``clear_logs`` return a value (if it doesn't do it already) and the following ``QtWidgets.QMessageBox.information`` should use this to not display "everything fine" when the log has the additional entry "failed to remove log file"?

BTW: if you progress that fast I'd be able to test 4.7.3 during the next week (don't hurry, I just thought "wow - very quick").

**Comment by ColinDuquesnoy** [comment]
> Just a thought: shouldn't clear_logs return a value (if it doesn't do it already) and the following QtWidgets.QMessageBox.information should use this to not display "everything fine" when the log has the additional entry "failed to remove log file"?

Yep sounds better indeed. A warning message box will now appear if the function failed to remove a log file (even an old log file that does not get shown in the about box).

>  if you progress that fast I'd be able to test 4.7.3 during the next week (don't hurry, I just thought "wow - very quick").

Well, I'd like to finish OCIDE this week-end so that I can start working on pyqode 3.0 (I am going to leave my current job in july. Since I've used pyqode in a few internal tools there, I'd like pyqode 3.0 to be ready before I leave, at least the big changes I plan for the public API).
