### ISSUE TITLE
Setup DB2 Express C on Windows

### ISSUE THREAD

**Issue by askadian** [OpenCobolIDE/OpenCobolIDE#298]
I have **OpenCOBOL IDE** installed on my Windows 8.1 PC + I have **DB2 Express C** also.
**Objective**: To write an **OpenCOBOL+DB2** Program and run it on **Windows 8.1**
OpenCOBOL Program '_cblsql2.sqb_'.
I did a **precompile** using DB2 Express C API and I got two files: '_cblsql2.cbl_' and '_cblsql2.bnd_'.
The 'cblsql2.cbl' is what I opened in OpenCOBOL IDE and did a compile. Compilation is successful and an 'cblsql2.exe' got created in my app's ~\bin directory.
Also, did a bind of 'cblsql2.bnd'. and was able to see the same getting in SYSIBM Tables.
Now when I click on run in OpenCOBOL IDE, I am getting the following:
*F:\COBOL\cbl\bin\cblsql2.exe 
cblsql2.cbl:93: libcob: Cannot find module 'sqlgstrt'
Process finished with exit code 1*

I tried the following options in OpenCOBOL IDE ==> (x) means box checked and ( ) means box unchecked
Edit -> Prefrences -> Compiler
Compiler Path:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe
(x)PATH:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin
(x)COB_CONFIG_DIR:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\config
(x)COB_COPY_DIR:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\copy
(x)COB_INCLUDE_PATH:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\include
(x)COB_LIB_PATH:- C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\lib
(x)Auto-detect and compiler submodules
VCVARS Path:- ___
Output directory:- bin
Associated extentions:- .cob;.pco;.lst;.cbl;.cpy
Standard:- default 
Free Format:- ( )
Compiler Flags: ( ) -static (x) -debug (x) -g
( ) -ftrace ( ) -ftraceall (x) -fdebugging-line
Copybook paths:- C:\Program Files\IBM\SQLLIB\include\cobol_a
Library paths:- C:\Program Files\IBM\SQLLIB\lib\ -->this directory contains 'db2api.lib'
Libraries:- 
Extra compiler flags:- **
But still getting the same error while execution: "Cannot find module 'sqlgstrt'"

**Comment by ColinDuquesnoy** [comment]
I have no experience with DB2 Express C. At first glance, it looks like you don't link with ``db2api.lib``. Either add ``db2api`` to  *Libraries* or ``-ldb2api`` to *Extra compiler flags* and report back.

**Comment by askadian** [comment]
Hi,
Thanks for your help on the issue.

I tried adding -ldb2api as per your guidelines. I am still getting the same error.

Attached is the screenshot for your reference.

Thanks!!
[Screenshots.pdf](https://github.com/OpenCobolIDE/OpenCobolIDE/files/196234/Screenshots.pdf)
![screenshot_01](https://cloud.githubusercontent.com/assets/8684201/14153922/9379cf36-f6d7-11e5-83a8-345ba32590f9.jpg)
![screenshot_02](https://cloud.githubusercontent.com/assets/8684201/14153937/aab6c136-f6d7-11e5-96c6-49b03b7e9c48.jpg)

**Comment by ColinDuquesnoy** [comment]
Looking at the compiler output, you can see that there is a warning from ld.exe about unhandled machine type. It looks like you're trying to link a 32 bit executable with a 64 bit library. Either install a 32 bit version of the db2api or use a 64 bit compiler. Or maybe you need a msvc based GnuCobol compiler (the default compiler is built with MinGW32).

BTW, are there any reasons for using an outdated version of OpenCobolIDE? (latest is 4.7.2).

**Comment by askadian** [comment]
I added the Win32 library to Library paths: **C:\Program Files\IBM\SQLLIB\lib\Win32**(this contained another db2api.lib, which must be for 32-bit)
and then recompiled. The warning from ld.exe about _unhandled machine type_ is gone. 
The error "**cblsql2.cbl:93: libcob: Cannot find module 'sqlgstrt'**" is still there while executing. It leaves me with option of reinstalling the IDE for 64-bit(I am running Windows 8.1 64 bit). I know of no way to find out which version(32 or 64 bit????) of OpenCOBOLIDE I am running. 
**OpenCOBOL IDE Version**: 4.6.3
**GnuCOBOL**: GNU Cobol 1.1.0
**Qt**: 5.4.1
**PyQt**: 5.4.1
**pycode.core**: 2.6.6
**pycode.cobol**: 2.6.2
**pygments**: 2.0.2
**QDarkStyle**: 2.1.dev0 

I am going to try to reinstall **OpenCOBOL IDE Version 4.7.2 64 Bit Windows**.
[IDE Log.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/196544/IDE.Log.txt)

**Comment by askadian** [comment]
Do we have OpenCOBOL IDE available for Windows 8.1 64 Bit Version 4.7.2 ?? It seems not as I can find only one setup file on launchpad.

**Comment by ColinDuquesnoy** [comment]
> Do we have OpenCOBOL IDE available for Windows 8.1 64 Bit Version 4.7.2 ?? It seems not as I can find only one setup file on launchpad.

There has never been a 64bits version of OCIDE, always 32bits. It will work fine on Windows 8 64 bit.

>  know of no way to find out which version(32 or 64 bit????) of OpenCOBOLIDE I am running. 

Always 32 bits but that doesn't matter. What matters is the compiler (GnuCobol) bitness.

> The warning from ld.exe about unhandled machine type is gone. The error "cblsql2.cbl:93: libcob: Cannot find module 'sqlgstrt'" is still there while executing.

Where is db2api.dll? If it is not in %PATH%, I suggest to either copy the dll next to the executable or add COB_PRE_LOAD setting either in the system environment variables or in the run environment variable (in OCIDE, Preferences -> Run -> Environment variable, this require OCIDE 4.7.x).

**Comment by askadian** [comment]
**Ist Approach**: Setting **COB_PRE_LOAD=db2agapi** in Run Options of the OpenCOBOL IDE solves the issue. We need to copy the '_db2agapi.dll_' into the directory where '_cblsql2.exe_' is present.
**IInd Approach**: Adding **-fstatic-call** to Extra compiler flags also makes the issue go away.

**Comment by ColinDuquesnoy** [comment]
Thank you for your feedback. I guess we can close it.
