### ISSUE TITLE
Allow the issue to be send by [CTRL]+[RETURN]

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#302]
Many text boxes (like this on on GitHub) use [RETURN] for adding a line break and [CTRL]+[RETURN] for sending the form. It would be nice to have this tiny feature in QCrash.

**Comment by GitMensch** [comment]
Maybe catch the [TAB] event in the textarea, too (and send it to the form, giving the possibility to switch between the controls). If you are currently in the title and use [TAB] you get to the textarea and can not leave it without using the mouse.
The same applies for [SHIFT]+[TAB] which gets you backward from the checkboxes - but only until you reach the textarea.

Is there another control available which doesn't "eat" [TAB] but still allows [RETURN] to add a line break?

**Comment by ColinDuquesnoy** [comment]
Sound good.

> Is there another control available which doesn't "eat" [TAB] but still allows [RETURN] to add a line break?

Looks like I can set [QPlainTextEdit::setTabChangeFocus](http://doc.qt.io/qt-5/qplaintextedit.html#tabChangesFocus-prop) to True: tab would change focus instead of indenting the text and return would still add a line break.
