### ISSUE TITLE
GUI-Issues with the Review dialog

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#303]
* no icon
* a help function (question mark in the upper right) is available but cannot be used anywhere

**Comment by ColinDuquesnoy** [comment]
> no icon

Windows specific issue. On Linux it uses an icon from the current icon theme, on OSX the window has the OCIDE icon. I'll have a look.

> a help function (question mark in the upper right) is available but cannot be used anywhere

I'll remove it. (no windows specific though).

**Comment by ColinDuquesnoy** [comment]
Should be fixed in latest QCrash.
