### ISSUE TITLE
The navigation pane does not always use free format when the editor does

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#304]
### Description

It seems like this only happens on startup, see logs and attached screenshot.

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev13
- GnuCOBOL: cobc (GnuCOBOL) 2.0.20151025
- Python: 3.4.3 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.1.3
- QDarkStyle: 2.1

Application log: https://gist.github.com/1422c1be09e96938b892c47f94e75311
![free-file-fixed-navigation-pane](https://cloud.githubusercontent.com/assets/6699539/14440813/fc60ce9c-0031-11e6-851f-7d792589314a.PNG)

**Comment by GitMensch** [comment]
The change broke the free format:

* open OCIDE
* make sure to not use free format in preferences
* restart OCIDE

--> free format is enabled again (should have been stored and restored)

BTW: did we discussed the request "be able to set fixed/free format per file (use preferences setting only for the default [if reference format cannot be assumed - and for new files])" already?

**Comment by ColinDuquesnoy** [comment]
> free format is enabled again (should have been stored and restored)

I can't reproduce that and I actually made sure fixed format was working before uploading the build (tested on windows with the latest installer).

**Comment by ColinDuquesnoy** [comment]
> did we discussed the request "be able to set fixed/free format per file (use preferences setting only for the default [if reference format cannot be assumed - and for new files])" already?

Implemented in HE not planned in OCIDE.

**Comment by GitMensch** [comment]
> I can't reproduce that and I actually made sure fixed format was working before uploading the build (tested on windows with the latest installer).

I'm using dev16 (local build). fixed format does work but I'm quite sure it was saved before and this setting is now back to free format on every restart (reproducable).
Do you need logs?

**Comment by ColinDuquesnoy** [comment]
> I'm using dev16 (local build). fixed format does work but I'm quite sure it was saved before and this setting is now back to free format on every restart (reproducable).

Strange, I haven't changed anything regarding the storage of the setting. All changes were made in pyqode.cobol...

> Do you need logs?

If you can reproduce consistently, yes I would need the logs.

**Comment by ColinDuquesnoy** [comment]
> BTW: did we discussed the request "be able to set fixed/free format per file (use preferences setting only for the default [if reference format cannot be assumed - and for new files])" already?

In the end, I added a checkbox that let you quickly switch between fixed and free format. This toggle the global free format setting.

![screenshot_20160419_231806](https://cloud.githubusercontent.com/assets/1681217/14655923/fdd65f72-0684-11e6-8494-aa28b5935794.png)

**Comment by GitMensch** [comment]
Sounds like a reasonable and user-friendly work-around for OCIDE.

BTW: You did have seen the strange data-type names in the navigation pane, do you? Lot's of `pic` in there...

**Comment by ColinDuquesnoy** [comment]
> BTW: You did have seen the strange data-type names in the navigation pane, do you? Lot's of pic in there...

I missed them, I was too focused on the folding panel ;-) 

These are anonymous pictures:

```cobol
10  pic x(316)  value "  Usage:     
```

I guess the best would be to discard them (don't show them at all in the navigation panel).

**Comment by GitMensch** [comment]
It is the same as filler. If you show them (which I guess) I suggest to transform the "name" pic to "FILLER".

Whatever way you choose: they must be shown in the offset table.

**Comment by ColinDuquesnoy** [comment]
Alright, should be good now.

One last question: I noticed level 88 are not shown in the navigation pane. It seems to be done on purpose but I don't remember why. Is it correct or should they be shown?

**Comment by GitMensch** [comment]
You'll like get different opinions from different developers in this point.
I'd personally like them to be in (as sub-items to the "real" data items)

**Comment by ColinDuquesnoy** [comment]
Thanks. Sounds like it needs an option. I'll leave it that way for now but feel free to open an issue if you want them to be in.

**Comment by GitMensch** [comment]
I did as requested but recognized with 4.7.3.dev24 the following (which I'd assume as a bug):

* level 88 items don't show up in code completion
* level 88 items cannot be jumped to (via [CTRL])

If they need to be in navigation pane for this to work: please add them (if someone doesn't want to see their 85x 88 items below a single variable in navigation pane [this is a real world sample (!)] they still can collapse them in navigation pane).

**Comment by ColinDuquesnoy** [comment]
Agreed. It will be on by default for now and I'll add an option later.
