### ISSUE TITLE
Run in external terminal does not set key values correctly

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#305]
### Description

I've tested this with no entry in Preferences->Compiler->PATH
--> got the expected "libcob.dll missing"
--> ProcessExplorer shows that the PATH setting has only the value in that were set after running vcvarsall

Added the correct path to Preferences->Run->Values
--> still got the same message
--> ProcessExplorer shows that the PATH setting is identical to the last test

Added the correct path to Preferences->Compiler->PATH and the option enabled
--> Process can be started
--> ProcessExplorer shows that the PATH setting is identical to the last test but has the setting prefixed

This is at least confusing (add the entry to the Compiler setting and the Run works) and has the bug that Preferences->Run->Values is not applied (or not after using the vcvars values)

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev13
- GnuCOBOL: cobc (GnuCOBOL) 2.0.20151025
- Python: 3.4.3 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.1.3
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Thanks for reporting, I'll have a look.

**Comment by ColinDuquesnoy** [comment]
I can reproduce the issue. What happens here is that I always set environ['PATH '] based on the result of GnuCobolCompiler.setup_process_environment() even if you defined PATH in Preferences->Run (any other environment variable will be applied correctly). Now I've changed the implementation to use the compiler PATH only if you did not defined PATH in Preferences->Run. If you do, you're responsible for setting up a correct complete PATH (including any additional paths).
