### ISSUE TITLE
Error outline sometimes occurs on multiple lines, linter parser doesn't work sometimes

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#307]
I've reduced a missed error (only shown in compilation tab) to the minimum.

This sample source

~~~~cobol
      *
      *
       ; COPY TCOP.
      *
      ;COPY SOME.
~~~~

leads to 

![missederr](https://cloud.githubusercontent.com/assets/6699539/14492706/6fa664fc-0181-11e6-8eb0-a3eb3fe700ac.PNG)

--> the first error is shown in three lines [please fix this first as it likely doesn't occur any more after fixing the linter parser]
--> only the first error is shown in error outline

If you use "compile" you get only one error in the issues tab (the first one).

~~~~
Error   TEST.COB   3    TCOP: No such file or directory
~~~~

The compiler tab has both errors:

~~~~
D:\GnuCOBOL\GnuCOBOL 2.0\bin\cobc.exe -o ..\tmp\TEST.dll -std=default -debug TEST.COB
TEST.COB (5): Error: Invalid indicator ';' at column 7
TEST.COB (3): Error: TCOP: No such file or directory
~~~~

If I place a `*` in line 3 column seven there are no errors outlined, using compile the issue tab has the following error in (line was not found):

~~~~
Error   TEST.COB   -   TEST.COB (5): Error: Invalid indicator ';' at column 7
~~~~

For the first error the log has

~~~~
PYQODEDEBUGCOMM::pyqode.backend::linter raw output: TEST.1460548316.COB (3): Error: TCOP: No such file or directory
PYQODEDEBUGCOMM::pyqode.backend::linter parsed output: [(' TCOP: No such file or directory', 2, 2, 0, None, None, 'C:\\Users\\Simon\\AppData\\Local\\Temp\\TEST.1460548316.COB'), (' syntax error, unexpected Identifier or Literal, expecting .', 2, 2, 0, None, None, 'C:\\Users\\Simon\\AppData\\Local\\Temp\\TEST.1460548316.COB')
~~~~

and for the second one:

~~~~
PYQODEDEBUGCOMM::pyqode.backend::linter raw output: TEST.1460548329.COB (5): Error: Invalid indicator ';' at column 7
PYQODEDEBUGCOMM::pyqode.backend::linter parsed output: [
PYQODEDEBUGCOMM::pyqode.backend::
~~~~

**Comment by ColinDuquesnoy** [comment]
> the first error is shown in three lines [please fix this first as it likely doesn't occur any more after fixing the linter parser]

I can't reproduce that (here on Ubuntu with open-cobol package). Will try on windows later. I can reproduce all the other issues (I think there is still some improvements to do on the output parser regex).

**Comment by GitMensch** [comment]
> > the first error is shown in three lines [please fix this first as it likely doesn't occur any more after fixing the linter parser]

> I can't reproduce that (here on Ubuntu with open-cobol package). Will try on windows later. I can reproduce all the other issues (I think there is still some improvements to do on the output parser regex).

I can only reproduce the issue with the windows installer, the dev version doesn't have this issue...

**Comment by ColinDuquesnoy** [comment]
> I can only reproduce the issue with the windows installer, the dev version doesn't have this issue...

Actually I can reproduce this even with the dev version on Linux. It happens when you insert a line break on a line where you have an extra selection that spans the whole line. I am now using another way to select a whole line that does not cause this issue.

**Comment by ColinDuquesnoy** [comment]
The other issue should be fixed too (I added a unit test).
