### ISSUE TITLE
OpenCOBOL IDE: How to resolve SQLCODE -805 in DB2 Express C, Windows 8.1, GnuCOBOL

### ISSUE THREAD

**Issue by askadian** [OpenCobolIDE/OpenCobolIDE#309]
I am trying to work with **OpenCOBOL IDE** and **DB2 Express-C**. A very simple program **TEST0002.sqb**(attached) is **prep**'ed and **bind**'ed with DB2 creating - **TEST0002.bnd**(attached) and **TEST0002.cbl**(attached) files. Now when I execute the Program in **OpenCOBOL IDE
[TEST0002 - SQB.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/217888/TEST0002.-.SQB.txt)
[Compile & Run.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/217890/Compile.Run.txt)
[OpenCOBOL IDE execution messages.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/217891/OpenCOBOL.IDE.execution.messages.txt)
[TEST0002 BIND FILE INFO.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/217892/TEST0002.BIND.FILE.INFO.txt)
[TEST0002 - cbl.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/217894/TEST0002.-.cbl.txt)

**, I am getting -805. Following messages are displayed: (also attached)

```
F:\COBOL\bin\TEST0002.exe
CONNECT :)+000000000+1ÿ1208ÿAKADIAN
ÿSAMPLEÿQDB2/NT64ÿ2268ÿ2268ÿ0ÿ1252ÿ0ÿ
SQLCODE: -000000805
SQLCAID: SQLCA
SQLCABC: +000000136
SQLERRML: +0036
SQLERRMC: A Øõ( . CÀ[¸õ( 0X00000000604B4100
SQLERRP: SQLRA14D
SQLSTATE: 51002
SQLWARN:
Hello world: 0 -->THIS SHOULD BE 1 IF SQL WORKED :)
--- error report ---
ERROR occurred :

SQLCODE : -000000805
ERR BUFFER :
ERR BUFFER : SQL0805N Package " A Øõ( . CÀ[¸õ( 0X00000000604B4100"
was not found.
SQLSTATE=51002

Package: A Øõ( . CÀ[¸õ( 0X00000000604B4100
001SQL0805N Package " A Øõ( . CÀ[¸õ( 0X00000000604B4100" was not
found.
SQLSTATE=51002

SQLSTATE 51002: The package corresponding to an SQL statement
execution request
was not found.


--- end error report ---****

Process finished with exit code 98
```

**Comment by ColinDuquesnoy** [comment]
Honestly I have no idea. You will probably have a better answer on the GnuCOBOL/DB2 Express-C forums.

I am going to close this issue since this is not related to OCIDE but it would be nice if you could post the solution here in case other users have the same issue.

**Comment by askadian** [comment]
It is infact related to OCIDE. By adding -std=mf in Extra Compiler Flags, the -805 is gone. There is another negative SQLCODE now, but still I am guessing it has something to do with how we compile and run in OCIDE.
I will keep you posted on progress. Link for same issue on GnuCOBOL: https://sourceforge.net/p/open-cobol/discussion/cobol/thread/a54af9f7/

```
F:\COBOL\bin\TEST0002.exe 
CONNECT :)+0000000000+1ÿ1208ÿAKADIAN ÿSAMPLEÿQDB2/NT64ÿ377ÿ377ÿ0ÿ1252ÿ0ÿ                    
SQLCODE: -0000004903
SQLCAID: SQLCA   
SQLCABC: +0000000136
SQLERRML: +00028
SQLERRMC: runtime_pidÿsqlastrt_trusted                                          
SQLERRP: SQLASTRT
SQLSTATE: 42611
SQLWARN:            
Hello world: 0 -->THIS SHOULD BE 1 IF SQL WORKED :)  
--- error report ---
ERROR occurred :                                                                                 
SQLCODE : -0000004903
SQL4903N  The length of parameter "runtime_pid" of function "sqlastrt_trusted" is not valid.  SQLSTATE=42611

SQLSTATE 42611: The column, argument, parameter, or global variable definition is invalid.

--- end error report ---

Process finished with exit code 94
```
Are you aware of any **GnuCOBOL-DB2 ExpressC** Forum?

**Comment by ColinDuquesnoy** [comment]
> It is infact related to OCIDE. By adding -std=mf in Extra Compiler Flags, the -805 is gone.

No, not related to OCIDE. This is related to the compiler and your particular setup (no offense taken).

> Are you aware of any GnuCOBOL-DB2 ExpressC Forum?

Nope what I meant is that you'll have better support on forums related to the particular technology you're using (I meant GnuCOBOL forum or DB2 Express C forum).
