### ISSUE TITLE
Check compiler seems to only check for return code, not for result

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#310]
### Description

I *think* this was different before. I get the "compiler works" message although it doesn't.

snip from the log:

~~~~
09:21:55:937::DEBUG::5220::open_cobol_ide.compilers::output: 'Das System kann den angegebenen Pfad nicht finden.\r\n'
09:21:55:937::DEBUG::5220::open_cobol_ide.compilers::exit code: 0
09:21:55:938::INFO::5220::open_cobol_ide.compilers::GnuCOBOL compiler check: success
09:21:55:938::INFO::5220::open_cobol_ide.compilers::Executable extension: .exe
09:21:55:939::INFO::5220::open_cobol_ide.compilers::Module extension: .dll
~~~~

The first line means "the specified path cannot be found". The reason that the exit code is still zero is because of a wrapper shell that calls the actual cobc command and does not return the error.
The reason that I believe that is a bug is: OCIDE should check if there is an actual compiled result.

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: 
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Yes it used to work before. I guess this is a regression introduce in a previous refactoring. I will have a look.
