### ISSUE TITLE
Feature Request: Don't auto-close Log tab

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#311]
### Description

Which is currently done if you double click on an issue there.
This request is about either keeping it open as the manual close is still possible and you likely want to investigate the other issues the program has, too.

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: cobc (GNU Cobol) 2.0.20151025
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Bug introduced when I worked on #291. Will fix it before I release 4.7.3 final
