### ISSUE TITLE
Feature Request: Add ToDo markers

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#313]
### Description

ToDo markers are often use to mark parts in the code that needs additional work later or mark very special code parts.

It would be nice to have these available in the log pane (new TODO tab).

They are always part of a comment (which is language dependent), How ToDo-markers look like likely differs from programmer to programmer / project rule, therefore it would be good to be able to set the regex for them, maybe even have different types that can be grouped in the tab, but this can come later.

Maybe the feauture already exists in OCIDE and/or HE (in this case: how should the markers look like)?

**Comment by ColinDuquesnoy** [comment]
Feature planned for HackEdit beta (I already added a table for doing this while indexing).

Marker would look like these (after a ``#`` in python and behind a ``*`` or ``*>`` in COBOL):

- todo: my todo task descritpion
- fixme: my todo task description

Closing this issue as won't fix (OCIDE is in maintainance mode).

**Comment by GitMensch** [comment]
OK, I just was curious (and assume the marker is case-insensitive).
Will the following work, too? It's a local rule in the project I'm working on. If not: you could let the user define/change the marker definition in HE.

~~~~cobol
      *  @MSG ToDo: do something
      *  @MSG FIXME remove bug
~~~~

I'm closing the issue ;-)
