### ISSUE TITLE
Only go to definition with [CTRL]+[click], not on [CTRL]+[mouse-down]

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#316]
### Description

I often do a selection and use [CTRL]+[mouse move] to copy the selection to another code part.
The problem here: OCIDE currently goes to the definition of the code part you do the mouse down on, leading to the code to be copied there. I consider this an important bug in current preview release.

This won't happen if OCIDE only goes to the definition on [CTRL]+[click].

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: cobc (GNU Cobol) 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Why using CTRL for selection? It will work fine if you don't hold CTRL.

**Comment by GitMensch** [comment]
[CTRL] is used as [CTRL]+[mouse move] copies the selected text to another place.

**Comment by ColinDuquesnoy** [comment]
I see. So a possible fix is to prevent goto when there is a selection, isn't it?

**Comment by GitMensch** [comment]
This would "prevent" this specific bug but the "solution" would be: use "click", not "mouse down".

**Comment by ColinDuquesnoy** [comment]
I guess you're talking about the mouse release event when you're talking about click. Qt exposes 3 mouse events:

- mouseMoveEvent
- mousePressEvent  -> I am using this one for now, which I assume is what you mean by mouse down
- mouseReleaseEvent

**Comment by GitMensch** [comment]
> mousePressEvent -> I am using this one for now, which I assume is what you mean by mouse down

Your assumption is correct (and the available events a little bit strange, but it would be Qt to blame...)
If you would change this to `mouseReleaseEvent` it could work direcly (not sure if you need to additional check which button was pressed for handling context menu).
