### ISSUE TITLE
Cursor cannot be recognized if "under" a margin

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#317]
### Description

... no matter which colour the margin has.

Is it possible to draw the margin "under" the cursor or change cursor width?

**Comment by ColinDuquesnoy** [comment]
> Is it possible to draw the margin "under" the cursor

That is not possible, I have to draw the margin on top of the text document otherwise it will be hidden by the background (I am not drawing the cursor myself, this is part of the qt test document rendering).

I'll see what can be done in pyqode 3.0.

**Comment by GitMensch** [comment]
Good to know. In the meanwhile: if you don't see your cursor it is likely under a margin :-)

**Comment by ColinDuquesnoy** [comment]
> if you don't see your cursor it is likely under a margin :-)

Yes.

**Comment by ColinDuquesnoy** [comment]
Changing the cursor width from 1px to 2px works well (btw it looks like this is what is done in QtCreator).
