### ISSUE TITLE
Code folding: Not collapsed source is sometimes shown as collapsed

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#318]
### Description

See attached image. Should only happen with collapsed text and sometimes does anyway.

![tt](https://cloud.githubusercontent.com/assets/6699539/14559340/57f40494-0308-11e6-8de6-1b9f42141950.png)

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: cobc (GNU Cobol) 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Hmm, I've never seen that. Steps to reproduce?

**Comment by GitMensch** [comment]
> Steps to reproduce?

As it happens randomly (without actually using the collapse feature !) this will be hard. If I find something I'll post a comment.

**Comment by ColinDuquesnoy** [comment]
This should not happen anymore with the new code folding implementation. I think this is due to incoherent fold levels which are now fixed. Comment if you see that with OCIDE 4.7.4 and I'll reopen.
