### ISSUE TITLE
Feature Request: Search History

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#321]
### Description

OCIDE currently seem to miss this feature, not checked in HE.

Implementation (if done) could be:
- use drop-down box in search/replace panes
- on enter: store terms in search and replace to the preference file
- on key-press [DEL] remove the selected entry from preference file

**Comment by ColinDuquesnoy** [comment]
You're speaking about the editor's builtin search panel, isn't it? (Ctrl+F). This is a pyqode.core feature, so both HE and OCIDE are lacking this useful feature. 

BTW I've decided to take one more day to polish pyqode 2.9 and fix most of the issues you reported today. I'll delay the release of OCIDE a little bit, maybe monday

**Comment by ColinDuquesnoy** [comment]
It turns out to be more complicated than I initially thought. The problem is that the search works on the fly, many intermediate searches might show up in the history. I'll need to take some to find a good solution. As such I delay this feature to pyqode 3.0 and a future version of ocide.

**Comment by GitMensch** [comment]
This sounds reasonable.
The "logic" other programs use is simple: only store if the search term was finished with ENTER
