### ISSUE TITLE
Feature Request: Add level 88 items to navigation pane

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#323]
As discussed in #304 this may need an option (if we add this with an option it would be nice to be able to toggle this option in navigation pane).

**Comment by ColinDuquesnoy** [comment]
I'll add an option for this in 4.7.4 (need a way to set custom option in pyqode 3.0 because the naviation pane is a generic widget that works with other languages). I'll enable it by default for now.
