### ISSUE TITLE
docs: release information for 4.7.3 miss the pyqode part: navigation of uncomplete sources like copybooks or programs that have the important divisions in copybooks works

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#324]
This quite a big part, I suggest to add it to the release notes https://launchpad.net/cobcide/4.0/4.7.3

BTW: quite a long title "usable" here.

**Comment by ColinDuquesnoy** [comment]
Done.

**Comment by GitMensch** [comment]
Can you add this to https://github.com/OpenCobolIDE/OpenCobolIDE/releases, too?

**Comment by ColinDuquesnoy** [comment]
Done.
