### ISSUE TITLE
typo: "Complier check failed"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#325]
Likely should be "Compiler check failed".

BTW: I've seen this message since months and just realized the typo. Brains are funny (assuming the right thing depending on the context).

**Comment by GitMensch** [comment]
Found another one "workign"

**Comment by GitMensch** [comment]
And the suggestion to change

~~~~patch
-            msg = 'You have to install the package open-cobol using your ' \
-                  "distribution's package manager"
+            msg = 'You have to either install one of the packages gnu-cobol or open-cobol ' \
+                  " using your distribution's package manager or "
+                  " build it from source."
~~~~

**Comment by ColinDuquesnoy** [comment]
> BTW: I've seen this message since months and just realized the typo. Brains are funny (assuming the right thing depending on the context).

Yeah, brains are funny: 

>Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in waht oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteer be at the rghit pclae. The rset can be a toatl mses and you can sitll raed it wouthit porbelm. Tihs is bcuseae the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe.
