### ISSUE TITLE
minor code issues

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#326]
I just add here what I stumble over. *minor* issues only.

~~~~patch
     def check_compiler(cls, compiler):
         def get_output_path(input_path):
             dirname, filename = os.path.split(input_path)
             basename = os.path.splitext(filename)[0]
-            possible_extensions = ['.exe', '.dll', '.so', '.dylib', '']
+            possible_extensions = ['.exe', '']
~~~~

**Comment by ColinDuquesnoy** [comment]
I don't understand why this is needed. Wouldn't that break compiler test on Linux and Max OSX?

**Comment by GitMensch** [comment]
No, you have this in two times, one for the executable where `['.exe', '']` are enough and one time for the modules where `['.dll', '.so', '.dylib']` are enough.

**Comment by GitMensch** [comment]
... or not, but I think you got the idea. Close it if it is irrelevant.

**Comment by ColinDuquesnoy** [comment]
I made possibles_extension a parameter of get_output_path, now only the correct extensions will be checked.
