### ISSUE TITLE
navigation pane orders "by level" instead of "by structure"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#336]
### Description

The code

~~~~cobol
      01 some.
           03 other.
              05 l5-0.
                 06 l6          pic x.
              05 l5-1.
                 07 l7-1.
                    09 l9-1     PIC X(01).
                    09 l9-2     PIC X(03).
                 07 l7-2        PIC 9(02).
              05 l5-2           PIC X(03).
              05 l5-3           PIC X(03).
                   88 l88-1     VALUE SPACES.
                   88 l88-2     VALUE "stuff".
~~~~

is ordered by level (all 88 are below all lvl 09, which are below the previous lvl 07, 06, 05, ...).
The problem here: it must only go upwards their own parent items.

Screenshot:
![mixed_levels](https://cloud.githubusercontent.com/assets/6699539/16453252/7d037f00-3e0c-11e6-8ba9-3d1ff466176c.PNG)

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3
- GnuCOBOL: cobc (GNU Cobol) 2.0.20151025
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.0
- pyqode.cobol: 2.9.0
- pyqode.qt: 2.9.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
Why? I find that pretty confusing...

**Comment by GitMensch** [comment]
"Why" what?
The following is perfectly fine COBOL (though a programmer may wonder if something is missing):

~~~cobol
01   level-1.
    02 level-2.
         05 level-5 pic x.
    02 level-2-again.
         03 level-3 pic x.
~~~

**Comment by ColinDuquesnoy** [comment]
I misunderstood what you meant, I thought you wanted the outline pane to order by level instead of by structure... 

The parser should already order them by structure but it looks like there is a bug (it works correctly with your second sample).

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch (I added test from your first sample).
