### ISSUE TITLE
Congratulations for 1200 commits!

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#339]
@ColinDuquesnoy Well done, keep the good work.

**Comment by ColinDuquesnoy** [comment]
Thank you @GitMensch, this cheers me up ;-)

You can also add 2657 commits from pyqode.core, 222 commits from pyqode.cobol and 78 commits from pyqode.qt, which makes a bit more than 4000 commits altogether! :open_mouth:
