### ISSUE TITLE
OutputWindow's backend cannot import pyqode

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#342]
```
23:02:05:998::ERROR::9262::pyqode.backend::Traceback (most recent call last):
23:02:05:999::ERROR::9262::pyqode.backend::  File "/usr/lib/python3/dist-packages/open_cobol_ide/extlibs/pyqode/core/backend/server.py", line 235, in <module>
23:02:05:999::ERROR::9262::pyqode.backend::    from pyqode.core import backend
23:02:05:999::ERROR::9262::pyqode.backend::ImportError: No module named 'pyqode'
23:02:06:942::ERROR::9262::pyqode.backend::Traceback (most recent call last):
23:02:06:942::ERROR::9262::pyqode.backend::  File "/usr/lib/python3/dist-packages/open_cobol_ide/extlibs/pyqode/core/backend/server.py", line 235, in <module>
23:02:06:942::ERROR::9262::pyqode.backend::    from pyqode.core import backend
```

**Comment by ColinDuquesnoy** [comment]
I think this is related to the backend of the new program output window (which use a pyqode.core backend for performing search operation in the program output content). Not a big deal, I'll fix that in next release.

**Comment by GitMensch** [comment]
What is the workaround for the standard install?

**Comment by ColinDuquesnoy** [comment]
Installing pyqode.qt, pyqode.core and pyqode.cobol should fix this issue

**Comment by GitMensch** [comment]
I've installed pyqode.core (got pyqode.qt itself). The installation showed the following output (I don't think the warnings should be there, should they?):

~~~~
simon@soprano-trisquel:~$ sudo pip3 install pyqode.core
Downloading/unpacking pyqode.core
  Downloading pyqode.core-2.10.0-py2.py3-none-any.whl (452kB): 452kB downloaded
Downloading/unpacking pyqode.qt (from pyqode.core)
  Downloading pyqode.qt-2.10.0-py2.py3-none-any.whl
Downloading/unpacking pygments (from pyqode.core)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB): 755kB downloaded
Downloading/unpacking future (from pyqode.core)
  Downloading future-0.15.2.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_root/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Installing collected packages: pyqode.core, pyqode.qt, pygments, future
  Running setup.py install for future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
    Installing futurize script to /usr/local/bin
    Installing pasteurize script to /usr/local/bin
Successfully installed pyqode.core pyqode.qt pygments future
Cleaning up...
~~~~

Problem: OCIDE doesn't work anymore (before doing the install it just showed the warnings noted above):

~~~~
simon@soprano-trisquel:~$ opencobolide 
Traceback (most recent call last):
  File "/usr/bin/opencobolide", line 9, in <module>
    load_entry_point('OpenCobolIDE==4.7.4', 'gui_scripts', 'opencobolide')()
  File "/usr/lib/python3/dist-packages/open_cobol_ide/main.py", line 29, in main
    override_sys_path()
  File "/usr/lib/python3/dist-packages/open_cobol_ide/main.py", line 20, in override_sys_path
    assert 'open_cobol_ide' in pyqode.core.__file__
AssertionError
~~~~

**Comment by ColinDuquesnoy** [comment]
Ah yes I forgot to tell you need to set the [OCIDE_DEV_MODE](https://github.com/OpenCobolIDE/OpenCobolIDE/blob/master/open_cobol_ide/main.py#L27) environment variable before running OCIDE for this to work.

**Comment by GitMensch** [comment]
OCIDE_DEV_MODE resulted in missing qcrash, installed it (and it's dependencies), everything works fine now.

**Comment by GitMensch** [comment]
Should something be concerning

    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'

?

**Comment by ColinDuquesnoy** [comment]
No  those warnings are coming from the future package. Feel free to open an issue on their bug tracker...

**Comment by GitMensch** [comment]
I've checked for an issue and created one at https://github.com/PythonCharmers/python-future/issues/221

If I understood future correct the aim is to work on python < 2.x, too - is it possible to make OCIDE (and more important HE) compatible with both? If not: where is the use of python-future?

**Comment by ColinDuquesnoy** [comment]
> If not: where is the use of python-future?

There a few pyqode users who are still stucked with python2 and pyside/pyqt4 (e.g. when embedding pyqode into freecad or houdini). I plan to remove python2 support in pyqode 3 (and qt4 support too).

I think we should stop maintaining python2 compatibility for new developments (at least not for free) and [I am not the only one](https://python3statement.github.io/) (this statement is about the python scientific community but I think this applies to the rest of the python community too).

So, no, HE and OCIDE will **never** be ported to python 2.

**Comment by GitMensch** [comment]
Can you please add OCIDE_DEV_MODE and OCIDE_EXTLIBS_PATH and their results to the docs somewhere?

**Comment by ColinDuquesnoy** [comment]
[Done](http://opencobolide.readthedocs.io/en/latest/advanced.html#developer-mode) ;-)
