### ISSUE TITLE
Modify startup screen to be more like HackEdit

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#343]
### Description

* Instead of "About" -> "Get Help" (with About, Report an issue, Documentation, Website)
* Add an additional button below: "Quit"

I'd leave the rest as it currently is, it is fine if HE and OCIDE have a different looking start screen.

**Comment by ColinDuquesnoy** [comment]
No. OCIDE is in maintainance mode and this is the kind of changes I won't do myself.
