### ISSUE TITLE
OCIDE with wrong file encoding after installation

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#344]
Not sure if/what can be done about this: after the recent installation on trisquel I was prompted with a "wrong encoding" message and manually had to add the correct (ISO-8859-1) encoding once as only UTF-8 was available (which is uncommon for most COBOL code).

**Comment by ColinDuquesnoy** [comment]
Wrong is a strong word. The available encoding is the one defined on your system. Since you can add some I don't see any issue. Common encoding depends on both the company conventions and your location in the world. I won't add any other default encoding.
