### ISSUE TITLE
Offset calculator calculates zero-based

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#345]
### Description

As this is COBOL it should be one-based.

Using

~~~cobol
       01 red-feld1-x.
           05 red-feld1-9 pic 9(01).
~~~

The offset calculator starting at `red-feld1-x` shows offset 1, starting at `red-feld1-9` shows offset 0 (should be 1 as a field always starts at 1).

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3
- GnuCOBOL: cobc (GNU Cobol) 2.0.20151025
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.0
- pyqode.cobol: 2.9.0
- pyqode.qt: 2.9.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
This issue was moved to pyQode/pyQode#65
