### ISSUE TITLE
Missing Offset entry

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#346]
### Description

The following doesn't show up in the offset calculator:

~~~cobol
       01 somevar pic 9(01) value 0.
           88 val-0 value 0.
           88 values-1 values 1, 2.
           88 val-2 value 2.
~~~

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3
- GnuCOBOL: cobc (GNU Cobol) 2.0.20151025
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.0
- pyqode.cobol: 2.9.0
- pyqode.qt: 2.9.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
This issue was moved to pyQode/pyQode#66
