### ISSUE TITLE
Syntax highlighting: free format sets all lines starting with * as comment lines

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#351]
Example:

~~~cobol
        compute a = a
                  * b
                  / 20
~~~

Free format has only inline comments, these start with `*>`.
There are other formats like the ACU terminal format (where comments start in col 1 with an asterisk, debugging lines on col 1 with `D`, ...) but as GnuCOBOL doesn't support it (yet) we may don't need to support this in OCIDE.
Or add a checkbox "asterisk in column 1 as inline comment" (MF has a similar setting which GnuCOBOL supports) in Preferences... In any case this would only be about col 1.

**Comment by ColinDuquesnoy** [comment]
This issue was moved to pyQode/pyQode#64
