### ISSUE TITLE
pyqode: add support for FIXME/TODO markers

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#355]
Looks like a pyqode.core feature (I wasn't able to create an issue there - and would like to see the backport in OCIDE, too, therefore creating it here, feel free to copy/move this issue around [for example the pyqode-part there, only a minor part to OCIDE and the full experience to HE]):

The following would have to be done:

* define a format how todo/to-do/fixme markers look like (ideally: use a standard formatting and let the user add his own via IDE options, *maybe* with a severity (1-3, something like `*> IDEA:`, `*> TODO:`, *> FIXME:`)
* check for these markers
* show them in the IDE

For the IDE options:
* option to define these markers and their severity, maybe per-file-type (not per file-extension)
* maybe give options to show them only from a given severity
* show these markers in the source view
* show these in the "lower pane" next to the issues - or include them there (at least for the severity 2+3)

**Comment by ColinDuquesnoy** [comment]
This will be in HackEdit. Parsing will be done during indexing and the solution I have in mind will be language agnostic. This will not be done in pyqode, pyqode will just highlight todo/fixme line in a different color. 

This won't be backported to OCIDE.
