### ISSUE TITLE
Compiler output not shown if error line is wrong

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#356]
When using an external preparser I've recognized that error messages are not shown at all if the line in the error does not occur in the file (preparser errror).

It would be nice to still see this error in the code window at the last line of the file (it is currently only shown if I add 200 empty lines to the file ;-))

The issues tab show the errors but this only happens on compilation (we discussed something similar to the issues tab to show the linter output for the current code window before but I didn't found the issue [I think the result was: Yes, but would be done in HE, not OCIDE]).

**Comment by ColinDuquesnoy** [comment]
I've split this issue into two subtasks: one in pyqode that will make sure error messages will always be visible in the editor and another in HE to add a plugin that shows all the error messages of the current editor. Won't be backported to OCIDE.
