### ISSUE TITLE
name parser is not case-insensitive

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#361]
If you have a `TEST-ME section` you can only jump to it via [CTRL]+[click] from `perform TEST-ME` but not from `perform test-Me`.

The same applies to variables.

Is this an pyqode (2.10.1) issue?

**Comment by GitMensch** [comment]
The same applies to the highlighting of the active word. Given a source with `TEST-ME section`, `perform test-Me` and `perform TEST-ME` you will only see a highlighting when you are on the first or last, but the second won't be highlighted.

**Comment by ColinDuquesnoy** [comment]
Does it depend on the standard or should it always be case insensitive? If it should always be case insensitive than yes this is a pyqode issue.

> The same applies to the highlighting of the active word.

Well the current word highlighter is a generic mode and is always case sensitive. We could specialise this behaviour for the cobol editor only if you think it makes sense.

**Comment by GitMensch** [comment]
> Does it depend on the standard or should it always be case insensitive?

COBOL is not case-sensitive (despite of literals, but it would be only a minor issue if you highlight literals with different case). Therefore it should always be case insensitive.

> We could specialise this behaviour for the cobol editor only if you think it makes sense.

Please do so, makes a lot of sense.

**Comment by ColinDuquesnoy** [comment]
This issue was moved to pyQode/pyQode#70

**Comment by ColinDuquesnoy** [comment]
> Please do so, makes a lot of sense.

This feature is now tracked in pyQode/pyQode#71.
