### ISSUE TITLE
Minor: Preferences->Run misses a label/link for "run in external terminal"

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#364]
### Description

The other checkboxes (at least the ones in the compiler tab) work if you click on the label but this doesn't work for "run in external terminal". Either a link is missing (if this exists) or the text isn't the actual label/caption for the checkbox.
### System information
- Operating System: Windows
- OpenCobolIDE: 4.7.5
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.4.4 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2

**Comment by ColinDuquesnoy** [comment]
Well this not the same layout: in the compiler tab the text you see is the checkbox's text property, in the run tab the text you see is a separate label, there is no link between the label and the checkbox. I'll leave it as it is.

**Comment by GitMensch** [comment]
I've seen the layout difference.

May I suggest a minimal change? Change the separate label to something like "Terminal" or "Terminal mode" or ...  - and use the text of the current label as caption for the checkbox. GUI-only change.

**Comment by ColinDuquesnoy** [comment]
Yes, why not. I'll see if it looks good.
