### ISSUE TITLE
Change to Encoding leads to empty editor window

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#365]
### Description

changed via context menu, result: editor winow empty
### System information
- Operating System: Windows
- OpenCobolIDE: 4.7.5
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.4.4 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2

Application log: https://gist.github.com/610c627e241967e78837ccfd2411c5ab

**Comment by ColinDuquesnoy** [comment]
I can reproduce it with any file. There seems to be a serious regression in pyqode.

**Comment by ColinDuquesnoy** [comment]
Fixed in pyqode master branch.
