### ISSUE TITLE
FR for compiler settings: add options for enabling the warnings

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#366]
I know that OCIDE is in mostly-bugfix mode but I think this one is really very important,

The warning flags are compiler dependent but all versions since at least OpenCOBOL 0.3 support the two groups `-W` (ALL warnings) and `-Wall` most warnings (sounds strange, doesn't it?) ...

It would be really good to have an option group for this in the compiler setting (group caption, * option, (tooltip) :

Warning group:
* none (add single warnings via "Extra compiler flags", if needed)
* -W (enable every warning)
* -Wall (enable most warnings, check compiler documentation for the specific warnings included)

I'd like to see -Wall enabled as new default, too as OCIDE is often used by people not knowing the compiler (or even COBOL) well and stumble over problems which they'd have seen directly with -Wall. But this is up to you.

**Comment by ColinDuquesnoy** [comment]
Ok, this seems very important. I'll add that to v4.7.6, probably during next weekend.
