### ISSUE TITLE
FR for showing the available compiler flags

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#367]
Can we include an option to show the available compiler flags? I think of a button right to the "extra compiler flags" that internally calls the configured compiler with the option `--help` and shows the result to the user with to option to use copy&paste to get them in the compiler flags.

The perfect solution (not part of this feature request) would be to parse the output, show a list of the available options in a popup (suppressing -help -i -V and the compiler flags we have in the IDE already) and let the user select via checkbox for each to include them in the "extra compiler flags". Not part of te FR as this is likely quite more work than only presenting the list.

**Comment by ColinDuquesnoy** [comment]
I'll do the "perfect solution" in hackedit and I'll see if I want to take the time to implement the partial solution in OCIDE. I don't promise anything yet ;-)

**Comment by ColinDuquesnoy** [comment]
This is in ;-)
