### ISSUE TITLE
Compiler setting: library and copybook paths need buttons for reordering

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#368]
### Description

Earlier options take precedence. If you want to setup a new "look there first" you currently need to remove all entries, add your new one and add the other entries back.

This is a little disturbing if you somehow manage to have 12 entries already ...

**Comment by ColinDuquesnoy** [comment]
Yes it seems rather important to have those buttons.

**Comment by ColinDuquesnoy** [comment]
Instead of adding a up/down button, I've just enabled drag & drop for internal moves and update the tooltip to let use know they can use drag & drop.

**Comment by GitMensch** [comment]
Sounds even better.
