### ISSUE TITLE
IDE crashes runnig the first time a program

### ISSUE THREAD

**Issue by Ayax917** [OpenCobolIDE/OpenCobolIDE#369]
### Description

The first time I press the green button (arrow head) running a program, after compiling sources, the IDE closes unexpectedly... I open it again, press the green button and executes normaly

### System information

- Operating System: Ubuntu
- OpenCobolIDE: 4.7.5
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.5.2 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2.1

Application log: https://gist.github.com/d0046d12cf2437617ab8f9da47a160fd

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting!

I have no clue about what's happening. I would need the application log for when the application crashed. 

Does it happens with a specific file or a basic hello world program is enough to reproduce the problem?
What version of ubuntu are you using?

**Comment by GitMensch** [comment]
@Ayax917 The application log is from the "works all fine" part. Can you please reproduce the issue and upload the application log where the error occurred?
According to [the docs][1] you'll find it at `~/.cache/.OpenCobolIDE/OpenCobolIDE.log`.

[1]:http://opencobolide.readthedocs.io/en/latest/faq.html#where-can-i-find-ocide-s-log-file

**Comment by ColinDuquesnoy** [comment]
@Ayax917 ping
