### ISSUE TITLE
OpenCobolIDE chrashes unexpectedly on editing source file

### ISSUE THREAD

**Issue by Ayax917** [OpenCobolIDE/OpenCobolIDE#371]
### Description

OpenCobolIDE crashes when I try edit some code line in a source file.

### System information

- Operating System: Ubuntu
- OpenCobolIDE: 4.7.5
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.5.2 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.0
- pyqode.cobol: 2.10.0
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2.1

Application log: https://gist.github.com/17d4bbbd027dc8f42c185f1894e607c0

**Comment by GitMensch** [comment]
Doesn't chrash here. Please create a minimal source sample where this happens (it will be included in the log), open OCIDE -> About and set the log level to maximum (PYQUODE_DEBUG) and click on "Clear logs".

Then restart the ide, open your minimal source and edit something until it chrases.
Add a comment to this issue and add the [log file][1] to this issue.

[1]:http://opencobolide.readthedocs.io/en/latest/faq.html#where-can-i-find-ocide-s-log-file
delete you log file

**Comment by ColinDuquesnoy** [comment]
@Ayax917 ping
