### ISSUE TITLE
Outline: Paragraphs recognition is borked

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#373]
### Description

I *think* we discussed this issue already, just to be sure:

Source lines that contain only one name and end with a period are currently marked as ne paragraph. This isn't correct (if you need more detailed rules drop a note).

Sample:

```cobol
            move function trim (tmp-source-line-buffer, trailing) to
                sourceline(MAX-ROWS).
```

Shows a paragraph "sourceline(MAX-ROWS)" (which shows an additional problem: words in the outline are currently not separated by parenthesis.)

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.4
- GnuCOBOL: cobc (GnuCOBOL) 2.0.20161105
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by GitMensch** [comment]
Just to add to the "outline doesn't separate on parenthesis: the auto-completion (smart) suggest me to insert `sourceline(max-rows)` when I type `max` (this may be a different and easy to change issue).

**Comment by ColinDuquesnoy** [comment]
Not sure if we discussed this but I won't implement this in pyqode. That being said I am interested to know more about the rules; it will definitely be helpful when I'll write the cobol parser for the new hackedit cobol editor.
