### ISSUE TITLE
FR: Search history

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#375]
### Description

We currently have only the last entry in the search, a drop-down would be nice - as it would be nice to keep the list between sessions (automatic store/reload from disk).

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.4
- GnuCOBOL: cobc (GnuCOBOL) 2.0.20161105
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.0.2
- QDarkStyle: 2.1

**Comment by ColinDuquesnoy** [comment]
I think we already discussed this. It would be a new feature of pyQode 3.0.

I don't know if you've read HackEdit/pyhackedit#95. In short I probably won't continue developing pyqode with python and QtWidgets, I will switch to C++ and QML. This means I will not implement all the features (and backports) planned for pyQode 3.0 and OCIDE 4.8.

**Comment by ColinDuquesnoy** [comment]
I will continue to address critical bug fix, **but no more new features.**
