### ISSUE TITLE
Add option to set command line parameters on run

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#378]
As this was asked/requested in the GnuCOBOL discussion boards I want to leave this here (even if OCIDE is in maintenance mode):

It would be quite useful to be able to pass command line options to the programs running.
This could be (for the GUI) easy possible by adding a submenu to the "run" button as it exists with the "compile" button (Executabel/Module). 

![ocide_tb](https://cloud.githubusercontent.com/assets/6699539/20700919/5ec87f1e-b610-11e6-9e29-5d11b44c73ac.PNG)

The standard (current behavior) would be "Run without parameters", the new one would be "Run with parameters". If this is chosen popup a minimal dialogue with a combobox where the user could choose from the last n options or type new ones.
The options are passed to the module by `cobcrun.exe module params` or `module.exe params`.

**Comment by ColinDuquesnoy** [comment]
I can see how useful that is. I haven't made my decision yet but if I do implement that feature, I will just add a new setting in the run preferences and no history of last options.

**Comment by GitMensch** [comment]
What about adding the sub-menu and don't save any parameters (or maybe only the last one)? I think this is much clearer than the run setting - but I won't complain *how* this is implemented ;-)
