### ISSUE TITLE
intend in fixed-form should not intend col7

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#380]
### Description

this actually works with un-intend (if it is on col7 it stays there) but not in the other way around

**Comment by ColinDuquesnoy** [comment]
What if you have written this (``|`` represents the cursor position):

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. YOUR-PROGRAM-NAME.
       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
       |DISPLAY "Hello world"
```

and you want to indent the display statement. I think you should be able to do it.

**Comment by GitMensch** [comment]
Thanks for taking the time to investigate this.

Yes, you should be able to intend - but this is column 12. In fixed form you have col 7 as "special column" and you already don't intend backwards in this column therefore it is consequent to don't to it the other wa around.

I've used ([SHIFT]+)[TAB] after selecting a block of code and all the comments weren't comments afterwards.

**Comment by ColinDuquesnoy** [comment]
Thank you for the explanation. It makes perfect sense now.
