### ISSUE TITLE
[Unhandled exception] AttributeError

### ISSUE THREAD

**Issue by ethnerom** [OpenCobolIDE/OpenCobolIDE#383]
### Description

hh

### Traceback

```
  File "/usr/local/lib/python3.5/dist-packages/open_cobol_ide/controllers/cobol.py", line 359, in run
    self.compile()
  File "/usr/local/lib/python3.5/dist-packages/open_cobol_ide/controllers/cobol.py", line 214, in compile
    path = self.app.edit.current_editor.file.path

AttributeError: 'NoneType' object has no attribute 'file'
```

### System information

- Operating System: Ubuntu
- OpenCobolIDE: 4.7.5
- GnuCOBOL: cobc (OpenCOBOL) 1.1.0
- Python: 3.5.2 (64bits)
- Qt: 5.7.0
- PyQt: 5.7
- pyqode.core: 2.10.0
- pyqode.cobol: 2.10.0
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2.1

Application log: https://gist.github.com/f97eea08af8e5c6ad7521cea55f2fc47

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting! 

But I have no clue why this happened. Could you describe the steps needed to reproduce the issue and/or include a more verbose log output? (About -> Log -> Set log level to DEBUG).
