### ISSUE TITLE
Is there an option to use environment variables in preferences -> compiler/run

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#384]
There is an option to set environment variables there - but can we use them, too?

I've tested with Output-directory "%temp%" and this "directory" was created below the source directly.
Using environment vars would even allows to use OCIDE with two different projects: just set an environment variable `PROJDIR` from a batch file and start OCIDE from there.
[It is actually possible to switch between two compiler versions this way - remove all compiler settings from OCIDE and set them via an environment var beforehand]

**Comment by ColinDuquesnoy** [comment]
Sorry, I've read your post several times but I can't seem to figure out what you mean... 

Especially, this sentence is somewhat cryptic : "There is an option to set environment variables there - but can we use them, too?" What do you mean by: "can we use them too?"??

**Comment by GitMensch** [comment]
We can *set* environment variables in the preferences. These are used from the called processes.
But I'd like to *use* environment variables which were set when OCIDE process was started. My example was to set the output directory to "%temp%\bin" (assuming this would create the files under "C:\users\simon\Appdata\Local\Temp"). Not sure if there is such an option already we have to use `$(var)` or `$var` instead of `%var%` (in this case I pretend to not have read this in the docs).

**Comment by ColinDuquesnoy** [comment]
OCIDE will pick up system environment variables and only override them if other environment variables are set in the settings. But it does not (and will not) expand environment variables set in the settings' text boxes such as the output directory.

**Comment by GitMensch** [comment]
I see. Would it be hard to check and error for `$` [!WIN32] / `%` [WIN32] in the settings' text boxes?

**Comment by ColinDuquesnoy** [comment]
> Would it be hard to check and error for $ [!WIN32] / % [WIN32] in the settings' text boxes?

It wouldn't be hard but it would take some time (too much for me).

**Comment by GitMensch** [comment]
OK. Then I suggest to add this as a remark in the docs :-)

**Comment by ColinDuquesnoy** [comment]
Good suggestion. It's done ;)
