### ISSUE TITLE
Request: Can you please update the reserved words for the upcoming release?

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#389]
These are the current (and slightly updated for things to come) reserved words, known intrinsic functions and available mnemonic identifiers.

[reserved.lst.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/678481/reserved.lst.txt)
[intrinsics.lst.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/678482/intrinsics.lst.txt)
[mnemonic.lst.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/678483/mnemonic.lst.txt)

As this will surely be done in pyqode BPEdit gets them for free :-)

**Comment by ColinDuquesnoy** [comment]
Yes it will be in pyqode.cobol 2.11.0. I added these in commit pyQode/pyqode.cobol@9fdcf11c14d67270e9e5541180e4bb3e40c5657f

**Comment by GitMensch** [comment]
Nice. Thank you. Does something like `SWITCH 21` (containing a space) actually work?

**Comment by ColinDuquesnoy** [comment]
> Does something like SWITCH 21 (containing a space) actually work?

It is highlighted yes.
