### ISSUE TITLE
OCIDE releases

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#390]
launchpad misses 4.7.6 - it would be a good idea to either add this there, too or get the pre 4.7 releases here, too and closing launchpad.

Question: does GitHub provide the nice download stats like launchpad somewhere?

Hint for the release: the MinGW package comes from Arnold Trembl**e**y

**Comment by ColinDuquesnoy** [comment]
I know. I usually first release [here on Github](https://github.com/OpenCobolIDE/OpenCobolIDE/releases) and pypi and then I create mirrors on launchpad.

> Question: does GitHub provide the nice download stats like launchpad somewhere?

I think you need to use the github RestAPI to retrieve such stats. I think I remember someone wrote a script to retrieve the stats.

**Comment by GitMensch** [comment]
> I think you need to use the github RestAPI to retrieve such stats. I think I remember someone wrote a script to retrieve the stats.

The nicest part of pypi is https://coveralls.io/github/OpenCobolIDE/OpenCobolIDE :-)

It would be nice to include the script within the release tag (if possible) or be able to run it manually.

**Comment by ColinDuquesnoy** [comment]
> The nicest part of pypi is https://coveralls.io/github/OpenCobolIDE/OpenCobolIDE :-)
It would be nice to include the script within the release tag (if possible) or be able to run it manually.

Sorry I am not sure what part you're talking about? The coverage badge or the build number?

**Comment by GitMensch** [comment]
The test coverage of 65% (this is what it means, isn't it) is more than many small free software projects have (not sure about GnuCOBOL, this will be one of the focus of a later release...).

**Comment by ColinDuquesnoy** [comment]
I couldn't find the script back. But you can retrieve a lots of stats for the github releases of OCIDE with curl:

```bash
curl -i  https://api.github.com/repos/OpenCobolIDE/OpenCobolIDE.git/releases -H "Accept: application/vnd.github.manifold-preview+json"
```
