### ISSUE TITLE
FR: add selection size to the status bar

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#392]
### Description

If the next version is only for updating the version of GnuCOBOL on Win32 this is only as hint for HE, otherwise it is a nice-to-have:

OCIDE shows current position (line + position in bytes/chars) in the right lower corner.
It would be nice if it would additionally show the length of the current selection (NPP has this built-in and especially for languages like COBOL where literal size often matters it is a nice helping function).

This is NPP's status bar:
![grafik](https://cloud.githubusercontent.com/assets/6699539/21846320/eb8358d6-d7f6-11e6-9f13-e6697eb3ab59.png)
* number of bytes in the current source
* number of lines in the current source
* position (line, column), if you double click the menu for "go to" (the same that is opened with [CTRL]+[G]) opens
* current selection (number of bytes | number of lines)
* position (line, column), if you do a double click there then the dialog for "go to" (the same that is opened with [CTRL]+[G]) opens
* line ending style, if you do a right click there then the sub-menu for line-ending opens as context menu
* encoding used in the current source window if you double or right click there nothing happens
* insert mode currently used in the editor, if you do a double click there then it toggles between "INS" (insert) and "OVR" overwrite (the same that is done with pressing [Insert])

**Comment by ColinDuquesnoy** [comment]
> If the next version is only for updating the version of GnuCOBOL on Win32 this is only as hint for HE, 

Yes no new features are planned for OCIDE. I'll implement this in HackEdit. 

Since the development of the C++/QML version of HackEdit will take some quite time (I don't expect to finish it before 1/2 years) and I don't want to be flooded by feature request/tickets, I'd suggest to keep those suggestion for you for now and check the hackedit beta version when available and only open tickets at that time. Ok?
