### ISSUE TITLE
"Detect and compile sub-modules" compiles additional sources even for nestes/multi programs

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#395]
### Description

Sample

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. progA.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  BIN PIC 9(9) BINARY VALUE 1.

       PROCEDURE DIVISION.
           CALL "subb" USING bin.
           CALL "subb" USING 4096.
       STOP RUN.

       IDENTIFICATION DIVISION.
       PROGRAM-ID. subb.
       DATA DIVISION.
       WORKING-STORAGE SECTION.

       LINKAGE SECTION.
       01  X  PIC 9(9) BINARY.

       PROCEDURE DIVISION USING X.
            DISPLAY ':' X ':'.
       END PROGRAM subb.
       END PROGRAM progA.

```

OCIDE tries to compile the program "subb" (just realized this as I had a broken source subb.cob laying around).

**Comment by ColinDuquesnoy** [comment]
Do you have a file named subb.cbl (or .cob,...) next to your sample source file?

OCIDE does not check of there is a nested subprogram, it just try to find a corresponding module with the name of the subprogram.

**Comment by GitMensch** [comment]
> Do you have a file named subb.cbl (or .cob,...) next to your sample source file?

yes.

> OCIDE does not check if there is a nested subprogram, it just try to find a corresponding module with the name of the subprogram.

That's the bug description.

**Comment by ColinDuquesnoy** [comment]
I won't fix that tiny edge case.

**Comment by GitMensch** [comment]
OK, please add wontfix label showing "the bug is not closed because it is fixed but because it wont be fixed" (if no pull-request will be done).

**Comment by ColinDuquesnoy** [comment]
I already added the wontfix label.
