### ISSUE TITLE
LINAGE-COUNTER Error - Microfocus to OpenCobol conversion

### ISSUE THREAD

**Issue by cuervojones** [OpenCobolIDE/OpenCobolIDE#397]
Hello friends,
I'm converting a Microfocus cobol program to Open Cobol and found myself with the following errors:

syntax error, unexpected LINAGE-COUNTER, expecting ADDRESS or Identifier

SFH017.COB: In paragraph '500-00':

SFH017.COB:443: Error: syntax error, unexpected LINAGE-COUNTER, expecting ADDRESS or Identifier

Here's the program. The error is happenning at the '500-CABEC' section.

``      IDENTIFICATION DIVISION.
       PROGRAM-ID.                     SFH017.
      * AUTHOR.                         FELIPE.
      * SECURITY.
      *            SISTEMA : S F H
      *            OBJETIVO: QUADRO GERENCIAL SFHCEF
      *
      * ORDEM DA TABELA SITUACAO <> ORDEM DOS TOTAIS
      * EX: SIT-W(4) "TOTAL RNV" | TVENCIDO-W(4) = RNV NAO AUDITADO
      *
      * SITUACAO E VALORES POR LINHA ONDE (IND-W)

      * LINHA 9 RCV = SIT-W(1)
      * LINHA 10 AUDITADO = SIT-W(13) | VALORES(1)
      * LINHA 11 NAO AUDITADO = SIT-W(14) | VALORES(2)
      * LINHA 14 TOTAL RCV = SIT-W(2) | VALORES(11)
      * LINHA 16 RNV = SIT-W(3)
      * LINHA 18 AUDITADO = SIT-W(13) | VALORES(3)
      * LINHA 19 NAO AUDITADO = SIT-W(14) | VALORES(4)
      * LINHA 21 TOTAL RNV = SIT-W(4) | VALORES(12)
      * LINHA 23 TOTAL = SIT-W(5)
      * LINHA 24 RCV+RNV = SIT-W(6) | VALORES(13)
      * LINHA 26 SM = SIT-W(7)
      * LINHA 28 AUDITADO = SIT-W(13) | VALORES(5)
      * LINHA 29 NAO AUDITADO = SIT-W(14) | VALORES(6)
      * LINHA 31 RNV NEGATIVA = SIT-W(8)
      * LINHA 33 NAO AUDITADO = SIT-W(13) | VALORES(7)
      * LINHA 34 AUDITADO = SIT-W(14) | VALORES(8)
      * LINHA 36 TOTAL SM+RNV = SIT-W(9) | VALORES(14)
      * LINHA 39 CNH = SIT-W(10)
      * LINHA 40 NAO HOMOLOGADO = VALORES(9)
      * LINHA 43 NEGATIVA = SIT-W(11)
      * LINHA 44 COBERTURA = SIT-W(12) | VALORES(10)

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.                S-8000.
       OBJECT-COMPUTER.                S-8000.
       SPECIAL-NAMES.                  DECIMAL-POINT IS COMMA.
      *
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      *
           SELECT SFHCAD ASSIGN TO DISK "SFHCAD"
                  ORGANIZATION INDEXED
                  ACCESS MODE  DYNAMIC
                  RECORD KEY   BOSFH01KEY.
      *
           SELECT SFHCEF ASSIGN TO DISK "SFHCEF"
                  ORGANIZATION INDEXED
                  ACCESS MODE  DYNAMIC
                  RECORD KEY   BOSFH06KEY.
      *
           SELECT SFHCEF-S ASSIGN TO DISK "SFHCEF-S"
               ORGANIZATION IS LINE SEQUENTIAL.
      *
           SELECT SORT-FILE ASSIGN TO DISK "SORTWORK".
      *
           SELECT RELATO ASSIGN TO DISK "SFH017T.TXT"
               ORGANIZATION IS LINE SEQUENTIAL.
      /
       DATA DIVISION.
       FILE SECTION.
      *
       FD          SFHCAD.
           COPY 'BOSFH001'.
      *
       FD          SFHCEF.
           COPY 'BOSFH006'.
      *
       SD  SORT-FILE.
       01  SORT-RECORD.
           02  S-KEY                      PIC 9(13).
           02  S-NOME                     PIC X(40).
           02  FILLER                     PIC X(85).

       FD          SFHCEF-S.
           COPY 'BOSFH006S'.
      *
       FD          RELATO
           LINAGE IS 66 WITH FOOTING AT 58.
       01          LINHA               PIC X(132).
      /
        WORKING-STORAGE SECTION.
       01 WS-WORK.        
           05          ACC-W               PIC 9(01) VALUE ZEROS.
           05          SALDO-W             PIC 9(13)V99.
           05          QTD-W               PIC 9(03) OCCURS 14 TIMES.
           05          TVENCIDO-W          PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05         TVENCENDO-W         PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05          TVAF3-W             PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05          TVAF4-W             PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05          TNOVADO4-W          PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05          TNOVADO-W           PIC 9(13)V99
                                       OCCURS 14 TIMES.
           05          TSEMNOV-W           PIC 9(13)V99
                                       OCCURS 14 TIMES.
      *
       05          DATA-AUX            PIC 9(08).
       05          DATA-AUX-R REDEFINES  DATA-AUX.
           10      DIA-AUX             PIC 9(02).
           10      MES-AUX             PIC 9(02).
           10      ANO-AUX             PIC 9(04).
      *
       05          DATA-CAB            PIC 9(08).
       05          RDATA-CAB REDEFINES DATA-CAB.
           10      DIA-CAB             PIC 9(02).
           10      MES-CAB             PIC 9(02).
           10      ANO-CAB             PIC 9(04).

       05 IND-W                        PIC 9(02) VALUE ZEROS.
       05 WS-EXISTE                    PIC 9(01) VALUE ZEROS.
       05 SIT-W                        PIC X(03) VALUE SPACES.
       05 WS-PRIM                      PIC 9(01) VALUE ZEROS.
       05 MASC-W                       PIC ZZ.ZZZ.ZZ9,99.
       05 QTD-MASC                     PIC ZZ9 VALUE ZEROS.
       05 WS-LIN-SOBR                  PIC 9(02) VALUE ZEROS.
       05 WS-LIN-MAX                   PIC 9(02) VALUE 66.          
      *
      *****
      *
      *
      ****** R E L A T O R I O *****
      *
       01          LIN-W1.
           05      FILLER              PIC X(113) VALUE
      *    05      FILLER              PIC X(61) VALUE
              'FAMILIA PAULISTA COMPANHIA HIPOTECARIA  '.
           05      FILLER              PIC X(12)  VALUE
                   'DATA  -'.
           05      DATA-W1             PIC 99/9999.
      *
       01          LIN-W2.
           05      CAB-W2              PIC X(61) VALUE
      *    'RELACAO DOS CONTRATOS ALTERADOS NO MES DE '.
           'QUADRO GERENCIAL'.
      *    05      MES-W2              PIC X(09).
      *    05      FILLER              PIC X(01) VALUE '/'.
      *    05      ANO-W2              PIC 9(04)B(10).
      *
       01          LIN-W3.
           05      FILLER             PIC X(113) VALUE
      *    05      FILLER             PIC X(61) VALUE
                   'D.T.I. - SFH017'.
           05      FILLER             PIC X(16)  VALUE
                   'FOLHA -'.
           05      FOLHA-W3           PIC 9(03)  VALUE ZEROS.
      *
       01          LIN-W4.
           05      FILLER              PIC X(132) VALUE ALL '-'.
      *
       01          LIN-W5.
           05      FILLER              PIC X(14) VALUE
                   'SITUACAO'.
           05      FILLER              PIC X(09) VALUE
                   'QTDE'.
           05      FILLER              PIC X(07) VALUE
                   'TR'.
           05      FILLER              PIC X(14) VALUE
                   'SLD. VENCIDO'.
           05      FILLER              PIC X(24) VALUE
                   'SLD. VINCENDO'.
           05      FILLER              PIC X(15) VALUE
                   'VAF3'.
           05      FILLER              PIC X(08) VALUE
                   'VAF4'.
           05      FILLER              PIC X(14) VALUE
                   'SLD. NOVADO'.
      *    05      FILLER              PIC X(22) VALUE
      *            'SALDO NOVADO'.
      *    05      FILLER              PIC X(12) VALUE
      *            'SALDO'.
      *
      *01          LIN-W5A.
      *    05      FILLER              PIC X(111) VALUE SPACES.
      *    05      FILLER              PIC X(10) VALUE
      *            '- VAF4'.
      *    05      FILLER              PIC X(11) VALUE
      *            'SEM NOVACAO'.
      * 
       01          DET-W5B.       
           05      SIT-W5B             PIC X(20).
           05      DIV1-W5B            PIC X(01) VALUE "(".
           05      TR-W5B              PIC X(05).
           05      DIV2-W5B            PIC X(01) VALUE ")".
      *
       01          DET-W5.
           05      SIT-W5              PIC X(15).
           05      QTD-W5              PIC X(12).
           05      FILLER              PIC X(01) VALUE SPACES.
           05      VENCIDO-W5          PIC ZZZ.ZZZ.ZZ9,99.
           05      FILLER              PIC X(01) VALUE SPACES.
           05      VENCENDO-W5         PIC ZZZ.ZZZ.ZZ9,99.
           05      FILLER              PIC X(01) VALUE SPACES.
           05      VAF3-W5             PIC ZZZ.ZZZ.ZZ9,99.
           05      FILLER              PIC X(01) VALUE SPACES.
           05      VAF4-W5             PIC ZZZ.ZZZ.ZZ9,99.
           05      FILLER              PIC X(01) VALUE SPACES.
           05      TNOVADO4-W5         PIC ZZZ.ZZZ.ZZ9,99.
           05      FILLER              PIC X(01) VALUE SPACES.
      *    05      TNOVADO-W5          PIC ZZZ.ZZZ.ZZ9,99.
     **    05      FILLER              PIC X(01) VALUE SPACES.
     **    05      SLDSEMNOV-W5        PIC ZZZ.ZZZ.ZZ9,99.
       01 SITUACAO-T.
                 05 FILLER PIC X(15) VALUE "RCV".
                 05 FILLER PIC X(15) VALUE "TOTAL RCV".
                 05 FILLER PIC X(15) VALUE "RNV".
                 05 FILLER PIC X(15) VALUE "TOTAL RNV".
                 05 FILLER PIC X(15) VALUE "TOTAL".                 
                 05 FILLER PIC X(15) VALUE "RCV + RNV".                                  
                 05 FILLER PIC X(15) VALUE "SM".
                 05 FILLER PIC X(15) VALUE "RNV (NEGATIVA)".
                 05 FILLER PIC X(15) VALUE "TOTAL SM + RNV".                                  
                 05 FILLER PIC X(15) VALUE "CNH".
                 05 FILLER PIC X(15) VALUE "NEGATIVA".
                 05 FILLER PIC X(15) VALUE "COBERTURA".
                 05 FILLER PIC X(15) VALUE "AUDITADO".
                 05 FILLER PIC X(15) VALUE "NAO AUDITADO".
        01 SITUACAO-R REDEFINES SITUACAO-T.
                 05 SITUACAO-W              PIC X(15) OCCURS 14 TIMES.

       
                     
      *
       COPY TABMES.
      *
       01  LINHA-BRANCO.
           05      FILLER              PIC X(136) VALUE ALL ' '.
      /
        SCREEN SECTION.
        01 TELA-W.
                03 BLANK SCREEN.
                03 LINE 1 COL 20 VALUE
      -  "FAMILIA PAULISTA COMPANHIA HIPOTECARIA  " HIGHLIGHT.
                03 LINE 3 COL 20 VALUE
      -  "SISTEMA     - S F H" HIGHLIGHT.
                03 LINE 5 COL 20 VALUE
      -  "SUB-SISTEMA - QUADRO GERENCIAL SFHCEF" HIGHLIGHT.
                03 LINE 7 COL 20 VALUE
      -  "PROGRAMA    - SFH017" HIGHLIGHT.
                03 LINE 12 COL 20 VALUE
      -  "I M P R I M I N D O   ! ! !" HIGHLIGHT.

        01 LABO-LIMPA.
                03 LINE 25 COL 1 BLANK LINE.
        01  LIMPA-TELA.
                03  BLANK SCREEN.
        PROCEDURE DIVISION.
      ********************
      *
       001-INICIO SECTION.
       001-00.
           PERFORM 100-PROCINIC.
           PERFORM 200-PROCESSA UNTIL BOSFH06KEY-S = HIGH-VALUES.
           PERFORM 600-TOTAL
                   VARYING IND-W FROM 1 BY 1
                   UNTIL IND-W GREATER THAN 10.
           PERFORM 999-FIM.
           STOP    RUN.
       001-EXIT.
           EXIT.
      *
      *****
      *
       100-PROCINIC SECTION.
       100-00.
           DISPLAY TELA-W.

           SORT SORT-FILE
                   ON ASCENDING KEY S-NOME
                   USING SFHCEF
                   GIVING SFHCEF-S.

           OPEN    INPUT  SFHCEF-S.
           OPEN    INPUT  SFHCAD.
           OPEN    OUTPUT RELATO.
       100-EXIT.
           EXIT.
      *
      *****
      *
       200-PROCESSA SECTION.
       200-00.

           PERFORM 800-LE-SFHCEF.
           IF      BOSFH06KEY-S = HIGH-VALUES
                   GO TO 200-EXIT.

           MOVE BOSFH06EMP-S     TO BOSFH01EMP.
           MOVE BOSFH06NRO-S     TO BOSFH01NRO.
           MOVE BOSFH06DV-S      TO BOSFH01DV.

           PERFORM 700-PROCURA-SFHCAD.

           IF WS-EXISTE EQUAL 1
                   GO TO 200-EXIT.

           PERFORM 300-INICIA.

           PERFORM 400-VERIFICA-CONDICOES.

       200-EXIT.
           EXIT.
      *
      *****
      *
       300-INICIA SECTION.
       300-00.

      *    MOVE MESTAB-W(BOSFH06MBASE-S) TO MES-W2.
      *    MOVE BOSFH06ABASE-S TO ANO-W2.

           MOVE  01            TO DIA-CAB
           MOVE BOSFH06MBASE-S TO MES-CAB
           MOVE BOSFH06ABASE-S TO ANO-CAB.

           MOVE    DATA-CAB  TO DATA-W1.

           IF WS-PRIM EQUAL ZEROS
               PERFORM 500-CABEC.
       300-EXIT.
           EXIT.
      *
       400-VERIFICA-CONDICOES SECTION.
       400-00.
           MOVE BOSFH01POSICAO TO SIT-W.
      *    MOVE BOSFH01CONDRET TO TR-W5.

           EVALUATE SIT-W
           WHEN "RCV"
               IF BOSFH06AUDINAUD-S EQUAL "AUDI"
                     MOVE 1 TO IND-W
                     PERFORM 450-ADICIONA-VALORES
               ELSE
                     MOVE 2 TO IND-W
                     PERFORM 450-ADICIONA-VALORES
               END-IF
               MOVE 11 TO IND-W
               PERFORM 450-ADICIONA-VALORES               
               MOVE 13 TO IND-W
               PERFORM 450-ADICIONA-VALORES                              
      * RNV PODE SER AUDITADO/NAO AUDITADO E NEGATIVADO
           WHEN "RNV"
               IF BOSFH06AUDINAUD-S EQUAL "AUDI"
                   IF BOSFH01CONDRET EQUAL 05
                          MOVE 7 TO IND-W
                          PERFORM 450-ADICIONA-VALORES
                          MOVE 14 TO IND-W
                          PERFORM 450-ADICIONA-VALORES
                   ELSE
                          MOVE 3 TO IND-W
                          PERFORM 450-ADICIONA-VALORES
                          MOVE 12 TO IND-W
                          PERFORM 450-ADICIONA-VALORES
                          MOVE 13 TO IND-W
                          PERFORM 450-ADICIONA-VALORES
                   END-IF
               ELSE
                  IF BOSFH06AUDINAUD-S EQUAL "NAUD"
                       IF BOSFH01CONDRET EQUAL 05
                           MOVE 8 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                           MOVE 14 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                       ELSE
                           MOVE 4 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                           MOVE 12 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                           MOVE 13 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                       END-IF

                  ELSE
                       IF BOSFH01CONDRET EQUAL 05
                           MOVE 10 TO IND-W
                           PERFORM 450-ADICIONA-VALORES
                       END-IF
                  END-IF
               END-IF
           WHEN "SM "
           WHEN " SM"
      *
      * SM NEGATIVADO (AUDI OU NAUDI) ADICIONA SOMENTE NOS NEGATIVADOS
      *
               IF BOSFH01CONDRET EQUAL 05
                   MOVE 10 TO IND-W
                   PERFORM 450-ADICIONA-VALORES
               ELSE
                   IF BOSFH06AUDINAUD-S EQUAL "AUDI"
                       MOVE 5 TO IND-W
                       PERFORM 450-ADICIONA-VALORES
                   ELSE
                       MOVE 6 TO IND-W
                       PERFORM 450-ADICIONA-VALORES
                   END-IF
                   MOVE 14 TO IND-W
                   PERFORM 450-ADICIONA-VALORES
               END-IF
           WHEN "CNH"
               MOVE 9 TO IND-W
               PERFORM 450-ADICIONA-VALORES
      * NENHUMA DAS SITUACOES ANTERIORES
           WHEN OTHER
               IF BOSFH01CONDRET EQUAL 05
                       MOVE 10 TO IND-W
                       PERFORM 450-ADICIONA-VALORES
               ELSE
                       DISPLAY BOSFH01POSICAO AT 2610
                       DISPLAY 'SITUACAO INVALIDA' AT 2510
                       ACCEPT ACC-W
               END-IF
           END-EVALUATE.
       400-EXIT.
           EXIT.
      *
       450-ADICIONA-VALORES SECTION.
       450-00.
           ADD BOSFH06SLDVENCIDO-S  TO TVENCIDO-W(IND-W).
           ADD BOSFH06SLDVENCENDO-S TO TVENCENDO-W(IND-W).
           ADD BOSFH06VAF3POSIC-S   TO TVAF3-W(IND-W).
           ADD BOSFH06VAF4POSIC-S   TO TVAF4-W(IND-W).
           ADD 1                  TO QTD-W(IND-W).

           COMPUTE SALDO-W = BOSFH01VCEFMANT + BOSFH01CRE -
                   BOSFH01DEB + BOSFH01CMONETCEF
                   + BOSFH01JUROSCEF + BOSFH01VAGMANT
                   + BOSFH01CMONETAG + BOSFH01JUROSAG.

                   ADD SALDO-W TO TSEMNOV-W(IND-W).

       450-EXIT.
           EXIT.
      *
       500-CABEC SECTION.
       500-00.
             MOVE ZEROS TO LINAGE-COUNTER.
             ADD     1 TO FOLHA-W3.
             WRITE   LINHA FROM LIN-W1.
             WRITE   LINHA FROM LIN-W2.
             WRITE   LINHA FROM LIN-W3.
             WRITE   LINHA FROM LINHA-BRANCO.
             WRITE   LINHA FROM LIN-W4.
             WRITE   LINHA FROM LIN-W5.
      *      WRITE   LINHA FROM LIN-W5A.
             WRITE   LINHA FROM LIN-W4.
             MOVE 1 TO WS-PRIM.
       500-EXIT.
           EXIT.
      *
       600-TOTAL SECTION.
       600-00.
      *
      * LINHA DE SITUACAO
      *

       EVALUATE IND-W
       WHEN 01
            MOVE "RCV" TO SIT-W5B
                        MOVE "12-17" TO TR-W5B
            WRITE LINHA FROM DET-W5B
*******************************************************                        
            WRITE LINHA FROM LIN-W4
*******************************************************                        
            MOVE "AUDITADO" TO SIT-W5
            PERFORM 620-MOVE-VALORES            
            PERFORM 650-GRAVA
       WHEN 02
            MOVE "NAO AUDITADO" TO SIT-W5
            PERFORM 620-MOVE-VALORES                        
            PERFORM 650-GRAVA
*******************************************************            
            WRITE LINHA FROM LIN-W4
*******************************************************            
            MOVE "TOTAL RCV" TO SIT-W5
            MOVE 11 TO IND-W
            PERFORM 620-MOVE-VALORES
            PERFORM 650-GRAVA
*******************************************************                        
            WRITE LINHA FROM LIN-W4            
*******************************************************                        
            MOVE 02 TO IND-W
       WHEN 03       
            MOVE "RNV" TO SIT-W5B
                        MOVE "12-17" TO TR-W5B
            WRITE LINHA FROM DET-W5B
*****************************************************                        
            WRITE LINHA FROM LIN-W4
*****************************************************            
            MOVE "AUDITADO" TO SIT-W5
            PERFORM 620-MOVE-VALORES
            PERFORM 650-GRAVA
       WHEN 04
            MOVE "NAO AUDITADO" TO SIT-W5
            PERFORM 620-MOVE-VALORES            
            PERFORM 650-GRAVA
*******************************************************            
            WRITE LINHA FROM LIN-W4
*******************************************************            
            MOVE "TOTAL RNV" TO SIT-W5
            MOVE 12 TO IND-W
            PERFORM 620-MOVE-VALORES
            PERFORM 650-GRAVA            
*******************************************************            
            WRITE LINHA FROM LIN-W4
*******************************************************
                        MOVE SPACES TO DIV1-W5B
                                       DIV2-W5B
            MOVE "TOTAL" TO SIT-W5B
                        MOVE SPACES TO TR-W5B
            WRITE LINHA FROM DET-W5B
                        MOVE "RCV + RNV" TO SIT-W5
            MOVE 13 TO IND-W
            PERFORM 620-MOVE-VALORES
                        PERFORM 650-GRAVA
                        WRITE LINHA FROM LIN-W4
                        MOVE 04 TO IND-W
                        MOVE "(" TO DIV1-W5B
                        MOVE ")" TO DIV2-W5B

      *
      * A PARTIR DE 20/9/16 LUZIA SOLICITOU ALTERACAO
      *

      *    WHEN 05
      *                 MOVE "SM" TO SIT-W5B
      *                 MOVE "12-17" TO TR-W5B
      *                 WRITE LINHA FROM DET-W5B
*******************************************************                        
      *                 WRITE LINHA FROM LIN-W4
*******************************************************                        
      *                 MOVE "AUDITADO" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
      *    WHEN 06
      *                 MOVE "NAO AUDITADO" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
*******************************************************                        
      *                 WRITE LINHA FROM LIN-W4
*******************************************************                                    
      *    WHEN 07
      *                 MOVE "RNV (NEGATIVA)" TO SIT-W5B
      *                 MOVE "  17" TO TR-W5B
      *                 WRITE LINHA FROM DET-W5B
*******************************************************                        
      *                 WRITE LINHA FROM LIN-W4
*******************************************************                                    
      *                 MOVE "AUDITADO" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
      *    WHEN 08
      *                 MOVE "NAO AUDITADO" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
*******************************************************            
      *                 WRITE LINHA FROM LIN-W4
*******************************************************    
      *                 MOVE "TOTAL SM + RNV" TO SIT-W5
      *                 MOVE 14 TO IND-W
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
*******************************************************            
      *                 WRITE LINHA FROM LIN-W4
*******************************************************                
      *                 MOVE 08 TO IND-W
      * CNH
      *    WHEN 09
*******************************************************            
      *                 WRITE LINHA FROM LIN-W4
*******************************************************           
      *                 MOVE "CNH" TO SIT-W5B
      *                 MOVE "  11" TO TR-W5B
      *                 WRITE LINHA FROM DET-W5B
      *                 MOVE "NAO HOMOLOGADO" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
*******************************************************            
      *                 WRITE LINHA FROM LIN-W4
*******************************************************
      * NEGATIVA DE COBERTURA
      *    WHEN 10
*******************************************************
      *                 WRITE LINHA FROM LIN-W4
*******************************************************           
      *                 MOVE "NEGATIVA" TO SIT-W5B
      *                 MOVE "  15" TO TR-W5B
      *                 WRITE LINHA FROM DET-W5B
      *                 MOVE "COBERTURA" TO SIT-W5
      *                 PERFORM 620-MOVE-VALORES
      *                 PERFORM 650-GRAVA
*******************************************************            
      *                 WRITE LINHA FROM LIN-W4
*******************************************************                   
       END-EVALUATE.
       

       600-EXIT.
           EXIT.
      *
       620-MOVE-VALORES SECTION.
       620-00.
           MOVE QTD-W(IND-W)       TO QTD-MASC.
           MOVE QTD-MASC           TO QTD-W5.
           MOVE TVENCIDO-W(IND-W)  TO VENCIDO-W5.
           MOVE TVENCENDO-W(IND-W) TO VENCENDO-W5.
           MOVE TVAF3-W(IND-W)     TO VAF3-W5.
           MOVE TVAF4-W(IND-W)     TO VAF4-W5.

       COMPUTE TNOVADO4-W(IND-W)= TVENCIDO-W(IND-W) + TVENCENDO-W(IND-W)
                                   + TVAF3-W(IND-W) + TVAF4-W(IND-W).

       COMPUTE TNOVADO-W(IND-W) = TVENCIDO-W(IND-W) + TVENCENDO-W(IND-W)
                                             + TVAF3-W(IND-W).

           MOVE TNOVADO4-W(IND-W) TO TNOVADO4-W5.
      *    MOVE TNOVADO-W(IND-W)  TO TNOVADO-W5.
      *    MOVE TSEMNOV-W(IND-W)  TO SLDSEMNOV-W5.
       620-EXIT.
           EXIT.
      *
       650-GRAVA SECTION.
       650-00.
           WRITE LINHA FROM DET-W5
                 AT EOP
                 WRITE LINHA FROM LIN-W4
                 PERFORM 500-CABEC.
       650-EXIT.
           EXIT.
      *
       700-PROCURA-SFHCAD SECTION.
       700-00.

           READ  SFHCAD
                 INVALID KEY
                 MOVE 1 TO WS-EXISTE
                 GO TO 700-EXIT.

      * CESSAO BRADESCO - ESTOU USANDO A MESMA VARIAVEL SOMENTE PARA QUE
      * ELE SAIA QUANDO FOR UM CLIENTE CEDIDO

           IF BOSFH01CESSAO EQUAL 2
              MOVE 1 TO WS-EXISTE
           ELSE
               MOVE 0 TO WS-EXISTE.

       700-EXIT.
           EXIT.
      *
       800-LE-SFHCEF SECTION.
       800-00.

           READ    SFHCEF-S
                   AT END
                   MOVE HIGH-VALUES TO BOSFH06KEY-S.
       800-EXIT.
           EXIT.
      *
       999-FIM SECTION.
       999-00.
           DISPLAY    'FIM DE PROCESSAMENTO - SFH017' AT LINE 25 COL 20.
           DISPLAY LIMPA-TELA.
           DISPLAY LIMPA-TELA  AT LINE 10 COL 10.
           CLOSE   RELATO.
           CLOSE   SFHCEF-S.
           CLOSE   SFHCAD.
       999-EXIT.
           EXIT.
`

**Comment by GitMensch** [comment]
@ColinDuquesnoy as I miss the necessary rights: please close this issue.

@cuervojones This is the wrong place for questions related to COBOL or the compiler. Use the official mailing lists https://savannah.gnu.org/mail/?group=gnucobol or the discussion board at https://sourceforge.net/p/open-cobol/discussion/ the GnuCOBOL community will gladly help you there. And please provide at least the output of `cobc --version` (found in OCIDE -> About) - in any case I'd suggest to upgrade to most recent version of the GnuCOBOL compiler.

**Comment by cuervojones** [comment]
Ok, thank you!
