### ISSUE TITLE
[Unhandled exception] UnicodeDecodeError

### ISSUE THREAD

**Issue by HadeeqaKaramat** [OpenCobolIDE/OpenCobolIDE#410]
### Description

My applications won't launch

### Traceback

```
  File "open_cobol_ide\controllers\file.py", line 129, in save_current
  File "d:\users\colin\documents\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py", line 1244, in save_current
  File "d:\users\colin\documents\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py", line 1256, in _save
  File "c:\python\32-bit\3.4\lib\encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>
```

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.6
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Python: 3.4.4 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.11.0
- pyqode.cobol: 2.11.0
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.3.0

Application log: https://gist.github.com/54879fc9932ac1579265f23b27d28227

**Comment by ColinDuquesnoy** [comment]
Does it happen with a new file created by OpenCobolIDE or by a file you created with another editor?

The IDE fails to save one of the open editor, can you please attach the file that causes the problem?

**Comment by GitMensch** [comment]
@HadeeqaKaramat What was the reason for the bug, how did you solved it? No matter how you reached the error it should simply not happen.

**Comment by HadeeqaKaramat** [comment]
I'm sorry for the trouble I caused you. I don't remember when this problem occured or which file caused it.

**Comment by GitMensch** [comment]
@ColinDuquesnoy Looking at the application log: Could it be that a binary file was opened and pressing "save" caused this issue? I just did this (opened the OpenCobolIDE.lnk file on the desktop), got the "There was a problem opening the file, choose encoding" message and pressing save raises this exception.
Shouldn't the save be prohibited (=auto-read-only) as long as opening the file doesn't work without errors (=an encoding was used that "worked")?

**Comment by ColinDuquesnoy** [comment]
@GitMensch Thank you for investigating. Yes this is probably what happened.
