### ISSUE TITLE
OpenCobolIDE with Accept with decimal point

### ISSUE THREAD

**Issue by claudiomiguelmuller** [OpenCobolIDE/OpenCobolIDE#419]
Hi,
i have:

decimal point is comma.
Working:
01 edit pic zz9,99.
procedure.

accept edit at 1010

but i dont use "." or ","

How do I make it work?
I already tried a lot but I did not understand how.

I use opencobolide to compile and run

Windows 7.
Opencobolide 4.7.6
Cobc version 2.0.0

**Comment by GitMensch** [comment]
The support for `ACCEPT`ing a field with any other definition than "plain" `PIC X` is not very well in GnuCOBOL yet.
As this has nothing to do with OCIDE but with the underlying COBOL compiler (which you may change) I'd vote for closing this ticket.

@claudiomiguelmuller For compiler / runtime specific issues and some hints how to do this ask at https://sourceforge.net/p/open-cobol/discussion/
BTW: I'd normally go with something like `ACCEPT fieldXXXXXX   MOVE FUNCTION NUMVAL(field) TO field999v99`
