### ISSUE TITLE
FR: allow [F1] Help in dialogs (especially preferences)

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#431]
### Description

with either the "normal" call to http://opencobolide.readthedocs.io/en/latest or even better the call to the specific section.
If this is done the link on preferences->sql to http://opencobolide.readthedocs.io/en/latest/advanced.html#how-to-setup-dbpre-integration-with-opencobolide could be removed from the dialog

**Comment by ColinDuquesnoy** [comment]
Sorry no new features.
