### ISSUE TITLE
FR: add a keystroke to set the cursor to the next/previous margin

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#433]
### Description

maybe something like [ALT]+[TAB] / [ALT]+[SHIFT]+[TAB]

This would be quite handy and looks like an easy addition

**Comment by ColinDuquesnoy** [comment]
Being easy is not a criteria. I won't implement ANY new feature in OCIDE.

**Comment by GitMensch** [comment]
Then this may be something to be reminded for HE :-)
