### ISSUE TITLE
4.3.0 beta released

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#95]
Hello,

I've just released a beta version with all the fixes for the bug reported by @Astalaseven  and @Bofinken. The beta also includes experimental support for SQL Cobol on Linux and for using a custom GnuCobol compiler on Windows.

Installer for Windows and Mac OSX are available in the [release section on github](https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.3.0b).

Linux users need to upgrade OpenCobolIDE and pyQode from source checkout. This can easily be done by running the following commands:

```
sudo pip3 install git+https://github.com/pyQode/pyqode.qt.git --upgrade
sudo pip3 install git+https://github.com/pyQode/pyqode.core.git --upgrade
sudo pip3 install git+https://github.com/pyQode/pyqode.cobol.git --upgrade
sudo pip3 install git+https://github.com/OpenCobolIDE/OpenCobolIDE.git --upgrade
```

I already updated the documentation. There are 3 new topics:

- [a description of the preferences settings](http://opencobolide.readthedocs.org/en/latest/settings.html)
- [a guide on how to use a custom compiler on windows](http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-use-a-custom-gnucobol-compiler-build-on-windows)
- [a guide on how to setup dbpre integration on linux](http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-setup-dbpre-integration-with-opencobolide)

@Bofinken, @Astalaseven, @LuizFlavio, @martyheyman, @abbhishek Please give it a try! Feel free to give your feedback in this thread!

The final release is planned for the 11th January 2015.

**Comment by Bofinken** [comment]
I found an issue, but I think it was present before.

The navigation outline should not show the 88 values only W-RUBRIC-SPEC PIC
X(10)

WORKING-STORAGE SECTION.

01 W-RUBRIC-SPEC PIC X(10).

   88 RUBRIC-SPEC VALUES ARE

              'ALFA ',

              'BRAVO ',

              'CHARLIE ',

              'DELTA '.

 

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 31 december 2014 16:13
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: [OpenCobolIDE] 4.3.0 beta released (#95)

 

Hello,

I've just released a beta version with all the fixes for the bug reported by
@Astalaseven <https://github.com/Astalaseven>  and @bofinken
<https://github.com/bofinken> . The beta also includes experimental support
for SQL Cobol on Linux and for using a custom GnuCobol compiler on Windows.

Installer for Windows and Mac OSX are available in the release
<https://github.com/OpenCobolIDE/OpenCobolIDE/releases/tag/4.3.0b>  section
on github.

Linux users need to upgrade OpenCobolIDE and pyQode from source checkout.
This can easily be done by running the following commands:

sudo pip3 install git+https://github.com/pyQode/pyqode.qt.git --upgrade
sudo pip3 install git+https://github.com/pyQode/pyqode.core.git --upgrade
sudo pip3 install git+https://github.com/pyQode/pyqode.cobol.git --upgrade
sudo pip3 install git+https://github.com/OpenCobolIDE/OpenCobolIDE.git
--upgrade

I already updated the documentation. There are 3 new topics:

*	a <http://opencobolide.readthedocs.org/en/latest/settings.html>
description of the preferences settings
*	a
<http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-use-a-cu
stom-gnucobol-compiler-build-on-windows>  guide on how to use a custom
compiler on windows
*	a
<http://opencobolide.readthedocs.org/en/latest/advanced.html#how-to-setup-db
pre-integration-with-opencobolide>  guide on how to setup dbpre integration
on linux

@bofinken <https://github.com/bofinken> , @Astalaseven
<https://github.com/Astalaseven> , @LuizFlavio
<https://github.com/LuizFlavio> , @martyheyman
<https://github.com/martyheyman> , @abbhishek <https://github.com/abbhishek>
Please give it a try! Feel free to give your feedback in this thread!

The final release is planned for the 11th January 2015.

—
Reply to this email directly or view it on GitHub
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/95> .
<https://github.com/notifications/beacon/AGDDmNcDDO5fBUh5wdNYN30iGbhCBlVHks5
ndAoPgaJpZM4DNfNa.gif>

**Comment by abbhishek** [comment]
Hi Colin,

Sorry I wasn't able to test your build .... Was busy with some personal
stuff. Will test your beta and will let you know.
For the compiler issue that you told looks to be a dealbreaker.  I was able
to compile dbpre using cygwin, but could not get the mysqlcobolapi
compiled. Can using cygwin reduce the dependency on visual studio?
And another problem that has cropped up is that my govt has banned github
in india, so am not able to pull your source. Is there an alternative?

**Comment by ColinDuquesnoy** [comment]
> The navigation outline should not show the 88 values only W-RUBRIC-SPEC PIC X(10)

@Bofinken Indeed, it was present before. I'll fix that for the final release ;) thanks!

> Can using cygwin reduce the dependency on visual studio?

Yes but I guess you'll probably have to compile both mysql connector and GnuCobol with cygwin.

> And another problem that has cropped up is that my govt has banned github in india, so am not able to pull your source. 

That's annoying. No, not at the moment. There are no up to date source mirrors but I can try to create one on launchpad.net if it is available for you.

**Comment by abbhishek** [comment]
@colin: I'll try to setup cygwin and get it working. Let's see if it works.
Will it be possible for you to include cygwin.dll in your distribution as
the exe's generated have a dependency on them? Is it allowed?

**Comment by ColinDuquesnoy** [comment]
@abbhishek The IDE will automatically copy any dll file found in the compiler directory. E.g. if you compiled GnuCobol with cygwin and installed it to c:\GnuCobol, just copy the cygwin dll there and the IDE will automatically copy c:\GnuCobol\*.dll next to your compiled program.

**Comment by ColinDuquesnoy** [comment]
The new version has been released officially, both on githubs, pypi and launchpad.

@Bofinken the lvl 88 variables issue should be fixed, I added a unit test for this case.

**Comment by ColinDuquesnoy** [comment]
@Bofinken in OCIDE 4.7.3 level 88 variables will show up in the navigation tree (see #323). In a future release you'll have an option to hide level 88 variables in the navigation tree but still parse them for autocompletion and goto.
