### ISSUE TITLE
[FeatureRequest] Restore cursor position after reloading a file due to external changes

### ISSUE THREAD

**Issue by Bofinken** [OpenCobolIDE/OpenCobolIDE#97]
### Description of the issue
Enhancement request, when the file I work with has been changed by the file system, I just want to be notified about it and keep the same row position. Now I get to the beginning of the file.
### System information
* Operating System: win7 64
* OpenCobolIDE Versinion:4.3.0

**Comment by ColinDuquesnoy** [comment]
Thanks for the report, I'll add for the next bug fix release.

**Comment by Bofinken** [comment]
Just a thought, but when you press ”Report a bug” in the IDE, can you pass
along the version number from the IDE?

 

  _____  

Från: Colin Duquesnoy [mailto:notifications@github.com] 
Skickat: den 28 januari 2015 13:11
Till: OpenCobolIDE/OpenCobolIDE
Kopia: Bofinken
Ämne: Re: [OpenCobolIDE] [FeatureRequest] Restore cursor position after
reloading a file due to external changes (#97)

 

Thanks for the report, I'll add for the next bug fix release.

—
Reply to this email directly or view
<https://github.com/OpenCobolIDE/OpenCobolIDE/issues/97#issuecomment-7182549
8>  it on GitHub.
<https://github.com/notifications/beacon/AGDDmBvReEQrDuL8ytvUmDdZ8CHYkS6Vks5
nmMk2gaJpZM4DYSeb.gif>

**Comment by ColinDuquesnoy** [comment]
It would be nice indeed. I'll have a look and see if it is possible.

**Comment by ColinDuquesnoy** [comment]
If that works I might push it a little further and include more information (such as the system information and maybe the log or at least important debugging data). I might also add a form for filling up the description and setup a proper title with an auto generated prefix (e.g. [BUG], [WISH],...).

**Comment by ColinDuquesnoy** [comment]
Note for myself: this is what I need to use: https://developer.github.com/v3/issues/#create-an-issue. And there is already a python wrapper API: https://github.com/ChristopherMacGown/python-github3

**Comment by ColinDuquesnoy** [comment]
Your initial request has been implemented in master branch.
