### ISSUE TITLE
Getting clang error

### ISSUE THREAD

**Issue by rajdeepsinghal** [OpenCobolIDE/OpenCobolIDE#99]
WHILE I'M RUNNING MY CODE(in mac YOSEMITE 10.10.2 )
getting error
clang: error: unknown argument: '-R/opt/local/lib'

**Comment by ColinDuquesnoy** [comment]
Does it work if you build and run your code from the terminal? 

I cannot reproduce your problem. I'll need the following info to have a chance to figure it out:
- what version of GnuCobol are you using and how did you install it?
- a [SSCCE](http://sscce.org/) would be helpful

At a first glance, this looks like a GnuCobol problem but I might be wrong. If you're still using OpenCobol 1.1, try to upgrade it to GnuCobol 2.0.

**Comment by ColinDuquesnoy** [comment]
This is not a bug with the IDE but with the compiler. Have a look at this link: http://sourceforge.net/p/open-cobol/discussion/help/thread/e1b4af35/

**Comment by rajdeepsinghal** [comment]
Yeah I'm having the same problem.But the thread is not helping me I tried the fix they mentioned but still getting the same error.
And can you help me upgrading to GnuCobol 2.0, may be it helps !

**Comment by ColinDuquesnoy** [comment]
Actually I am still using OpenCobol 1.1 on Yosemite 10.10.2 but I installed it with homebrew. HTH
